// ------------------------------------------------------------------------------------------------
// <copyright file="IOrganizationService.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Dal.AutoGeneratedServices
{
    using ErrorOr;

    using Mycelium.Forge.Common;

    /// <summary>
    /// Defines custom service operations for <see cref="IOrganization" /> instances.
    /// </summary>
    public partial interface IOrganizationService
    {
        /// <summary>
        /// Asynchronously reads a single <see cref="IOrganization" /> instance matching the specified organization short name
        /// managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="shortName">The short name of the organization.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{TValue}" /> containing the permitted <see cref="IOrganization" /> or an error.</returns>
        Task<ErrorOr<IOrganization>> ReadByShortNameAsync(IUserContext userContext, string shortName, CancellationToken token = default);
    }
}
