// ------------------------------------------------------------------------------------------------
// <copyright file="OrganizationService.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Dal.AutoGeneratedServices
{
    using ErrorOr;

    using Microsoft.Extensions.Logging;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Common.Extensions;
    using Mycelium.Forge.Dal.Extensions;
    using Mycelium.Forge.Orm.AutoGeneratedFilters;
    using Mycelium.Forge.Orm.Filters;

    using NpgsqlTypes;

    /// <summary>
    /// Service implementation for managing <see cref="IOrganization" /> instances, bringing validation, permissions, and data
    /// persistence together.
    /// </summary>
    public partial class OrganizationService
    {
        /// <summary>
        /// Asynchronously reads a single <see cref="IOrganization" /> instance matching the specified organization short name
        /// managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="shortName">The short name of the organization.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{TValue}" /> containing the permitted <see cref="IOrganization" /> or an error.</returns>
        public async Task<ErrorOr<IOrganization>> ReadByShortNameAsync(IUserContext userContext, string shortName, CancellationToken token = default)
        {
            ArgumentNullException.ThrowIfNull(userContext);

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting ReadByShortNameAsync for Organization: shortName {ShortName}", shortName.SanitizeForLog());
            }

            var filter = (SqlFilter)OrganizationReadFilter.FromUserContext(userContext);

            filter.Where(
                """
                LOWER("Thing"."data"->>'shortName') = LOWER(@shortName)
                """);

            filter.AddParameter("@shortName", NpgsqlDbType.Text, shortName);

            var readResult = await this.databaseSource.ReadWithFilterAsync((transaction, cancellationToken) => this.dao.ReadAsync(transaction, cancellationToken, filter: filter), this.permissionService, userContext, this.logger, token);

            if (readResult.IsError)
            {
                return readResult.Errors;
            }

            var item = readResult.Value.FirstOrDefault();

            if (item == null)
            {
                return Error.NotFound(description: $"Organization with short name '{shortName}' was not found.");
            }

            return (Organization)item;
        }
    }
}
