// ------------------------------------------------------------------------------------------------
// <copyright file="PackageService.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Dal.AutoGeneratedServices
{
    using ErrorOr;

    using Microsoft.Extensions.Logging;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Common.Extensions;
    using Mycelium.Forge.Orm.AutoGeneratedFilters;
    using Mycelium.Forge.Orm.Filters;

    using Npgsql;

    using NpgsqlTypes;

    /// <summary>
    /// Service implementation for managing <see cref="IPackage" /> instances, bringing validation, permissions, and data
    /// persistence together.
    /// </summary>
    public partial class PackageService
    {
        /// <summary>
        /// Asynchronously reads a single <see cref="IPackage" /> instance matching the specified scope and package short name
        /// within an existing transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="scopeShortName">The short name of the owning scope (organization or account).</param>
        /// <param name="packageShortName">The short name of the package.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{TValue}" /> containing the permitted <see cref="IPackage" /> or an error.</returns>
        public async Task<ErrorOr<IPackage>> ReadByCoordinateAsync(IUserContext userContext, NpgsqlTransaction transaction, string scopeShortName, string packageShortName, CancellationToken token = default)
        {
            ArgumentNullException.ThrowIfNull(userContext);
            ArgumentNullException.ThrowIfNull(transaction);

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting ReadByCoordinateAsync for Package within transaction: scope {Scope}, package {Package}", scopeShortName.SanitizeForLog(), packageShortName.SanitizeForLog());
            }

            var filter = (SqlFilter)PackageReadFilter.FromUserContext(userContext);

            filter.Where(
                """
                LOWER("Thing"."data"->>'shortName') = LOWER(@packageShortName)
                AND EXISTS (
                    SELECT 1 FROM "Forge"."Thing" AS "OwnerThing"
                    WHERE "OwnerThing"."id" = "Package"."owner"
                      AND LOWER("OwnerThing"."data"->>'shortName') = LOWER(@scopeShortName)
                )
                """);

            filter.AddParameter("@packageShortName", NpgsqlDbType.Text, packageShortName);
            filter.AddParameter("@scopeShortName", NpgsqlDbType.Text, scopeShortName);

            var readResult = await this.dao.ReadAsync(transaction, token, filter: filter);

            if (readResult.IsError)
            {
                return readResult.Errors;
            }

            var item = readResult.Value.FirstOrDefault();

            if (item == null)
            {
                return Error.NotFound(description: $"Package with scope '{scopeShortName}' and name '{packageShortName}' was not found.");
            }

            var permissionResult = await this.permissionService.IsAllowedToRead(userContext, item, transaction);

            if (permissionResult.IsError)
            {
                return permissionResult.Errors;
            }

            return (Package)item;
        }

        /// <summary>
        /// Asynchronously reads a single <see cref="IPackage" /> instance matching the specified scope and package short name
        /// managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="scopeShortName">The short name of the owning scope (organization or account).</param>
        /// <param name="packageShortName">The short name of the package.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{TValue}" /> containing the permitted <see cref="IPackage" /> or an error.</returns>
        public async Task<ErrorOr<IPackage>> ReadByCoordinateAsync(IUserContext userContext, string scopeShortName, string packageShortName, CancellationToken token = default)
        {
            ArgumentNullException.ThrowIfNull(userContext);

            try
            {
                await using var connection = await this.databaseSource.OpenNewConnectionAsync(token);
                await using var transaction = await connection.BeginTransactionAsync(token);

                var result = await this.ReadByCoordinateAsync(userContext, transaction, scopeShortName, packageShortName, token);

                if (result.IsError)
                {
                    await transaction.RollbackAsync(token);
                    return result.Errors;
                }

                await transaction.CommitAsync(token);
                return result;
            }
            catch (Exception exception)
            {
                this.logger.LogError(exception, "ReadByCoordinateAsync for Package failed with an error: scope {Scope}, package {Package}", scopeShortName.SanitizeForLog(), packageShortName.SanitizeForLog());

                return Error.Failure(description: exception.Message);
            }
        }
    }
}
