// ------------------------------------------------------------------------------------------------
// <copyright file="OrganizationDetailsViewModelTestFixture.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Tests.ViewModels.OrganizationDetails
{
    using System;
    using System.Collections.Immutable;
    using System.Threading;
    using System.Threading.Tasks;

    using ErrorOr;

    using Microsoft.Extensions.Logging;

    using Moq;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Dal.AutoGeneratedServices;
    using Mycelium.Forge.Services;
    using Mycelium.Forge.ViewModels.OrganizationDetails;

    [TestFixture]
    public class OrganizationDetailsViewModelTestFixture
    {
        private Mock<IOrganizationService> organizationServiceMock;
        private Mock<IPackageService> packageServiceMock;
        private Mock<IPackageVersionService> packageVersionServiceMock;
        private Mock<IPackageTypeService> packageTypeServiceMock;
        private Mock<IUserService> userServiceMock;
        private Mock<ILogger<OrganizationDetailsViewModel>> loggerMock;
        private OrganizationDetailsViewModel viewModel;

        [SetUp]
        public void SetUp()
        {
            this.organizationServiceMock = new Mock<IOrganizationService>();
            this.packageServiceMock = new Mock<IPackageService>();
            this.packageVersionServiceMock = new Mock<IPackageVersionService>();
            this.packageTypeServiceMock = new Mock<IPackageTypeService>();
            this.userServiceMock = new Mock<IUserService>();
            this.loggerMock = new Mock<ILogger<OrganizationDetailsViewModel>>();

            this.viewModel = new OrganizationDetailsViewModel(this.organizationServiceMock.Object, this.packageServiceMock.Object, this.packageVersionServiceMock.Object, this.packageTypeServiceMock.Object, this.userServiceMock.Object, this.loggerMock.Object);
        }

        [Test]
        public async Task VerifyInitializeViewModel()
        {
            var adminAccountId = Guid.NewGuid();
            var nonAdminAccountId = Guid.NewGuid();
            var orgId = Guid.NewGuid();
            var packageId = Guid.NewGuid();
            var versionId = Guid.NewGuid();
            var packageTypeId = Guid.NewGuid();

            var organization = new Organization
            {
                Id = orgId,
                Name = "Starion Group",
                ShortName = "starion",
                Origin = "https://example.com",
                Administrator = [adminAccountId],
                OwnedPackage = [packageId]
            };

            var package = new Package
            {
                Id = packageId,
                Name = "sysmlv2-kernel-library",
                ShortName = "sysmlv2-kernel-library",
                Owner = orgId,
                Version = [versionId],
                PackageType = packageTypeId
            };

            var packageVersion = new PackageVersion
            {
                Id = versionId,
                Owner = packageId,
                Version = "1.0.0",
                Listed = true,
                PublicationDate = DateTime.UtcNow
            };

            var packageType = new PackageType
            {
                Id = packageTypeId,
                Name = "SysML v2"
            };

            var adminUserContext = new UserContext
            {
                AccountId = adminAccountId,
                CurrentRoles = [RoleKind.Account]
            };

            // Scenario 1: Organization service returns error
            this.userServiceMock.Setup(x => x.GetUserContext()).ReturnsAsync(adminUserContext);

            this.organizationServiceMock.Setup(x => x.ReadByShortNameAsync(It.IsAny<IUserContext>(), "unknown", It.IsAny<CancellationToken>()))
                .ReturnsAsync(Error.NotFound("Not found"));

            await this.viewModel.InitializeViewModel("unknown");

            using (Assert.EnterMultipleScope())
            {
                Assert.That(this.viewModel.Organization, Is.Null);
                Assert.That(this.viewModel.Packages, Has.Count.EqualTo(0));
            }

            // Scenario 2: Happy path with admin by membership
            this.organizationServiceMock.Setup(x => x.ReadByShortNameAsync(It.IsAny<IUserContext>(), "starion", It.IsAny<CancellationToken>()))
                .ReturnsAsync(organization);

            this.packageServiceMock.Setup(x => x.ReadAsync(It.IsAny<IUserContext>(), It.IsAny<CancellationToken>(), It.IsAny<Guid[]>()))
                .ReturnsAsync(ImmutableList.Create<IPackage>(package));

            this.packageVersionServiceMock.Setup(x => x.ReadAsync(It.IsAny<IUserContext>(), It.IsAny<CancellationToken>(), It.IsAny<Guid[]>()))
                .ReturnsAsync(ImmutableList.Create<IPackageVersion>(packageVersion));

            this.packageTypeServiceMock.Setup(x => x.ReadAsync(It.IsAny<IUserContext>(), It.IsAny<CancellationToken>(), It.IsAny<Guid[]>()))
                .ReturnsAsync(ImmutableList.Create<IPackageType>(packageType));

            await this.viewModel.InitializeViewModel("@starion");

            using (Assert.EnterMultipleScope())
            {
                Assert.That(this.viewModel.Organization, Is.Not.Null);
                Assert.That(this.viewModel.Organization.ShortName, Is.EqualTo("starion"));
                Assert.That(this.viewModel.IsUserAdmin, Is.True);
                Assert.That(this.viewModel.Packages, Has.Count.EqualTo(1));
                Assert.That(this.viewModel.Packages[0].IsVerified, Is.False);
            }

            // Scenario 3: User is admin by permission (InstallationAdministrator)
            var installAdminContext = new UserContext
            {
                AccountId = nonAdminAccountId,
                CurrentRoles = [RoleKind.InstallationAdministrator]
            };

            this.userServiceMock.Setup(x => x.GetUserContext()).ReturnsAsync(installAdminContext);

            await this.viewModel.InitializeViewModel("starion");
            Assert.That(this.viewModel.IsUserAdmin, Is.True);

            // Scenario 4: User is not admin
            var regularUserContext = new UserContext
            {
                AccountId = nonAdminAccountId,
                CurrentRoles = [RoleKind.Account]
            };

            this.userServiceMock.Setup(x => x.GetUserContext()).ReturnsAsync(regularUserContext);

            await this.viewModel.InitializeViewModel("starion");
            Assert.That(this.viewModel.IsUserAdmin, Is.False);
        }
    }
}
