import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

const currentDirectory = path.dirname(fileURLToPath(import.meta.url));

/**
 * Parses command-line arguments formatted as --key=value.
 * @param {string[]} args - Process arguments.
 * @returns {Record<string, string>} Parsed arguments dictionary.
 */
function parseArguments(args) {
  const result = {};
  for (const argument of args) {
    if (argument.startsWith('--')) {
      const [key, ...valueParts] = argument.slice(2).split('=');
      result[key] = valueParts.join('=') || 'true';
    }
  }
  return result;
}

const commandLineArguments = parseArguments(process.argv.slice(2));
const target = commandLineArguments.target || 'all';

const defaultTokensDirectory = path.resolve(currentDirectory, '..', 'Styles', 'tokens');
const tokensDirectory = commandLineArguments.tokensDir
  ? path.resolve(process.cwd(), commandLineArguments.tokensDir)
  : defaultTokensDirectory;

const defaultOutputDirectory = path.resolve(currentDirectory, '..', 'Styles', 'dist');
const outputDirectory = commandLineArguments.outDir
  ? path.resolve(process.cwd(), commandLineArguments.outDir)
  : defaultOutputDirectory;

if (!fs.existsSync(outputDirectory)) {
  fs.mkdirSync(outputDirectory, { recursive: true });
}

/**
 * Creates a StyleDictionary instance configured for a specific product and theme mode.
 * @param {string} product - 'forge' or 'bloom'
 * @param {string} mode - 'light' or 'dark'
 * @param {string} destinationFileName - Output file name
 * @param {string} selector - CSS rule selector (':root' or '.dark')
 * @returns {StyleDictionary} Configured StyleDictionary instance
 */
function createStyleDictionaryInstance(product, mode, destinationFileName, selector) {
  const sharedGlob = path.posix.join(tokensDirectory.replace(/\\/g, '/'), 'shared/**/*.json');
  const semanticsGlob = path.posix.join(tokensDirectory.replace(/\\/g, '/'), `${product}-${mode}/**/*.json`);

  return new StyleDictionary({
    parsers: ['dtcg-primitives-shim', 'dtcg-semantics-shim'],
    hooks: {
      parsers: {
        'dtcg-primitives-shim': {
          pattern: /mycelium-primitives\.json$/,
          parser: ({ contents }) => {
            const parsed = JSON.parse(contents);
            if (parsed.radius) {
              for (const [key, token] of Object.entries(parsed.radius)) {
                if (token.$type === 'number') {
                  token.$type = 'dimension';
                  const val = key === 'full' ? 9999 : token.$value;
                  token.$value = { value: val, unit: 'px' };
                }
              }
            }
            return parsed;
          }
        },
        'dtcg-semantics-shim': {
          pattern: /mycelium-semantics\.json$/,
          parser: ({ contents }) => {
            const parsed = JSON.parse(contents);
            // Remove colliding identity alias groups that re-declare primitives
            delete parsed.radius;
            delete parsed.spacing;
            delete parsed.text;
            delete parsed.$extensions;
            return parsed;
          }
        }
      }
    },
    source: [sharedGlob, semanticsGlob],
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: `${outputDirectory.replace(/\\/g, '/')}/`,
        files: [
          {
            destination: destinationFileName,
            format: 'css/variables',
            options: {
              selector: selector,
              outputReferences: true
            }
          }
        ]
      }
    }
  });
}

/**
 * Builds the tokens for a product (light, dark, and combined css).
 * @param {string} product - 'forge' or 'bloom'
 */
async function buildProductTokens(product) {
  console.log(`Building tokens for ${product}...`);

  const lightFileName = `tokens-${product}-light.css`;
  const darkFileName = `tokens-${product}-dark.css`;
  const combinedFileName = `tokens-${product}.css`;

  const styleDictionaryLight = createStyleDictionaryInstance(product, 'light', lightFileName, ':root');
  const styleDictionaryDark = createStyleDictionaryInstance(product, 'dark', darkFileName, '.dark');

  await styleDictionaryLight.buildAllPlatforms();
  await styleDictionaryDark.buildAllPlatforms();

  const lightContent = fs.readFileSync(path.join(outputDirectory, lightFileName), 'utf8');
  const darkContent = fs.readFileSync(path.join(outputDirectory, darkFileName), 'utf8');

  // Generate combined file (:root + .dark)
  const combinedContent = `/**\n * Design Tokens - Combined (${product})\n * Auto-generated by Style Dictionary pipeline.\n */\n\n${lightContent}\n\n${darkContent}\n`;
  fs.writeFileSync(path.join(outputDirectory, combinedFileName), combinedContent, 'utf8');

  console.log(`Generated: ${lightFileName}, ${darkFileName}, ${combinedFileName}`);
}

async function main() {
  try {
    if (target === 'forge' || target === 'all') {
      await buildProductTokens('forge');
    }
    if (target === 'bloom' || target === 'all') {
      await buildProductTokens('bloom');
    }
    console.log('Design token generation completed successfully.');
  } catch (error) {
    console.error('Error generating design tokens:', error);
    process.exit(1);
  }
}

await main();
