// ------------------------------------------------------------------------------------------------
// <copyright file="PackageDetailsViewModel.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.ViewModels.PackageDetails
{
    using Mycelium.Forge.Common;
    using Mycelium.Forge.Dal.AutoGeneratedServices;
    using Mycelium.Forge.Extensions;
    using Mycelium.Forge.Model;
    using Mycelium.Forge.Models.DialogResults;
    using Mycelium.Forge.Services;

    /// <summary>
    /// Provides view model state and initialization logic for the Mycelium Forge package details page.
    /// </summary>
    public class PackageDetailsViewModel : IPackageDetailsViewModel
    {
        /// <summary>
        /// The (injected) <see cref="IAccountService" /> used to retrieve maintainer accounts.
        /// </summary>
        private readonly IAccountService accountService;

        /// <summary>
        /// The (injected) <see cref="INotificationService" /> used to emit notifications.
        /// </summary>
        private readonly INotificationService notificationService;

        /// <summary>
        /// The (injected) <see cref="IOrganizationService" /> used to retrieve organization data.
        /// </summary>
        private readonly IOrganizationService organizationService;

        /// <summary>
        /// The (injected) <see cref="IPackageMetaDataService" /> used to retrieve package metadata.
        /// </summary>
        private readonly IPackageMetaDataService packageMetaDataService;

        /// <summary>
        /// The (injected) <see cref="IPackageService" /> used to retrieve package data.
        /// </summary>
        private readonly IPackageService packageService;

        /// <summary>
        /// The (injected) <see cref="IPackageTypeService" /> used to retrieve package type data.
        /// </summary>
        private readonly IPackageTypeService packageTypeService;

        /// <summary>
        /// The (injected) <see cref="IPackageVersionService" /> used to retrieve package version data.
        /// </summary>
        private readonly IPackageVersionService packageVersionService;

        /// <summary>
        /// The (injected) <see cref="IUserService" /> used to retrieve the current user context.
        /// </summary>
        private readonly IUserService userService;

        /// <summary>
        /// Initializes a new instance of the <see cref="PackageDetailsViewModel" /> class.
        /// </summary>
        /// <param name="packageService">The (injected) <see cref="IPackageService" />.</param>
        /// <param name="organizationService">The (injected) <see cref="IOrganizationService" />.</param>
        /// <param name="packageVersionService">The (injected) <see cref="IPackageVersionService" />.</param>
        /// <param name="packageMetaDataService">The (injected) <see cref="IPackageMetaDataService" />.</param>
        /// <param name="packageTypeService">The (injected) <see cref="IPackageTypeService" />.</param>
        /// <param name="accountService">The (injected) <see cref="IAccountService" />.</param>
        /// <param name="userService">The (injected) <see cref="IUserService" />.</param>
        /// <param name="notificationService">The (injected) <see cref="INotificationService" />.</param>
        public PackageDetailsViewModel(IPackageService packageService, IOrganizationService organizationService, IPackageVersionService packageVersionService,
            IPackageMetaDataService packageMetaDataService, IPackageTypeService packageTypeService, IAccountService accountService, IUserService userService, INotificationService notificationService)
        {
            this.packageService = packageService;
            this.organizationService = organizationService;
            this.packageVersionService = packageVersionService;
            this.packageMetaDataService = packageMetaDataService;
            this.packageTypeService = packageTypeService;
            this.accountService = accountService;
            this.userService = userService;
            this.notificationService = notificationService;
        }

        /// <summary>
        /// Gets or sets the underlying package DTO.
        /// </summary>
        public IPackage Package { get; set; }

        /// <summary>
        /// Gets or sets the owning organization DTO.
        /// </summary>
        public IOrganization Organization { get; set; }

        /// <summary>
        /// Gets or sets the package type DTO.
        /// </summary>
        public IPackageType PackageType { get; set; }

        /// <summary>
        /// Gets or sets the collection of released package version DTOs.
        /// </summary>
        public IReadOnlyList<IPackageVersion> Versions { get; set; } = [];

        /// <summary>
        /// Gets or sets the collection of maintainer account DTOs.
        /// </summary>
        public IReadOnlyList<IAccount> Maintainers { get; set; } = [];

        /// <summary>
        /// Gets or sets the selected or latest package version DTO.
        /// </summary>
        public IPackageVersion SelectedVersion { get; set; }

        /// <summary>
        /// Gets or sets the collection of package metadata DTOs corresponding to package versions.
        /// </summary>
        public IReadOnlyList<IPackageMetaData> MetaDatas { get; set; } = [];

        /// <summary>
        /// Gets the package metadata DTO for the currently selected package version.
        /// </summary>
        public IPackageMetaData CurrentMetaData => this.MetaDatas.FirstOrDefault(m => m.Owner == this.SelectedVersion?.Id || m.Id == this.SelectedVersion?.MetaData);

        /// <summary>
        /// Gets the collection of model elements contained within the package release.
        /// </summary>
        public IReadOnlyList<(string Name, string Kind, string Category, string AttributeSummary)> Elements => this.CurrentMetaData?.Elements ?? [];

        /// <summary>
        /// Gets the collection of direct package dependencies resolved from the usage projection.
        /// </summary>
        public IReadOnlyList<(string Name, string Summary, bool IsVerified)> Dependencies => this.CurrentMetaData?.Dependencies ?? [];

        /// <summary>
        /// Gets the collection of packages and projects depending on this package.
        /// </summary>
        public IReadOnlyList<(string Name, string Summary, bool IsProject, bool IsVerified)> Dependents => [];

        /// <summary>
        /// Gets the collection of quality evaluation checks.
        /// </summary>
        public IReadOnlyList<(string Title, string Detail, bool Passed)> QualityChecks => this.CurrentMetaData?.QualityChecks ?? [];

        /// <summary>
        /// Gets or sets the dictionary of install commands.
        /// </summary>
        public IReadOnlyDictionary<string, string> InstallCommands { get; set; } = new Dictionary<string, string>();

        /// <summary>
        /// Gets or sets a value indicating whether the current user is an administrator of the package.
        /// </summary>
        public bool IsUserAdmin { get; set; } = true;

        /// <summary>
        /// Initializes the package view model state for the specified package name and organization asynchronously.
        /// </summary>
        /// <param name="packageName">The name of the package.</param>
        /// <param name="organization">The organization of the package.</param>
        /// <returns>A <see cref="Task" /> representing the asynchronous initialization.</returns>
        public async Task InitializeViewModel(string packageName, string organization)
        {
            var userContext = this.userService.GetUserContext();
            var allPackages = await this.packageService.ReadOrEmpty(userContext, emptyWhenNoIds: false);

            this.Package = allPackages.FirstOrDefault(p => string.Equals(p.ShortName, packageName, StringComparison.InvariantCultureIgnoreCase));

            if (this.Package == null)
            {
                return;
            }

            this.Organization = await this.organizationService.ReadOrNull(userContext, this.Package.Owner);
            this.PackageType = await this.packageTypeService.ReadOrNull(userContext, this.Package.PackageType);

            this.Versions = (await this.packageVersionService.ReadOrEmpty(userContext, this.Package.Version))
                .OrderByDescending(v => v.PublicationDate)
                .ToList();

            this.SelectedVersion = this.Versions.FirstOrDefault();

            var metaDataIds = this.Versions.Select(v => v.MetaData).Where(id => id != Guid.Empty).ToList();
            this.MetaDatas = (await this.packageMetaDataService.ReadOrEmpty(userContext, metaDataIds)).ToList();

            List<Guid> maintainerIds = [.. this.Package.PackageMaintainer, .. this.Package.PackageOwner];
            this.Maintainers = await this.accountService.ReadOrEmpty(userContext, maintainerIds);

            var publisher = this.Organization.ShortName;
            var currentVersion = this.SelectedVersion.GetVersion();

            this.InstallCommands = InstallCommandHelper.GenerateInstallCommands(publisher, this.Package.ShortName, currentVersion);
        }

        /// <summary>
        /// Initiates a migration of the package in Bloom to the specified target project and emits a user notification.
        /// </summary>
        /// <param name="result">The migration parameters including destination project and version constraint.</param>
        public void MigrateInBloom(MigrateInBloomResult result)
        {
            this.notificationService.AddNotification(
                $"Migration of package '{this.Package.Name}' to project '{result.ProjectName}' has been initiated in Bloom.",
                "Migration Initiated",
                NotificationType.Success);
        }
    }
}
