// ------------------------------------------------------------------------------------------------
// <copyright file="UserService.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Services
{
    using System.Security.Claims;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Dal.AutoGeneratedServices;
    using Mycelium.Forge.Data;

    /// <summary>
    /// Scoped service that holds the identity, profile details, and assigned roles of the currently authenticated user.
    /// One instance per Blazor circuit ensures concurrent users are isolated.
    /// </summary>
    public class UserService : IUserService
    {
        /// <summary>
        /// The injected <see cref="IAccountService" /> used to read account details.
        /// </summary>
        private readonly IAccountService accountService;

        /// <summary>
        /// The injected <see cref="IHttpContextAccessor" /> used to read HTTP request context.
        /// </summary>
        private readonly IHttpContextAccessor httpContextAccessor;

        /// <summary>
        /// Gets or sets the application and domain roles currently assigned to the user.
        /// </summary>
        /// <remarks>This will likely be removed when IAccount roles is implemented.</remarks>
        private IReadOnlyList<RoleKind> currentRoles;

        /// <summary>
        /// The underlying account entity of the currently authenticated user, if available.
        /// </summary>
        private IAccount currentUser;

        /// <summary>
        /// Initializes a new instance of the <see cref="UserService" /> class in an unauthenticated state.
        /// </summary>
        /// <param name="accountService">The injected <see cref="IAccountService" />.</param>
        /// <param name="httpContextAccessor">The optional injected <see cref="IHttpContextAccessor" />.</param>
        public UserService(IAccountService accountService, IHttpContextAccessor httpContextAccessor)
        {
            this.accountService = accountService;
            this.httpContextAccessor = httpContextAccessor;
            this.currentUser = null;
            this.currentRoles = [RoleKind.Anonymous];
        }

        /// <summary>
        /// Gets a value indicating whether the user is authenticated.
        /// </summary>
        public bool IsAuthenticated => this.currentUser != null && !this.currentRoles.Contains(RoleKind.Anonymous);

        /// <summary>
        /// Gets the current user account, optionally forcing a reload from the data source.
        /// </summary>
        /// <param name="forceLoad">The value indicating whether to force a reload.</param>
        /// <returns>A <see cref="Task{IAccount}" /> representing the asynchronous operation.</returns>
        public async Task<IAccount> GetCurrentUser(bool forceLoad = false)
        {
            await this.TryPopulateUserFromHttpContextAsync();

            if (!forceLoad || this.currentUser == null)
            {
                return this.currentUser;
            }

            var context = GetJwtContextPlaceholder(this.currentUser.Id);
            var readResult = await this.accountService.ReadAsync(context, CancellationToken.None, [this.currentUser.Id]);

            if (!readResult.IsError && !readResult.Value.IsEmpty)
            {
                this.currentUser = readResult.Value[0];
            }

            return this.currentUser;
        }

        /// <summary>
        /// Gets the user context, which includes the account ID, username, and current roles of the authenticated user.
        /// </summary>
        /// <param name="forceLoad">The value indicating whether to force a reload.</param>
        /// <returns>A <see cref="Task{IUserContext}" /> representing the asynchronous operation.</returns>
        public async Task<IUserContext> GetUserContext(bool forceLoad = false)
        {
            var user = await this.GetCurrentUser(forceLoad);

            if (user == null)
            {
                return UserContext.CreateAnonymous();
            }

            return new UserContext
            {
                AccountId = user.Id,
                Username = user.ShortName,
                CurrentRoles = this.currentRoles
            };
        }

        /// <summary>
        /// Sets the currently authenticated user by account identifier and optional roles.
        /// </summary>
        /// <remarks>This is only a placeholder and will be removed once OIDC is configured</remarks>
        /// <param name="userId">The unique identifier of the user account to set as current, or <c>null</c> for unauthenticated.</param>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <returns>A <see cref="Task" /> representing the asynchronous operation.</returns>
        public async Task SetCurrentUser(Guid? userId, CancellationToken cancellationToken = default)
        {
            if (userId.HasValue)
            {
                var contextComingFromJwt = GetJwtContextPlaceholder(userId.Value);

                var result = await this.accountService.ReadAsync(contextComingFromJwt, cancellationToken, [userId.Value]);

                if (!result.IsError && !result.Value.IsEmpty)
                {
                    this.currentUser = result.Value[0];
                    this.currentRoles = contextComingFromJwt.CurrentRoles;

                    return;
                }
            }

            this.currentUser = null;
            this.currentRoles = [RoleKind.Anonymous];
        }

        /// <summary>
        /// Attempts to load the user identity and assigned roles from the current HTTP request context.
        /// </summary>
        /// <returns>A <see cref="Task" /> representing the asynchronous operation.</returns>
        private async Task TryPopulateUserFromHttpContextAsync()
        {
            if (this.currentUser != null || this.httpContextAccessor.HttpContext?.User.Identity?.IsAuthenticated != true)
            {
                return;
            }

            var nameIdentifier = this.httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (!Guid.TryParse(nameIdentifier, out var userId))
            {
                return;
            }

            var roles = this.httpContextAccessor.HttpContext.User
                .FindAll(ClaimTypes.Role)
                .Select(claim => Enum.TryParse<RoleKind>(claim.Value, out var role) ? role : (RoleKind?)null)
                .Where(role => role.HasValue)
                .Select(role => role.Value)
                .ToList();

            var jwtContext = GetJwtContextPlaceholder(userId);
            var result = await this.accountService.ReadAsync(jwtContext, CancellationToken.None, [userId]);

            if (!result.IsError && !result.Value.IsEmpty)
            {
                this.currentUser = result.Value[0];
                this.currentRoles = roles.Count > 0 ? roles : jwtContext.CurrentRoles;
            }
        }

        /// <summary>
        /// Gets a placeholder JWT user context with administrator and account roles.
        /// </summary>
        /// <remarks>This is only a placeholder and will be removed once OIDC is configured.</remarks>
        /// <param name="userId">The optional user account identifier.</param>
        /// <returns>A populated <see cref="IUserContext" /> placeholder.</returns>
        private static IUserContext GetJwtContextPlaceholder(Guid? userId = null)
        {
            return new UserContext
            {
                AccountId = userId ?? SeedData.RegisAccount.Id,
                Username = SeedData.RegisAccount.ShortName,
                CurrentRoles = [RoleKind.InstallationAdministrator, RoleKind.OrganizationAdministrator, RoleKind.Account]
            };
        }
    }
}
