// ------------------------------------------------------------------------------------------------
// <copyright file="AccountPermissionService.cs" company="Starion Group S.A.">
//
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Dal.AutoGenPermissionService
{
    using System.CodeDom.Compiler;

    using FluentResults;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Dal.AutoGeneratedServices;
    using Mycelium.Forge.Dal.PermissionService;

    /// <summary>
    /// Default permission service for <see cref="IAccount"/>.
    /// </summary>
    [GeneratedCode("Mycelium.Forge.Generator", "1.0.0")]
    public partial class AccountPermissionService : PermissionServiceBase<IAccount>, IAccountPermissionService
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountPermissionService"/> class.
        /// </summary>
        public AccountPermissionService()
        {
        }

        /// <summary>
        /// Core implementation hook for verifying create permissions on <paramref name="toCreate"/>.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="toCreate">The entity to create.</param>
        /// <returns>An awaitable <see cref="Task{Result}"/> indicating whether creation is permitted.</returns>
        protected override Task<Result> IsAllowedToCreateImplementation(IUserContext userContext, IAccount toCreate)
        {
            return Task.FromResult(PermissionGuard.GuardPermission(userContext, PermissionKind.ManageAccounts));
        }

        /// <summary>
        /// Core implementation hook for verifying read permissions on <paramref name="thing"/>.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="thing">The entity to read.</param>
        /// <returns>An awaitable <see cref="Task{Result}"/> indicating whether reading is permitted.</returns>
        protected override Task<Result> IsAllowedToReadImplementation(IUserContext userContext, IAccount thing)
        {
            if (userContext.AccountId.HasValue && thing.Id == userContext.AccountId.Value)
            {
                return Task.FromResult(Result.Ok());
            }

            return Task.FromResult(PermissionGuard.GuardAnyPermission(userContext, PermissionKind.ViewAllAccounts, PermissionKind.ManageAccounts));
        }

        /// <summary>
        /// Core implementation hook for verifying update permissions comparing <paramref name="existingThing"/> and <paramref name="updatedThing"/>.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="existingThing">The existing persisted entity state.</param>
        /// <param name="updatedThing">The updated entity state.</param>
        /// <returns>An awaitable <see cref="Task{Result}"/> indicating whether updating is permitted.</returns>
        protected override Task<Result> IsAllowedToUpdateImplementation(IUserContext userContext, IAccount existingThing, IAccount updatedThing)
        {
            if (userContext.AccountId.HasValue && existingThing.Id == userContext.AccountId.Value)
            {
                return Task.FromResult(Result.Ok());
            }

            return Task.FromResult(PermissionGuard.GuardPermission(userContext, PermissionKind.ManageAccounts));
        }

        /// <summary>
        /// Core implementation hook for verifying delete permissions on <paramref name="thing"/>.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="thing">The entity to delete.</param>
        /// <returns>An awaitable <see cref="Task{Result}"/> indicating whether deletion is permitted.</returns>
        protected override Task<Result> IsAllowedToDeleteImplementation(IUserContext userContext, IAccount thing)
        {
            if (userContext.AccountId.HasValue && thing.Id == userContext.AccountId.Value)
            {
                return Task.FromResult(Result.Ok());
            }

            return Task.FromResult(PermissionGuard.GuardPermission(userContext, PermissionKind.ManageAccounts));
        }
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
