// ------------------------------------------------------------------------------------------------
// <copyright file="PackageVersionPermissionService.cs" company="Starion Group S.A.">
//
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Dal.AutoGenPermissionService
{
    using System.CodeDom.Compiler;

    using ErrorOr;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Dal.AutoGeneratedServices;
    using Mycelium.Forge.Dal.PermissionService;

    using Npgsql;

    /// <summary>
    /// Default permission service for <see cref="IPackageVersion"/>.
    /// </summary>
    [GeneratedCode("Mycelium.Forge.Generator", "0.5.0")]
    public partial class PackageVersionPermissionService : PermissionServiceBase<IPackageVersion>, IPackageVersionPermissionService
    {
        /// <summary>
        /// The (injected) <see cref="IPackageService" /> domain service.
        /// </summary>
        private readonly IPackageService packageService;

        /// <summary>
        /// The (injected) <see cref="IPackagePermissionService" /> domain service.
        /// </summary>
        private readonly IPackagePermissionService packagePermissionService;

        /// <summary>
        /// Initializes a new instance of the <see cref="PackageVersionPermissionService"/> class.
        /// </summary>
        public PackageVersionPermissionService()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PackageVersionPermissionService"/> class.
        /// </summary>
        /// <param name="packageService">The (injected) <see cref="IPackageService" /> domain service.</param>
        /// <param name="packagePermissionService">The (injected) <see cref="IPackagePermissionService" /> domain service.</param>
        public PackageVersionPermissionService(IPackageService packageService, IPackagePermissionService packagePermissionService)
        {
            this.packageService = packageService;
            this.packagePermissionService = packagePermissionService;
        }

        /// <summary>
        /// Core implementation hook for verifying create permissions on <paramref name="toCreate"/>.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="toCreate">The entity to create.</param>
        /// <param name="transaction">The database transaction.</param>
        /// <returns>An awaitable <see cref="Task{ErrorOr}"/> indicating whether creation is permitted.</returns>
        protected override async Task<ErrorOr<Success>> IsAllowedToCreateImplementation(IUserContext userContext, IPackageVersion toCreate, NpgsqlTransaction transaction = null)
        {
            if (!userContext.IsAuthenticated || !userContext.AccountId.HasValue)
            {
                return Error.Unauthorized(description: "Unauthenticated user cannot publish a packageversion.");
            }

            var guard = PermissionGuard.GuardPermission(userContext, PermissionKind.PublishPackageVersion);

            if (guard.IsError)
            {
                return guard;
            }

            var parentResult = transaction == null
                ? await this.packageService.ReadAsync(userContext, CancellationToken.None, [toCreate.Owner])
                : await this.packageService.ReadAsync(userContext, transaction, CancellationToken.None, [toCreate.Owner]);

            if (!parentResult.IsError && parentResult.Value.Count > 0)
            {
                var package = parentResult.Value[0];
                var accountId = userContext.AccountId.Value;

                if (package.Owner == accountId || package.PackageOwner.Contains(accountId) || package.PackageMaintainer.Contains(accountId))
                {
                    return Result.Success;
                }

                return Error.Forbidden(description: "Access denied: user is not an owner or maintainer of the package.");
            }

            return Error.Forbidden(description: "Access denied: parent package was not found or is not accessible.");
        }

        /// <summary>
        /// Core implementation hook for verifying read permissions on <paramref name="thing"/>.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="thing">The entity to read.</param>
        /// <param name="transaction">The database transaction.</param>
        /// <returns>An awaitable <see cref="Task{ErrorOr}"/> indicating whether reading is permitted.</returns>
        protected override async Task<ErrorOr<Success>> IsAllowedToReadImplementation(IUserContext userContext, IPackageVersion thing, NpgsqlTransaction transaction = null)
        {
            var parentResult = transaction == null
                ? await this.packageService.ReadAsync(userContext, CancellationToken.None, [thing.Owner])
                : await this.packageService.ReadAsync(userContext, transaction, CancellationToken.None, [thing.Owner]);

            if (!parentResult.IsError && parentResult.Value.Count > 0)
            {
                return Result.Success;
            }

            return Error.Forbidden(description: "Access denied: parent package was not found or is not accessible.");
        }

        /// <summary>
        /// Core implementation hook for verifying update permissions comparing <paramref name="existingThing"/> and <paramref name="updatedThing"/>.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="existingThing">The existing persisted entity state.</param>
        /// <param name="updatedThing">The updated entity state.</param>
        /// <param name="transaction">The database transaction.</param>
        /// <returns>An awaitable <see cref="Task{ErrorOr}"/> indicating whether updating is permitted.</returns>
        protected override async Task<ErrorOr<Success>> IsAllowedToUpdateImplementation(IUserContext userContext, IPackageVersion existingThing, IPackageVersion updatedThing, NpgsqlTransaction transaction = null)
        {
            if (!userContext.IsAuthenticated || !userContext.AccountId.HasValue)
            {
                return Error.Unauthorized(description: "Unauthenticated user cannot update packageversion.");
            }

            if (existingThing.CreatedAt != updatedThing.CreatedAt ||
                    existingThing.DownloadCount != updatedThing.DownloadCount ||
                    existingThing.MetaData != updatedThing.MetaData ||
                    existingThing.ModifiedAt != updatedThing.ModifiedAt ||
                    existingThing.Owner != updatedThing.Owner ||
                    existingThing.PublicationDate != updatedThing.PublicationDate ||
                    existingThing.Version != updatedThing.Version)
            {
                return Error.Forbidden(description: "PackageVersions are immutable; only the listed status may be modified.");
            }

            if (existingThing.Listed != updatedThing.Listed)
            {
                var stateGuard = updatedThing.Listed
                    ? PermissionGuard.GuardPermission(userContext, PermissionKind.RelistPackageVersion)
                    : PermissionGuard.GuardPermission(userContext, PermissionKind.UnlistPackageVersion);

                if (stateGuard.IsError)
                {
                    return stateGuard;
                }
            }

            var parentResult = transaction == null
                ? await this.packageService.ReadAsync(userContext, CancellationToken.None, [existingThing.Owner])
                : await this.packageService.ReadAsync(userContext, transaction, CancellationToken.None, [existingThing.Owner]);

            if (!parentResult.IsError && parentResult.Value.Count > 0)
            {
                var package = parentResult.Value[0];
                var accountId = userContext.AccountId.Value;

                if (package.Owner == accountId || package.PackageOwner.Contains(accountId) || package.PackageMaintainer.Contains(accountId))
                {
                    return Result.Success;
                }

                return Error.Forbidden(description: "Access denied: user is not an owner or maintainer of the package.");
            }

            return Error.Forbidden(description: "Access denied: parent package was not found or is not accessible.");
        }

        /// <summary>
        /// Core implementation hook for verifying delete permissions on <paramref name="thing"/>.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="thing">The entity to delete.</param>
        /// <param name="transaction">The database transaction.</param>
        /// <returns>An awaitable <see cref="Task{ErrorOr}"/> indicating whether deletion is permitted.</returns>
        protected override async Task<ErrorOr<Success>> IsAllowedToDeleteImplementation(IUserContext userContext, IPackageVersion thing, NpgsqlTransaction transaction = null)
        {
            if (!userContext.IsAuthenticated || !userContext.AccountId.HasValue)
            {
                return Error.Unauthorized(description: "Unauthenticated user cannot erase a packageversion.");
            }

            var eraseGuard = PermissionGuard.GuardPermission(userContext, PermissionKind.ErasePackageVersion);

            if (eraseGuard.IsError)
            {
                return eraseGuard;
            }

            var parentResult = transaction == null
                ? await this.packageService.ReadAsync(userContext, CancellationToken.None, [thing.Owner])
                : await this.packageService.ReadAsync(userContext, transaction, CancellationToken.None, [thing.Owner]);

            if (!parentResult.IsError && parentResult.Value.Count > 0)
            {
                var package = parentResult.Value[0];
                var accountId = userContext.AccountId.Value;

                if (package.Owner == accountId || package.PackageOwner.Contains(accountId) || package.PackageMaintainer.Contains(accountId))
                {
                    return Result.Success;
                }

                return Error.Forbidden(description: "Access denied: only package owners can delete package versions.");
            }

            return Error.Forbidden(description: "Access denied: parent package was not found or is not accessible.");
        }
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
