// ------------------------------------------------------------------------------------------------
// <copyright file="AccountServiceDecorator.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Dal.Decorators
{
    using System.Collections.Immutable;

    using ErrorOr;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Dal.AutoGeneratedServices;

    using Npgsql;

    using ZiggyCreatures.Caching.Fusion;

    /// <summary>
    /// Decorator for <see cref="IAccountService" /> providing cache invalidation for scope entries.
    /// </summary>
    public class AccountServiceDecorator : IAccountService
    {
        /// <summary>
        /// The (injected) <see cref="IFusionCache" /> used as a caching layer.
        /// </summary>
        private readonly IFusionCache fusionCache;

        /// <summary>
        /// The decorated <see cref="IAccountService" /> inner service.
        /// </summary>
        private readonly IAccountService innerService;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountServiceDecorator" /> class.
        /// </summary>
        /// <param name="innerService">The decorated <see cref="IAccountService" /> inner service.</param>
        /// <param name="fusionCache">The (injected) <see cref="IFusionCache" /> used as a caching layer.</param>
        public AccountServiceDecorator(IAccountService innerService, IFusionCache fusionCache)
        {
            this.innerService = innerService;
            this.fusionCache = fusionCache;
        }

        /// <summary>
        /// Asynchronously creates (persists) instances of <see cref="IAccount" /> within an existing transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="dtos">The collection of <see cref="IAccount" /> instances to create.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Created}" /> indicating success or failure.</returns>
        public Task<ErrorOr<Created>> CreateAsync(IUserContext userContext, NpgsqlTransaction transaction, IEnumerable<IAccount> dtos, CancellationToken token)
        {
            return this.innerService.CreateAsync(userContext, transaction, dtos, token);
        }

        /// <summary>
        /// Asynchronously creates (persists) instances of <see cref="IAccount" /> managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="dtos">The collection of <see cref="IAccount" /> instances to create.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Created}" /> indicating success or failure.</returns>
        public Task<ErrorOr<Created>> CreateAsync(IUserContext userContext, IEnumerable<IAccount> dtos, CancellationToken token)
        {
            return this.innerService.CreateAsync(userContext, dtos, token);
        }

        /// <summary>
        /// Asynchronously reads instances of <see cref="IAccount" /> within an existing transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <param name="iids">An optional array of unique identifiers to read.</param>
        /// <returns>A <see cref="ErrorOr{TValue}" /> containing an <see cref="ImmutableList{T}" /> of permitted instances.</returns>
        public Task<ErrorOr<ImmutableList<IAccount>>> ReadAsync(IUserContext userContext, NpgsqlTransaction transaction, CancellationToken token, Guid[] iids = null)
        {
            return this.innerService.ReadAsync(userContext, transaction, token, iids);
        }

        /// <summary>
        /// Asynchronously reads instances of <see cref="IAccount" /> managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <param name="iids">An optional array of unique identifiers to read.</param>
        /// <returns>A <see cref="ErrorOr{TValue}" /> containing an <see cref="ImmutableList{T}" /> of permitted instances.</returns>
        public Task<ErrorOr<ImmutableList<IAccount>>> ReadAsync(IUserContext userContext, CancellationToken token, Guid[] iids = null)
        {
            return this.innerService.ReadAsync(userContext, token, iids);
        }

        /// <summary>
        /// Asynchronously updates instances of <see cref="IAccount" /> within an existing transaction and invalidates cached
        /// entries.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="dtos">The collection of <see cref="IAccount" /> instances to update.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Updated}" /> indicating success or failure.</returns>
        public async Task<ErrorOr<Updated>> UpdateAsync(IUserContext userContext, NpgsqlTransaction transaction, IEnumerable<IAccount> dtos, CancellationToken token)
        {
            var dtoList = dtos?.ToList() ?? [];

            var result = await this.innerService.UpdateAsync(userContext, transaction, dtoList, token);

            if (!result.IsError)
            {
                foreach (var dto in dtoList)
                {
                    await this.fusionCache.RemoveByTagAsync($"Scope:{dto.Id}", token: token);
                }
            }

            return result;
        }

        /// <summary>
        /// Asynchronously updates instances of <see cref="IAccount" /> managing its own connection and transaction and invalidates
        /// cached entries.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="dtos">The collection of <see cref="IAccount" /> instances to update.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Updated}" /> indicating success or failure.</returns>
        public async Task<ErrorOr<Updated>> UpdateAsync(IUserContext userContext, IEnumerable<IAccount> dtos, CancellationToken token)
        {
            var dtoList = dtos?.ToList() ?? [];

            var result = await this.innerService.UpdateAsync(userContext, dtoList, token);

            if (!result.IsError)
            {
                foreach (var dto in dtoList)
                {
                    await this.fusionCache.RemoveByTagAsync($"Scope:{dto.Id}", token: token);
                }
            }

            return result;
        }

        /// <summary>
        /// Asynchronously deletes instances of <see cref="IAccount" /> within an existing transaction and invalidates cached
        /// entries.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="iids">The collection of unique identifiers of instances to delete.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Deleted}" /> indicating success or failure.</returns>
        public async Task<ErrorOr<Deleted>> DeleteAsync(IUserContext userContext, NpgsqlTransaction transaction, IEnumerable<Guid> iids, CancellationToken token)
        {
            var idList = iids?.ToList() ?? [];

            var result = await this.innerService.DeleteAsync(userContext, transaction, idList, token);

            if (!result.IsError)
            {
                foreach (var id in idList)
                {
                    await this.fusionCache.RemoveByTagAsync($"Scope:{id}", token: token);
                }
            }

            return result;
        }

        /// <summary>
        /// Asynchronously deletes instances of <see cref="IAccount" /> managing its own connection and transaction and invalidates
        /// cached entries.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="iids">The collection of unique identifiers of instances to delete.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Deleted}" /> indicating success or failure.</returns>
        public async Task<ErrorOr<Deleted>> DeleteAsync(IUserContext userContext, IEnumerable<Guid> iids, CancellationToken token)
        {
            var idList = iids?.ToList() ?? [];

            var result = await this.innerService.DeleteAsync(userContext, idList, token);

            if (!result.IsError)
            {
                foreach (var id in idList)
                {
                    await this.fusionCache.RemoveByTagAsync($"Scope:{id}", token: token);
                }
            }

            return result;
        }
    }
}
