// ------------------------------------------------------------------------------------------------
// <copyright file="OrganizationServiceDecorator.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Dal.Decorators
{
    using System.Collections.Immutable;

    using ErrorOr;

    using Microsoft.Extensions.Logging;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Common.Extensions;
    using Mycelium.Forge.Dal.AutoGeneratedServices;

    using Npgsql;

    using ZiggyCreatures.Caching.Fusion;

    /// <summary>
    /// Decorator for <see cref="IOrganizationService" /> providing pointer key caching and cache invalidation.
    /// </summary>
    public class OrganizationServiceDecorator : IOrganizationService
    {
        /// <summary>
        /// The (injected) <see cref="IFusionCache" /> used as a caching layer.
        /// </summary>
        private readonly IFusionCache fusionCache;

        /// <summary>
        /// The decorated <see cref="IOrganizationService" /> inner service.
        /// </summary>
        private readonly IOrganizationService innerService;

        /// <summary>
        /// The (injected) <see cref="ILogger{T}" /> logger.
        /// </summary>
        private readonly ILogger<OrganizationServiceDecorator> logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationServiceDecorator" /> class.
        /// </summary>
        /// <param name="innerService">The decorated <see cref="IOrganizationService" /> inner service.</param>
        /// <param name="fusionCache">The (injected) <see cref="IFusionCache" /> used as a caching layer.</param>
        /// <param name="logger">The (injected) <see cref="ILogger{T}" /> logger.</param>
        public OrganizationServiceDecorator(IOrganizationService innerService, IFusionCache fusionCache, ILogger<OrganizationServiceDecorator> logger)
        {
            this.innerService = innerService;
            this.fusionCache = fusionCache;
            this.logger = logger;
        }

        /// <summary>
        /// Asynchronously creates (persists) instances of <see cref="IOrganization" /> within an existing transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="dtos">The collection of <see cref="IOrganization" /> instances to create.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Created}" /> indicating success or failure.</returns>
        public Task<ErrorOr<Created>> CreateAsync(IUserContext userContext, NpgsqlTransaction transaction, IEnumerable<IOrganization> dtos, CancellationToken token)
        {
            return this.innerService.CreateAsync(userContext, transaction, dtos, token);
        }

        /// <summary>
        /// Asynchronously creates (persists) instances of <see cref="IOrganization" /> managing its own connection and
        /// transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="dtos">The collection of <see cref="IOrganization" /> instances to create.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Created}" /> indicating success or failure.</returns>
        public Task<ErrorOr<Created>> CreateAsync(IUserContext userContext, IEnumerable<IOrganization> dtos, CancellationToken token)
        {
            return this.innerService.CreateAsync(userContext, dtos, token);
        }

        /// <summary>
        /// Asynchronously reads instances of <see cref="IOrganization" /> within an existing transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <param name="iids">An optional array of unique identifiers to read.</param>
        /// <returns>A <see cref="ErrorOr{TValue}" /> containing an <see cref="ImmutableList{T}" /> of permitted instances.</returns>
        public Task<ErrorOr<ImmutableList<IOrganization>>> ReadAsync(IUserContext userContext, NpgsqlTransaction transaction, CancellationToken token, Guid[] iids = null)
        {
            return this.innerService.ReadAsync(userContext, transaction, token, iids);
        }

        /// <summary>
        /// Asynchronously reads instances of <see cref="IOrganization" /> managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <param name="iids">An optional array of unique identifiers to read.</param>
        /// <returns>A <see cref="ErrorOr{TValue}" /> containing an <see cref="ImmutableList{T}" /> of permitted instances.</returns>
        public Task<ErrorOr<ImmutableList<IOrganization>>> ReadAsync(IUserContext userContext, CancellationToken token, Guid[] iids = null)
        {
            return this.innerService.ReadAsync(userContext, token, iids);
        }

        /// <summary>
        /// Asynchronously updates instances of <see cref="IOrganization" /> within an existing transaction and invalidates cached
        /// entries.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="dtos">The collection of <see cref="IOrganization" /> instances to update.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Updated}" /> indicating success or failure.</returns>
        public async Task<ErrorOr<Updated>> UpdateAsync(IUserContext userContext, NpgsqlTransaction transaction, IEnumerable<IOrganization> dtos, CancellationToken token)
        {
            var dtoList = dtos?.ToList() ?? [];

            var result = await this.innerService.UpdateAsync(userContext, transaction, dtoList, token);

            if (!result.IsError)
            {
                foreach (var dto in dtoList)
                {
                    await this.fusionCache.RemoveByTagAsync($"Scope:{dto.Id}", token: token);
                    await this.fusionCache.RemoveAsync($"Scope:ShortName:{dto.ShortName.ToLowerInvariant()}", token: token);
                }
            }

            return result;
        }

        /// <summary>
        /// Asynchronously updates instances of <see cref="IOrganization" /> managing its own connection and transaction and
        /// invalidates cached entries.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="dtos">The collection of <see cref="IOrganization" /> instances to update.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Updated}" /> indicating success or failure.</returns>
        public async Task<ErrorOr<Updated>> UpdateAsync(IUserContext userContext, IEnumerable<IOrganization> dtos, CancellationToken token)
        {
            var dtoList = dtos?.ToList() ?? [];

            var result = await this.innerService.UpdateAsync(userContext, dtoList, token);

            if (!result.IsError)
            {
                foreach (var dto in dtoList)
                {
                    await this.fusionCache.RemoveByTagAsync($"Scope:{dto.Id}", token: token);
                    await this.fusionCache.RemoveAsync($"Scope:ShortName:{dto.ShortName.ToLowerInvariant()}", token: token);
                }
            }

            return result;
        }

        /// <summary>
        /// Asynchronously deletes instances of <see cref="IOrganization" /> within an existing transaction and invalidates cached
        /// entries.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="iids">The collection of unique identifiers of instances to delete.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Deleted}" /> indicating success or failure.</returns>
        public async Task<ErrorOr<Deleted>> DeleteAsync(IUserContext userContext, NpgsqlTransaction transaction, IEnumerable<Guid> iids, CancellationToken token)
        {
            var idList = iids?.ToList() ?? [];

            var result = await this.innerService.DeleteAsync(userContext, transaction, idList, token);

            if (!result.IsError)
            {
                foreach (var id in idList)
                {
                    await this.fusionCache.RemoveByTagAsync($"Scope:{id}", token: token);
                }
            }

            return result;
        }

        /// <summary>
        /// Asynchronously deletes instances of <see cref="IOrganization" /> managing its own connection and transaction and
        /// invalidates cached entries.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="iids">The collection of unique identifiers of instances to delete.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Deleted}" /> indicating success or failure.</returns>
        public async Task<ErrorOr<Deleted>> DeleteAsync(IUserContext userContext, IEnumerable<Guid> iids, CancellationToken token)
        {
            var idList = iids?.ToList() ?? [];

            var result = await this.innerService.DeleteAsync(userContext, idList, token);

            if (!result.IsError)
            {
                foreach (var id in idList)
                {
                    await this.fusionCache.RemoveByTagAsync($"Scope:{id}", token: token);
                }
            }

            return result;
        }

        /// <summary>
        /// Asynchronously reads a single <see cref="IOrganization" /> instance matching the specified organization short name
        /// managing its own connection and transaction, utilizing secondary index pointer caching.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="shortName">The short name of the organization.</param>
        /// <param name="token">The <see cref="CancellationToken" /> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{TValue}" /> containing the permitted <see cref="IOrganization" /> or an error.</returns>
        public async Task<ErrorOr<IOrganization>> ReadByShortNameAsync(IUserContext userContext, string shortName, CancellationToken token = default)
        {
            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting ReadByShortNameAsync for Organization: shortName {ShortName}", shortName.SanitizeForLog());
            }

            var cacheKey = $"Scope:ShortName:{shortName.ToLowerInvariant()}";

            var cached = await this.fusionCache.TryGetByPointerAsync(cacheKey, this.innerService, userContext, shortName, token);

            if (cached != null)
            {
                return (Organization)cached;
            }

            var result = await this.innerService.ReadByShortNameAsync(userContext, shortName, token);

            if (result is { IsError: false, Value: not null })
            {
                await this.fusionCache.SetPointerAsync(cacheKey, result.Value.Id, [$"Scope:{result.Value.Id}"], token);
            }

            return result;
        }
    }
}
