// ------------------------------------------------------------------------------------------------
// <copyright file="HomeViewModel.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.ViewModels.Home
{
    using Mycelium.Forge.Common;
    using Mycelium.Forge.Dal.AutoGeneratedServices;
    using Mycelium.Forge.Dal.Services;
    using Mycelium.Forge.Extensions;
    using Mycelium.Forge.Services;
    using Mycelium.Forge.ViewModels.Rows;

    /// <summary>
    /// Provides view model state and operations for the Mycelium Forge home landing page.
    /// </summary>
    public class HomeViewModel : IHomeViewModel
    {
        /// <summary>
        /// The list of standard library publisher handles.
        /// </summary>
        private static readonly IReadOnlyList<string> StandardLibraryPublishers = ["@omg", "@esa"];

        /// <summary>
        /// The (injected) <see cref="IPackageService" /> used to retrieve package data.
        /// </summary>
        private readonly IPackageService packageService;

        /// <summary>
        /// The (injected) <see cref="IPackageTypeService" /> used to retrieve package type data.
        /// </summary>
        private readonly IPackageTypeService packageTypeService;

        /// <summary>
        /// The (injected) <see cref="IPackageVersionService" /> used to retrieve package version data.
        /// </summary>
        private readonly IPackageVersionService packageVersionService;

        /// <summary>
        /// The (injected) <see cref="IScopeService" /> used to retrieve scope data.
        /// </summary>
        private readonly IScopeService scopeService;

        /// <summary>
        /// The (injected) <see cref="IUserService" /> used to retrieve the current user context.
        /// </summary>
        private readonly IUserService userService;

        /// <summary>
        /// Initializes a new instance of the <see cref="HomeViewModel" /> class.
        /// </summary>
        /// <param name="packageService">The (injected) <see cref="IPackageService" />.</param>
        /// <param name="scopeService">The (injected) <see cref="IScopeService" />.</param>
        /// <param name="packageVersionService">The (injected) <see cref="IPackageVersionService" />.</param>
        /// <param name="packageTypeService">The (injected) <see cref="IPackageTypeService" />.</param>
        /// <param name="userService">The (injected) <see cref="IUserService" />.</param>
        public HomeViewModel(IPackageService packageService, IScopeService scopeService,
            IPackageVersionService packageVersionService, IPackageTypeService packageTypeService, IUserService userService)
        {
            this.packageService = packageService;
            this.scopeService = scopeService;
            this.packageVersionService = packageVersionService;
            this.packageTypeService = packageTypeService;
            this.userService = userService;
        }

        /// <summary>
        /// Gets or sets the total published package count displayed in the hero section.
        /// </summary>
        public int PackageCount { get; set; }

        /// <summary>
        /// Gets or sets the total package version count displayed in the hero section.
        /// </summary>
        public int VersionCount { get; set; }

        /// <summary>
        /// Gets or sets the total registered publisher count displayed in the hero section.
        /// </summary>
        public int PublisherCount { get; set; }

        /// <summary>
        /// Gets or sets the total package download count displayed in the hero section.
        /// </summary>
        public int DownloadCount { get; set; }

        /// <summary>
        /// Gets or sets the standard library package models.
        /// </summary>
        public List<PackageRowViewModel> StandardLibraries { get; set; } = [];

        /// <summary>
        /// Gets or sets the recently updated package models.
        /// </summary>
        public List<PackageRowViewModel> RecentlyUpdated { get; set; } = [];

        /// <summary>
        /// Gets or sets the most used package models.
        /// </summary>
        public List<PackageRowViewModel> MostUsed { get; set; } = [];

        /// <summary>
        /// Gets or sets the package models from other MBSE tools.
        /// </summary>
        public List<PackageRowViewModel> ModelsFromOtherMbseTools { get; set; } = [];

        /// <summary>
        /// Initializes the view model state and populates the package catalog collections.
        /// </summary>
        /// <returns>A <see cref="Task" />.</returns>
        public async Task InitializeViewModel()
        {
            var userContext = await this.userService.GetUserContext();

            var packagesResult = await this.packageService.ReadAsync(userContext, CancellationToken.None);

            if (packagesResult.IsError)
            {
                return;
            }

            var packages = packagesResult.Value;

            var ownerIds = packages.Select(p => p.Owner).ToList();
            var versionIds = packages.SelectMany(p => p.Version);
            var packageTypeIds = packages.Select(p => p.PackageType);

            var scopesTask = this.scopeService.ReadOrEmpty(userContext, ownerIds);
            var packageVersionsTask = this.packageVersionService.ReadOrEmpty(userContext, versionIds);
            var packageTypesTask = this.packageTypeService.ReadOrEmpty(userContext, packageTypeIds);

            await Task.WhenAll(scopesTask, packageVersionsTask, packageTypesTask);

            var scopes = scopesTask.Result;
            var packageVersions = packageVersionsTask.Result;
            var packageTypes = packageTypesTask.Result;

            var allRows = PackageRowViewModel.GenerateRows(packages, [.. scopes, .. packageVersions, .. packageTypes]);

            this.PackageCount = packages.Count;
            this.VersionCount = packageVersions.Count;
            this.PublisherCount = scopes.Select(s => s.Id).Count();
            this.DownloadCount = packages.Sum(p => p.downloadCount);

            this.StandardLibraries = allRows
                .Where(p => StandardLibraryPublishers.Contains(p.Publisher) && p.Format == PackageFormatConstants.SysMlV2)
                .Take(3)
                .ToList();

            this.RecentlyUpdated = allRows
                .OrderByDescending(p => p.LatestPublicationDate)
                .Take(3)
                .ToList();

            this.MostUsed = allRows
                .OrderByDescending(p => p.DownloadCount)
                .Take(3)
                .ToList();

            this.ModelsFromOtherMbseTools = allRows
                .Where(p => p.Format != PackageFormatConstants.SysMlV2)
                .Take(3)
                .ToList();
        }
    }
}
