// ------------------------------------------------------------------------------------------------
// <copyright file="OrganizationDaoIntegrationTestFixture.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Orm.Tests.Dao
{
    using Microsoft.Extensions.Logging;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Orm.AutoGeneratedDao;
    using Mycelium.Forge.Orm.AutoGeneratedFilters;
    using Mycelium.Forge.Orm.Tests.Helper;

    using Npgsql;

    using NUnit.Framework;

    /// <summary>
    /// Suite of integration tests for the <see cref="OrganizationDao" /> class verifying read filter execution.
    /// </summary>
    [TestFixture]
    [Category("Database")]
    public class OrganizationDaoIntegrationTestFixture : BaseIntegrationTestClassFixture
    {
        private OrganizationDao organizationDao;
        private Guid forgeId;
        private Guid adminAccountId;
        private Guid otherAccountId;
        private Guid org1Id;
        private Guid org2Id;

        /// <summary>
        /// Verifies that <see cref="OrganizationDao.ReadAsync" /> and <see cref="OrganizationDao.ReadIdentifiersAsync" />
        /// apply the SQL read visibility filter correctly.
        /// </summary>
        /// <returns>An awaitable <see cref="Task" />.</returns>
        [Test]
        public async Task VerifyReadAsync()
        {
            var anonymousContext = UserContext.CreateAnonymous();
            var anonymousFilter = OrganizationReadFilter.FromUserContext(anonymousContext);

            var memberUserContext = new UserContext
            {
                AccountId = this.adminAccountId,
                Username = "adminUser",
                CurrentRoles = [RoleKind.Account]
            };

            var memberFilter = OrganizationReadFilter.FromUserContext(memberUserContext);

            await using var transaction = await this.Connection.BeginTransactionAsync();

            var anonResult = await this.organizationDao.ReadAsync(transaction, CancellationToken.None, filter: anonymousFilter);
            var memberResult = await this.organizationDao.ReadAsync(transaction, CancellationToken.None, filter: memberFilter);

            var byIdResult = await this.organizationDao.ReadAsync(transaction, CancellationToken.None, [this.org1Id], filter: anonymousFilter);

            var anonIdentifiers = await this.organizationDao.ReadIdentifiersAsync(transaction, CancellationToken.None, anonymousFilter);

            await transaction.CommitAsync();

            var org1 = anonResult.Value.FirstOrDefault(o => o.Id == this.org1Id);
            var org2 = anonResult.Value.FirstOrDefault(o => o.Id == this.org2Id);

            using (Assert.EnterMultipleScope())
            {
                // Organizations are public — all contexts see all organizations
                Assert.That(anonResult.IsSuccess, Is.True);
                Assert.That(anonResult.Value, Has.Count.EqualTo(2));

                Assert.That(memberResult.IsSuccess, Is.True);
                Assert.That(memberResult.Value, Has.Count.EqualTo(2));

                // Targeted read by ID returns only the requested organization
                Assert.That(byIdResult.IsSuccess, Is.True);
                Assert.That(byIdResult.Value, Has.Count.EqualTo(1));
                Assert.That(byIdResult.Value[0].Id, Is.EqualTo(this.org1Id));

                // Entity shape — verify membership is persisted and retrieved correctly
                Assert.That(org1, Is.Not.Null);
                Assert.That(org1.Name, Is.EqualTo("AdminOrg"));
                Assert.That(org1.Administrator, Does.Contain(this.adminAccountId));
                Assert.That(org1.Member, Does.Contain(this.adminAccountId));

                Assert.That(org2, Is.Not.Null);
                Assert.That(org2.Name, Is.EqualTo("OtherOrg"));
                Assert.That(org2.Administrator, Does.Contain(this.otherAccountId));
                Assert.That(org2.Member, Does.Contain(this.otherAccountId));

                // Identifiers
                Assert.That(anonIdentifiers, Has.Count.EqualTo(2));
                Assert.That(anonIdentifiers, Does.Contain(this.org1Id));
                Assert.That(anonIdentifiers, Does.Contain(this.org2Id));
            }
        }

        /// <summary>
        /// Sets up DAOs and prerequisite records before each test.
        /// </summary>
        /// <returns>An awaitable <see cref="Task" />.</returns>
        protected override async Task PostSetup()
        {
            this.organizationDao = new OrganizationDao(
                this.TestLoggerFactory.CreateLogger<OrganizationDao>(),
                this.Serializer);

            var forgeDao = new ForgeDao(
                this.TestLoggerFactory.CreateLogger<ForgeDao>(),
                this.Serializer);

            var countryDao = new CountryDao(
                this.TestLoggerFactory.CreateLogger<CountryDao>(),
                this.Serializer);

            var addressDao = new AddressDao(
                this.TestLoggerFactory.CreateLogger<AddressDao>(),
                this.Serializer);

            var accountDao = new AccountDao(
                this.TestLoggerFactory.CreateLogger<AccountDao>(),
                this.Serializer);

            this.forgeId = Guid.NewGuid();

            var forge = new Forge
            {
                Id = this.forgeId,
                Name = "TestForge",
                ShortName = "test-forge",
                Description = "Test Forge"
            };

            await this.Insert(transaction => forgeDao.CreateAsync(transaction, CancellationToken.None, forge));

            var countryId = Guid.NewGuid();

            var country = new Country
            {
                Id = countryId,
                Owner = this.forgeId,
                Alpha2Code = "US",
                Alpha3Code = "USA",
                Name = "United States",
                NumericCode = "840"
            };

            await this.Insert(transaction => countryDao.CreateAsync(transaction, CancellationToken.None, country));

            this.adminAccountId = Guid.NewGuid();
            this.otherAccountId = Guid.NewGuid();
            var addressId1 = Guid.NewGuid();
            var addressId2 = Guid.NewGuid();

            var address1 = new Address
            {
                Id = addressId1,
                Owner = this.adminAccountId,
                Country = countryId,
                AddressLine1 = "100 Admin Way",
                Locality = "Metropolis",
                PostalCode = "10001",
                Region = "NY"
            };

            var address2 = new Address
            {
                Id = addressId2,
                Owner = this.otherAccountId,
                Country = countryId,
                AddressLine1 = "200 Other St",
                Locality = "Metropolis",
                PostalCode = "10002",
                Region = "NY"
            };

            var adminAccount = new Account
            {
                Id = this.adminAccountId,
                Owner = this.forgeId,
                PrimaryAddress = addressId1,
                Name = "AdminUser",
                ShortName = "admin-user",
                Email = "admin@example.com",
                BillingEmail = "admin-billing@example.com",
                DefaultPackageVisibility = VisibilityKind.PUBLIC,
                Status = ScopeStatusKind.ACTIVE,
                Origin = "https://example.com"
            };

            var otherAccount = new Account
            {
                Id = this.otherAccountId,
                Owner = this.forgeId,
                PrimaryAddress = addressId2,
                Name = "OtherUser",
                ShortName = "other-user",
                Email = "other@example.com",
                BillingEmail = "other-billing@example.com",
                DefaultPackageVisibility = VisibilityKind.PUBLIC,
                Status = ScopeStatusKind.ACTIVE,
                Origin = "https://example.com"
            };

            await this.Insert(async transaction =>
            {
                await using var setConstraints = new NpgsqlCommand("SET CONSTRAINTS ALL DEFERRED;", transaction.Connection, transaction);
                await setConstraints.ExecuteNonQueryAsync();

                var address1Result = await addressDao.CreateAsync(transaction, CancellationToken.None, address1);

                if (address1Result.IsError)
                {
                    return address1Result;
                }

                var address2Result = await addressDao.CreateAsync(transaction, CancellationToken.None, address2);

                if (address2Result.IsError)
                {
                    return address2Result;
                }

                var adminAccountResult = await accountDao.CreateAsync(transaction, CancellationToken.None, adminAccount);

                if (adminAccountResult.IsError)
                {
                    return adminAccountResult;
                }

                return await accountDao.CreateAsync(transaction, CancellationToken.None, otherAccount);
            });

            this.org1Id = Guid.NewGuid();
            this.org2Id = Guid.NewGuid();

            var org1 = new Organization
            {
                Id = this.org1Id,
                Owner = this.forgeId,
                PrimaryAddress = addressId1,
                Name = "AdminOrg",
                ShortName = "admin-org",
                Email = "adminorg@example.com",
                BillingEmail = "adminorg-billing@example.com",
                DefaultPackageVisibility = VisibilityKind.PUBLIC,
                Status = ScopeStatusKind.ACTIVE,
                Origin = "https://example.com",
                Administrator = [this.adminAccountId],
                Member = [this.adminAccountId]
            };

            var org2 = new Organization
            {
                Id = this.org2Id,
                Owner = this.forgeId,
                PrimaryAddress = addressId2,
                Name = "OtherOrg",
                ShortName = "other-org",
                Email = "otherorg@example.com",
                BillingEmail = "otherorg-billing@example.com",
                DefaultPackageVisibility = VisibilityKind.PRIVATE,
                Status = ScopeStatusKind.ACTIVE,
                Origin = "https://example.com",
                Administrator = [this.otherAccountId],
                Member = [this.otherAccountId]
            };

            await this.Insert(transaction => this.organizationDao.CreateAsync(transaction, CancellationToken.None, org1));
            await this.Insert(transaction => this.organizationDao.CreateAsync(transaction, CancellationToken.None, org2));
        }
    }
}
