// ------------------------------------------------------------------------------------------------
// <copyright file="AddressDao.cs" company="Starion Group S.A.">
//
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Orm.AutoGeneratedDao
{
    using System.CodeDom.Compiler;
    using System.Collections.Immutable;
    using System.Diagnostics;
    using System.Globalization;
    using System.Text;
    using System.Text.Json;

    using FluentResults;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Orm.Filters;
    using Mycelium.Forge.Serializer.Json;

    using Npgsql;

    using NpgsqlTypes;

    /// <summary>
    /// The <see cref="AddressDao"/> class is a Data Access Object which acts
    /// as an ORM layer to the SQL database.
    /// </summary>
    [GeneratedCode("Mycelium.Forge.Generator", "1.0.0")]
    public partial class AddressDao : IAddressDao
    {
        /// <summary>
        /// The (injected) <see cref="ILogger"/> used for logging.
        /// </summary>
        private readonly ILogger<AddressDao> logger;

        /// <summary>
        /// The (injected) <see cref="ISerializer"/> used for JSON serialization.
        /// </summary>
        private readonly ISerializer serializer;

        /// <summary>
        /// Initializes a new instance of the <see cref="AddressDao"/> class.
        /// </summary>
        /// <param name="logger">The (injected) <see cref="ILogger"/> to perform logging.</param>
        /// <param name="serializer">The (injected) <see cref="ISerializer"/> used for JSON serialization.</param>
        public AddressDao(ILogger<AddressDao> logger, ISerializer serializer)
        {
            this.logger = logger;
            this.serializer = serializer;

            this.logger.LogDebug("AddressDao Initialized");
        }

        /// <summary>
        /// Asynchronously creates (persists) an instance of <see cref="IAddress"/> in the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Create operation.</param>
        /// <param name="address">The <see cref="IAddress"/> that is to be persisted.</param>
        /// <returns>Returns a successful <see cref="Result"/> when persisted successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> CreateAsync(NpgsqlTransaction transaction, CancellationToken token, IAddress address)
        {
            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting to Create the Address {Dto}", address);
            }

            try
            {
                await using var command = new NpgsqlCommand();

                // ValueType and Single Reference Properties SQL
                const string valueTypeAndSingleReferenceProperties =
                """
                -- Thing
                INSERT INTO "Forge"."Thing" ("id", "classKind", "data")
                VALUES (@id, @classKind, @data);

                -- Address
                INSERT INTO "Forge"."Address" ("id", "country", "owner")
                VALUES (@id, @country, @owner);

                """;

                var sqlBuilder = new StringBuilder(valueTypeAndSingleReferenceProperties);

                using var memoryStream = new MemoryStream();
                await this.serializer.SerializeAsync(address, memoryStream, new JsonWriterOptions(), token);
                var valueTypesJson = Encoding.UTF8.GetString(memoryStream.ToArray());

                if (this.logger.IsEnabled(LogLevel.Trace))
                {
                    this.logger.LogTrace("Address ValueType JSON: {valueTypesJson}", valueTypesJson);
                }

                // Thing NpgsqlParameter
                command.Parameters.Add(new NpgsqlParameter("@id", NpgsqlDbType.Uuid) { Value = address.Id });
                command.Parameters.Add(new NpgsqlParameter("@classKind", NpgsqlDbType.Text) { Value = "Address" });
                command.Parameters.Add(new NpgsqlParameter("@data", NpgsqlDbType.Jsonb) { Value = valueTypesJson });
                command.Parameters.Add(new NpgsqlParameter("@country", NpgsqlDbType.Uuid) { Value = address.Country });
                command.Parameters.Add(new NpgsqlParameter("@owner", NpgsqlDbType.Uuid) { Value = address.Owner });

                var sql = sqlBuilder.ToString();

                if (this.logger.IsEnabled(LogLevel.Trace))
                {
                    this.logger.LogTrace("Create Address SQL: {sql}", sql);
                }

                command.CommandText = sql;
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("Address - Execute Create SQL");
                await command.ExecuteNonQueryAsync(token);

                if (this.logger.IsEnabled(LogLevel.Debug))
                {
                    this.logger.LogDebug("Address - Create SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);
                }

                if (this.logger.IsEnabled(LogLevel.Information))
                {
                    this.logger.LogInformation("Address created: {Dto}", address);
                }

                return Result.Ok();
            }
            catch (Exception ex)
            {
                if (this.logger.IsEnabled(LogLevel.Error))
                {
                    this.logger.LogError(ex, "The Address could not be created in the database: {Dto}", address);
                }

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Asynchronously reads <see cref="IAddress"/> instances from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Read operation.</param>
        /// <param name="include">An array of unique identifiers of <see cref="IAddress"/> instances that are to be read.</param>
        /// <param name="exclude">An array of unique identifiers of <see cref="IAddress"/> instances that are to be excluded from the read results.</param>
        /// <param name="filter">An optional <see cref="ISqlFilter"/> to apply to the read query.</param>
        /// <returns>An <see cref="ImmutableList{T}"/> of <see cref="IAddress"/>.</returns>
        public async Task<Result<ImmutableList<IAddress>>> ReadAsync(NpgsqlTransaction transaction, CancellationToken token, Guid[] include = null, Guid[] exclude = null, ISqlFilter filter = null)
        {
            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting to Read the Address instances: include {@Include} - exclude {@Exclude}", include, exclude);
            }

            include ??= [];
            exclude ??= [];

            var overlap = include.Intersect(exclude).ToArray();

            if (overlap.Length > 0)
            {
                if (this.logger.IsEnabled(LogLevel.Warning))
                {
                    this.logger.LogWarning("Overlapping Address identifiers found between include and exclude: {@Overlap}", overlap);
                }

                return Result.Fail("Address include and exclude arrays contain overlapping identifiers.");
            }

            if (include.Length == 0)
            {
                include = (await this.ReadIdentifiersAsync(transaction, token, filter)).ToArray();
            }

            include = include.Except(exclude).ToArray();

            if (include.Length == 0)
            {
                return Result.Ok(ImmutableList<IAddress>.Empty);
            }

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Reading the following Address instances from the database {@Identifiers}", include);
            }

            try
            {
                var sqlBuilder = new StringBuilder(
                    """
                    -- READ Thing
                    SELECT
                       "Thing"."id" AS "id",
                       "Thing"."classKind" AS "classKind",
                       ("Thing"."data"->>'addressLine1') AS "addressLine1",
                       ("Thing"."data"->>'addressLine2') AS "addressLine2",
                       ("Thing"."data"->>'createdAt') AS "createdAt",
                       ("Thing"."data"->>'locality') AS "locality",
                       ("Thing"."data"->>'modifiedAt') AS "modifiedAt",
                       ("Thing"."data"->>'postalCode') AS "postalCode",
                       ("Thing"."data"->>'region') AS "region",
                       "Address"."country" AS "country",
                       "Address"."owner" AS "owner"
                    FROM "Forge"."Thing" AS "Thing"

                    -- READ Address
                    INNER JOIN "Forge"."Address" AS "Address"
                            ON "Address"."id" = "Thing"."id"

                    WHERE "Address"."id" = ANY(@include)
                    """);

                if (filter != null && !string.IsNullOrWhiteSpace(filter.ToSqlPredicate()))
                {
                    sqlBuilder.AppendLine();
                    sqlBuilder.Append($"                      AND ({filter.ToSqlPredicate()})");
                }

                sqlBuilder.Append(';');
                var sql = sqlBuilder.ToString();

                if (this.logger.IsEnabled(LogLevel.Trace))
                {
                    this.logger.LogTrace("Read Address SQL: {sql}", sql);
                }

                await using var command = new NpgsqlCommand(sql, transaction.Connection, transaction);

                command.Parameters.Add(new NpgsqlParameter("include", (NpgsqlDbType)((int)NpgsqlDbType.Array | (int)NpgsqlDbType.Uuid)) { Value = include });
                filter?.ApplyParameters(command);

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("Address - Execute Read SQL");
                await using var reader = await command.ExecuteReaderAsync(token);

                if (this.logger.IsEnabled(LogLevel.Debug))
                {
                    this.logger.LogDebug("Address - Read SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);
                }

                sw.Restart();
                this.logger.LogDebug("Address - Execute MapToDto");
                var i = 0;
                List<IAddress> databaseResult = [];

                while (await reader.ReadAsync(token))
                {
                    var dto = MapToDto(reader);
                    databaseResult.Add(dto);
                    i++;
                }

                if (this.logger.IsEnabled(LogLevel.Debug))
                {
                    this.logger.LogDebug("A total of {i} Address instance(s) mapped to DTO in {sw} [ms]", i, sw.ElapsedMilliseconds);
                }

                if (include.Length > 0 && databaseResult.Count == 0)
                {
                    return Result.Fail("Address data not found in the database.");
                }

                if (this.logger.IsEnabled(LogLevel.Information))
                {
                    this.logger.LogInformation("{i} Address instances Read from the database", i);
                }

                return Result.Ok(databaseResult.ToImmutableList());
            }
            catch (Exception ex)
            {
                if (this.logger.IsEnabled(LogLevel.Error))
                {
                    this.logger.LogError(ex, "The Address instance(s) could not be read from the database: include {@Include} - exclude {@Exclude}", include, exclude);
                }

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Reads the unique identifiers of all <see cref="IAddress"/> objects from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Read operation.</param>
        /// <param name="filter">An optional <see cref="ISqlFilter"/> to apply to the read query.</param>
        /// <returns>The list of identifiers of the <see cref="IAddress"/> objects that exist in the database.</returns>
        public async Task<List<Guid>> ReadIdentifiersAsync(NpgsqlTransaction transaction, CancellationToken token, ISqlFilter filter = null)
        {
            this.logger.LogDebug("Reading the Address Identifiers from the database");

            try
            {
                string sql;

                if (filter != null && !string.IsNullOrWhiteSpace(filter.ToSqlPredicate()))
                {
                    sql =
                        $"""
                        SELECT "Address"."id"
                        FROM "Forge"."Address" AS "Address"
                        INNER JOIN "Forge"."Thing" AS "Thing"
                                ON "Thing"."id" = "Address"."id"
                        WHERE ({filter.ToSqlPredicate()});
                        """;
                }
                else
                {
                    sql =
                    """
                    SELECT id FROM "Forge"."Address";
                    """;
                }

                await using var command = new NpgsqlCommand(sql, transaction.Connection, transaction);
                filter?.ApplyParameters(command);

                await using var reader = await command.ExecuteReaderAsync(token);

                List<Guid> result = [];

                while (await reader.ReadAsync(token))
                {
                    result.Add(reader.GetGuid(0));
                }

                return result;
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "Could not read the Address identifiers from the database");
                throw;
            }
        }

        /// <summary>
        /// Asynchronously updates (persists) an instance of <see cref="IAddress"/> in the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Update operation.</param>
        /// <param name="address">The <see cref="IAddress"/> that is to be updated.</param>
        /// <returns>Returns a successful <see cref="Result"/> when updated successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> UpdateAsync(NpgsqlTransaction transaction, CancellationToken token, IAddress address)
        {
            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting to Update the Address {Dto}", address);
            }

            try
            {
                await using var command = new NpgsqlCommand();

                // ValueType and Single Reference Properties SQL
                const string valueTypeAndSingleReferenceProperties =
                """
                -- Thing
                UPDATE "Forge"."Thing" SET "data" = @data WHERE "id" = @id;

                -- Address
                UPDATE "Forge"."Address"
                SET
                    "country" = @country,
                    "owner" = @owner
                WHERE "id" = @id;

                """;

                var sqlBuilder = new StringBuilder(valueTypeAndSingleReferenceProperties);

                using var memoryStream = new MemoryStream();
                await this.serializer.SerializeAsync(address, memoryStream, new JsonWriterOptions(), token);
                var valueTypesJson = Encoding.UTF8.GetString(memoryStream.ToArray());

                if (this.logger.IsEnabled(LogLevel.Trace))
                {
                    this.logger.LogTrace("Address ValueType JSON: {valueTypesJson}", valueTypesJson);
                }

                // Thing NpgsqlParameter
                command.Parameters.Add(new NpgsqlParameter("@id", NpgsqlDbType.Uuid) { Value = address.Id });
                command.Parameters.Add(new NpgsqlParameter("@data", NpgsqlDbType.Jsonb) { Value = valueTypesJson });
                command.Parameters.Add(new NpgsqlParameter("@country", NpgsqlDbType.Uuid) { Value = address.Country });
                command.Parameters.Add(new NpgsqlParameter("@owner", NpgsqlDbType.Uuid) { Value = address.Owner });

                var sql = sqlBuilder.ToString();

                if (this.logger.IsEnabled(LogLevel.Trace))
                {
                    this.logger.LogTrace("Update Address SQL: {sql}", sql);
                }

                command.CommandText = sql;
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("Address - Execute Update SQL");
                await command.ExecuteNonQueryAsync(token);

                if (this.logger.IsEnabled(LogLevel.Debug))
                {
                    this.logger.LogDebug("Address - Update SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);
                }

                if (this.logger.IsEnabled(LogLevel.Information))
                {
                    this.logger.LogInformation("Address updated: {Dto}", address);
                }

                return Result.Ok();
            }
            catch (Exception ex)
            {
                if (this.logger.IsEnabled(LogLevel.Error))
                {
                    this.logger.LogError(ex, "The Address could not be updated in the database: {Dto}", address);
                }

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Asynchronously deletes the provided <see cref="IAddress"/> instances from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="dtos">The collection of <see cref="IAddress"/> that are to be deleted from the database.</param>
        /// <returns>Returns a successful <see cref="Result"/> when deleted successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> DeleteAsync(NpgsqlTransaction transaction, CancellationToken token, IEnumerable<IAddress> dtos)
        {
            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting to Delete the Address instances {dtos}", dtos);
            }

            var ids = dtos.Select(x => x.Id).ToArray();

            try
            {
                await using var command = new NpgsqlCommand();

                const string sql =
                """
                DELETE FROM "Forge"."Address" WHERE id = ANY (@id) RETURNING id;
                """;

                if (this.logger.IsEnabled(LogLevel.Trace))
                {
                    this.logger.LogTrace("Delete Address SQL: {sql}", sql);
                }

                command.CommandText = sql;
                command.Parameters.Add(new NpgsqlParameter("id", (NpgsqlDbType)((int)NpgsqlDbType.Array | (int)NpgsqlDbType.Uuid)) { Value = ids });
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("Address - Execute Delete SQL");

                List<Guid> deletedIds = [];

                await using (var reader = await command.ExecuteReaderAsync(token))
                {
                    while (await reader.ReadAsync(token))
                    {
                        deletedIds.Add(reader.GetGuid(0));
                    }
                }

                if (this.logger.IsEnabled(LogLevel.Debug))
                {
                    this.logger.LogDebug("Address - Delete SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);
                }

                var equal = new HashSet<Guid>(ids).SetEquals(deletedIds);

                if (!equal)
                {
                    if (this.logger.IsEnabled(LogLevel.Warning))
                    {
                        this.logger.LogWarning("A different set of Address instances was deleted than requested {id}:{deleted}", ids, deletedIds);
                    }
                }

                return Result.Ok();
            }
            catch (Exception ex)
            {
                if (this.logger.IsEnabled(LogLevel.Error))
                {
                    this.logger.LogError(ex, "Delete of Address {id} failed with an error", ids);
                }

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Maps the contents of the <see cref="NpgsqlDataReader"/> to an <see cref="IAddress"/>.
        /// </summary>
        /// <param name="reader">An instance of <see cref="NpgsqlDataReader"/> that contains the data that is to be read.</param>
        /// <returns>An instance of <see cref="IAddress"/>.</returns>
        private static IAddress MapToDto(NpgsqlDataReader reader)
        {
            var dto = new Address
            {
                Id = (Guid)reader["id"],
                AddressLine1 = (string)reader["addressLine1"],
                AddressLine2 = reader["addressLine2"] is DBNull ? null : (string)reader["addressLine2"],
                Country = (Guid)reader["country"],
                CreatedAt = DateTime.Parse((string)reader["createdAt"], CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
                Locality = (string)reader["locality"],
                ModifiedAt = DateTime.Parse((string)reader["modifiedAt"], CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
                Owner = (Guid)reader["owner"],
                PostalCode = reader["postalCode"] is DBNull ? null : (string)reader["postalCode"],
                Region = reader["region"] is DBNull ? null : (string)reader["region"]
            };

            return dto;
        }
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
