// ------------------------------------------------------------------------------------------------
// <copyright file="IForgeDao.cs" company="Starion Group S.A.">
//
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Orm.AutoGeneratedDao
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.Immutable;
    using System.Threading;
    using System.Threading.Tasks;

    using FluentResults;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Orm;

    using Npgsql;

    /// <summary>
    /// The <see cref="IForgeDao"/> interface defines the properties and methods
    /// of the <see cref="ForgeDao"/> Data Access Object as an ORM layer to the SQL database.
    /// </summary>
    [GeneratedCode("Mycelium.Forge.Generator", "1.0.0")]
    public interface IForgeDao : IDao
    {
        /// <summary>
        /// Asynchronously creates (persists) an instance of <see cref="IForge"/> in the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Create operation.</param>
        /// <param name="forge">The <see cref="IForge"/> that is to be persisted.</param>
        /// <returns>Returns a successful <see cref="Result"/> when persisted successfully, or a failed <see cref="Result"/> if not successful.</returns>
        Task<Result> CreateAsync(NpgsqlTransaction transaction, CancellationToken token, IForge forge);

        /// <summary>
        /// Asynchronously reads <see cref="IForge"/> instances from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Read operation.</param>
        /// <param name="include">An array of unique identifiers of <see cref="IForge"/> instances that are to be read.</param>
        /// <param name="exclude">An array of unique identifiers of <see cref="IForge"/> instances that are to be excluded from the read results.</param>
        /// <returns>An <see cref="ImmutableList{T}"/> of <see cref="IForge"/>.</returns>
        Task<Result<ImmutableList<IForge>>> ReadAsync(NpgsqlTransaction transaction, CancellationToken token, Guid[] include = null, Guid[] exclude = null);

        /// <summary>
        /// Reads the unique identifiers of all <see cref="IForge"/> objects from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Read operation.</param>
        /// <returns>The list of identifiers of the <see cref="IForge"/> objects that exist in the database.</returns>
        Task<List<Guid>> ReadIdentifiersAsync(NpgsqlTransaction transaction, CancellationToken token);

        /// <summary>
        /// Asynchronously updates (persists) an instance of <see cref="IForge"/> in the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Update operation.</param>
        /// <param name="forge">The <see cref="IForge"/> that is to be updated.</param>
        /// <returns>Returns a successful <see cref="Result"/> when updated successfully, or a failed <see cref="Result"/> if not successful.</returns>
        Task<Result> UpdateAsync(NpgsqlTransaction transaction, CancellationToken token, IForge forge);

        /// <summary>
        /// Asynchronously deletes the provided <see cref="IForge"/> instances from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="dtos">The collection of <see cref="IForge"/> that are to be deleted from the database.</param>
        /// <returns>Returns a successful <see cref="Result"/> when deleted successfully, or a failed <see cref="Result"/> if not successful.</returns>
        Task<Result> DeleteAsync(NpgsqlTransaction transaction, CancellationToken token, IEnumerable<IForge> dtos);
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
