// ------------------------------------------------------------------------------------------------
// <copyright file="OrganizationDao.cs" company="Starion Group S.A.">
//
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Orm.AutoGeneratedDao
{
    using System.CodeDom.Compiler;
    using System.Collections.Immutable;
    using System.Diagnostics;
    using System.Globalization;
    using System.Text;
    using System.Text.Json;

    using FluentResults;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Orm.Filters;
    using Mycelium.Forge.Serializer.Json;

    using Npgsql;

    using NpgsqlTypes;

    /// <summary>
    /// The <see cref="OrganizationDao"/> class is a Data Access Object which acts
    /// as an ORM layer to the SQL database.
    /// </summary>
    [GeneratedCode("Mycelium.Forge.Generator", "1.0.0")]
    public partial class OrganizationDao : IOrganizationDao
    {
        /// <summary>
        /// The (injected) <see cref="ILogger"/> used for logging.
        /// </summary>
        private readonly ILogger<OrganizationDao> logger;

        /// <summary>
        /// The (injected) <see cref="ISerializer"/> used for JSON serialization.
        /// </summary>
        private readonly ISerializer serializer;

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationDao"/> class.
        /// </summary>
        /// <param name="logger">The (injected) <see cref="ILogger"/> to perform logging.</param>
        /// <param name="serializer">The (injected) <see cref="ISerializer"/> used for JSON serialization.</param>
        public OrganizationDao(ILogger<OrganizationDao> logger, ISerializer serializer)
        {
            this.logger = logger;
            this.serializer = serializer;

            this.logger.LogDebug("OrganizationDao Initialized");
        }

        /// <summary>
        /// Asynchronously creates (persists) an instance of <see cref="IOrganization"/> in the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Create operation.</param>
        /// <param name="organization">The <see cref="IOrganization"/> that is to be persisted.</param>
        /// <returns>Returns a successful <see cref="Result"/> when persisted successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> CreateAsync(NpgsqlTransaction transaction, CancellationToken token, IOrganization organization)
        {
            this.logger.LogDebug("Starting to Create the Organization {Dto}", organization);

            try
            {
                await using var command = new NpgsqlCommand();

                // ValueType and Single Reference Properties SQL
                const string valueTypeAndSingleReferenceProperties =
                """
                -- Thing
                INSERT INTO "Forge"."Thing" ("id", "classKind", "data")
                VALUES (@id, @classKind, @data);

                -- Namespace
                INSERT INTO "Forge"."Namespace" ("id")
                VALUES (@id);

                -- Scope
                INSERT INTO "Forge"."Scope" ("id", "primaryAddress")
                VALUES (@id, @primaryAddress);

                -- Organization
                INSERT INTO "Forge"."Organization" ("id", "owner")
                VALUES (@id, @owner);

                """;

                var sqlBuilder = new StringBuilder(valueTypeAndSingleReferenceProperties);

                using var memoryStream = new MemoryStream();
                await this.serializer.SerializeAsync(organization, memoryStream, new JsonWriterOptions(), token);
                var valueTypesJson = Encoding.UTF8.GetString(memoryStream.ToArray());

                this.logger.LogTrace("Organization ValueType JSON: {valueTypesJson}", valueTypesJson);

                // Thing NpgsqlParameter
                command.Parameters.Add(new NpgsqlParameter("@id", NpgsqlDbType.Uuid) { Value = organization.Id });
                command.Parameters.Add(new NpgsqlParameter("@classKind", NpgsqlDbType.Text) { Value = "Organization" });
                command.Parameters.Add(new NpgsqlParameter("@data", NpgsqlDbType.Jsonb) { Value = valueTypesJson });
                command.Parameters.Add(new NpgsqlParameter("@primaryAddress", NpgsqlDbType.Uuid) { Value = organization.PrimaryAddress });
                command.Parameters.Add(new NpgsqlParameter("@owner", NpgsqlDbType.Uuid) { Value = organization.Owner });

                // Organization Multi Reference Properties
                var administratorCounter = 0;

                foreach (var item in organization.Administrator)
                {
                    sqlBuilder.AppendLine("INSERT INTO \"Forge\".\"Organization_administrator__Account\"(\"sourceOrganization\",\"targetAccount\")");
                    sqlBuilder.AppendLine($"VALUES (@id, @administrator{administratorCounter});");
                    sqlBuilder.AppendLine("");

                    command.Parameters.Add(new NpgsqlParameter($"@administrator{administratorCounter}", NpgsqlDbType.Uuid) { Value = item });
                    administratorCounter++;
                }

                var memberCounter = 0;

                foreach (var item in organization.Member)
                {
                    sqlBuilder.AppendLine("INSERT INTO \"Forge\".\"Organization_member__Account\"(\"sourceOrganization\",\"targetAccount\")");
                    sqlBuilder.AppendLine($"VALUES (@id, @member{memberCounter});");
                    sqlBuilder.AppendLine("");

                    command.Parameters.Add(new NpgsqlParameter($"@member{memberCounter}", NpgsqlDbType.Uuid) { Value = item });
                    memberCounter++;
                }

                var sql = sqlBuilder.ToString();

                this.logger.LogTrace("Create Organization SQL: {sql}", sql);

                command.CommandText = sql;
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("Organization - Execute Create SQL");
                await command.ExecuteNonQueryAsync(token);
                this.logger.LogDebug("Organization - Create SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                this.logger.LogInformation("Organization created: {Dto}", organization);

                return Result.Ok();
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "The Organization could not be created in the database: {Dto}", organization);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Asynchronously reads <see cref="IOrganization"/> instances from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Read operation.</param>
        /// <param name="include">An array of unique identifiers of <see cref="IOrganization"/> instances that are to be read.</param>
        /// <param name="exclude">An array of unique identifiers of <see cref="IOrganization"/> instances that are to be excluded from the read results.</param>
        /// <param name="filter">An optional <see cref="ISqlFilter"/> to apply to the read query.</param>
        /// <returns>An <see cref="ImmutableList{T}"/> of <see cref="IOrganization"/>.</returns>
        public async Task<Result<ImmutableList<IOrganization>>> ReadAsync(NpgsqlTransaction transaction, CancellationToken token, Guid[] include = null, Guid[] exclude = null, ISqlFilter filter = null)
        {
            this.logger.LogDebug("Starting to Read the Organization instances: include {@Include} - exclude {@Exclude}", include, exclude);

            include ??= [];
            exclude ??= [];

            var overlap = include.Intersect(exclude).ToArray();

            if (overlap.Length > 0)
            {
                this.logger.LogWarning("Overlapping Organization identifiers found between include and exclude: {@Overlap}", overlap);

                return Result.Fail("Organization include and exclude arrays contain overlapping identifiers.");
            }

            if (include.Length == 0)
            {
                include = (await this.ReadIdentifiersAsync(transaction, token, filter)).ToArray();
            }

            include = include.Except(exclude).ToArray();

            if (include.Length == 0)
            {
                return Result.Ok(ImmutableList<IOrganization>.Empty);
            }

            this.logger.LogDebug("Reading the following Organization instances from the database {@Identifiers}", include);

            try
            {
                var sqlBuilder = new StringBuilder(
                    """
                    -- READ Thing
                    SELECT
                       "Thing"."id" AS "id",
                       "Thing"."classKind" AS "classKind",
                       ("Thing"."data"->>'billingEmail') AS "billingEmail",
                       ("Thing"."data"->>'createdAt') AS "createdAt",
                       ("Thing"."data"->>'defaultPackageVisibility') AS "defaultPackageVisibility",
                       ("Thing"."data"->>'email') AS "email",
                       ("Thing"."data"->>'LogoBlobReference') AS "logoBlobReference",
                       ("Thing"."data"->>'modifiedAt') AS "modifiedAt",
                       ("Thing"."data"->>'name') AS "name",
                       ("Thing"."data"->>'origin') AS "origin",
                       ("Thing"."data"->>'shortName') AS "shortName",
                       ("Thing"."data"->>'status') AS "status",
                       ("Thing"."data"->>'website') AS "website",
                       COALESCE("Scope_Address"."address",'{}'::uuid[]) AS "address",
                       COALESCE("Scope_OwnedPackage"."ownedPackage",'{}'::uuid[]) AS "ownedPackage",
                       "Organization"."owner" AS "owner",
                       "Scope"."primaryAddress" AS "primaryAddress",
                       COALESCE("Scope_ProfileLink"."profileLink",'{}'::uuid[]) AS "profileLink",
                       COALESCE("Organization_administrator__Account"."administrator",'{}'::uuid[]) AS "administrator",
                       COALESCE("Organization_member__Account"."member",'{}'::uuid[]) AS "member"
                    FROM "Forge"."Thing" AS "Thing"

                    -- READ Namespace
                    INNER JOIN "Forge"."Namespace" AS "Namespace"
                            ON "Namespace"."id" = "Thing"."id"

                    -- READ Scope
                    INNER JOIN "Forge"."Scope" AS "Scope"
                            ON "Scope"."id" = "Thing"."id"

                    -- READ Organization
                    INNER JOIN "Forge"."Organization" AS "Organization"
                            ON "Organization"."id" = "Thing"."id"

                    -- READ Scope.address
                    LEFT JOIN LATERAL(
                        SELECT
                            COALESCE(array_agg("Address"."id"::uuid), '{}'::uuid[]) AS "address"
                        FROM "Forge"."Address" AS "Address"
                        WHERE "Address"."owner" = "Scope"."id"
                    ) AS "Scope_Address" ON true

                    -- READ Scope.ownedPackage
                    LEFT JOIN LATERAL(
                        SELECT
                            COALESCE(array_agg("Package"."id"::uuid), '{}'::uuid[]) AS "ownedPackage"
                        FROM "Forge"."Package" AS "Package"
                        WHERE "Package"."owner" = "Scope"."id"
                    ) AS "Scope_OwnedPackage" ON true

                    -- READ Scope.profileLink
                    LEFT JOIN LATERAL(
                        SELECT
                            COALESCE(array_agg("ProfileLink"."id"::uuid), '{}'::uuid[]) AS "profileLink"
                        FROM "Forge"."ProfileLink" AS "ProfileLink"
                        WHERE "ProfileLink"."owner" = "Scope"."id"
                    ) AS "Scope_ProfileLink" ON true

                    -- READ Organization.administrator
                    LEFT JOIN LATERAL(
                        SELECT
                                "Organization_administrator__Account"."sourceOrganization" AS "id",
                           COALESCE(
                               array_agg("Organization_administrator__Account"."targetAccount"::uuid), '{}'::uuid[]
                           ) AS "administrator"
                       FROM "Forge"."Organization_administrator__Account" AS "Organization_administrator__Account"
                       WHERE "Organization_administrator__Account"."sourceOrganization" = "Organization"."id"
                       GROUP BY 1
                    ) AS "Organization_administrator__Account" ON true

                    -- READ Organization.member
                    LEFT JOIN LATERAL(
                        SELECT
                                "Organization_member__Account"."sourceOrganization" AS "id",
                           COALESCE(
                               array_agg("Organization_member__Account"."targetAccount"::uuid), '{}'::uuid[]
                           ) AS "member"
                       FROM "Forge"."Organization_member__Account" AS "Organization_member__Account"
                       WHERE "Organization_member__Account"."sourceOrganization" = "Organization"."id"
                       GROUP BY 1
                    ) AS "Organization_member__Account" ON true

                    WHERE "Organization"."id" = ANY(@include)
                    """);

                if (filter != null && !string.IsNullOrWhiteSpace(filter.ToSqlPredicate()))
                {
                    sqlBuilder.AppendLine();
                    sqlBuilder.Append($"                      AND ({filter.ToSqlPredicate()})");
                }

                sqlBuilder.Append(';');
                var sql = sqlBuilder.ToString();

                this.logger.LogTrace("Read Organization SQL: {sql}", sql);

                await using var command = new NpgsqlCommand(sql, transaction.Connection, transaction);

                command.Parameters.Add(new NpgsqlParameter("include", (NpgsqlDbType)((int)NpgsqlDbType.Array | (int)NpgsqlDbType.Uuid)) { Value = include });
                filter?.ApplyParameters(command);

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("Organization - Execute Read SQL");
                await using var reader = await command.ExecuteReaderAsync(token);
                this.logger.LogDebug("Organization - Read SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                sw.Restart();
                this.logger.LogDebug("Organization - Execute MapToDto");
                var i = 0;
                List<IOrganization> databaseResult = [];

                while (await reader.ReadAsync(token))
                {
                    var dto = MapToDto(reader);
                    databaseResult.Add(dto);
                    i++;
                }

                this.logger.LogDebug("A total of {i} Organization instance(s) mapped to DTO in {sw} [ms]", i, sw.ElapsedMilliseconds);

                if (include.Length > 0 && databaseResult.Count == 0)
                {
                    return Result.Fail("Organization data not found in the database.");
                }

                this.logger.LogInformation("{i} Organization instances Read from the database", i);

                return Result.Ok(databaseResult.ToImmutableList());
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "The Organization instance(s) could not be read from the database: include {@Include} - exclude {@Exclude}", include, exclude);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Reads the unique identifiers of all <see cref="IOrganization"/> objects from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Read operation.</param>
        /// <param name="filter">An optional <see cref="ISqlFilter"/> to apply to the read query.</param>
        /// <returns>The list of identifiers of the <see cref="IOrganization"/> objects that exist in the database.</returns>
        public async Task<List<Guid>> ReadIdentifiersAsync(NpgsqlTransaction transaction, CancellationToken token, ISqlFilter filter = null)
        {
            this.logger.LogDebug("Reading the Organization Identifiers from the database");

            try
            {
                string sql;

                if (filter != null && !string.IsNullOrWhiteSpace(filter.ToSqlPredicate()))
                {
                    sql =
                        $"""
                        SELECT "Organization"."id"
                        FROM "Forge"."Organization" AS "Organization"
                        INNER JOIN "Forge"."Thing" AS "Thing"
                                ON "Thing"."id" = "Organization"."id"
                        WHERE ({filter.ToSqlPredicate()});
                        """;
                }
                else
                {
                    sql =
                        """
                        SELECT id FROM "Forge"."Organization";
                        """;
                }

                await using var command = new NpgsqlCommand(sql, transaction.Connection, transaction);
                filter?.ApplyParameters(command);

                await using var reader = await command.ExecuteReaderAsync(token);

                List<Guid> result = [];

                while (await reader.ReadAsync(token))
                {
                    result.Add(reader.GetGuid(0));
                }

                return result;
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "Could not read the Organization identifiers from the database");
                throw;
            }
        }

        /// <summary>
        /// Asynchronously updates (persists) an instance of <see cref="IOrganization"/> in the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Update operation.</param>
        /// <param name="organization">The <see cref="IOrganization"/> that is to be updated.</param>
        /// <returns>Returns a successful <see cref="Result"/> when updated successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> UpdateAsync(NpgsqlTransaction transaction, CancellationToken token, IOrganization organization)
        {
            this.logger.LogDebug("Starting to Update the Organization {Dto}", organization);

            try
            {
                await using var command = new NpgsqlCommand();

                // ValueType and Single Reference Properties SQL
                const string valueTypeAndSingleReferenceProperties =
                """
                -- Thing
                UPDATE "Forge"."Thing" SET "data" = @data WHERE "id" = @id;

                -- Scope
                UPDATE "Forge"."Scope"
                SET
                    "primaryAddress" = @primaryAddress
                WHERE "id" = @id;

                -- Organization
                UPDATE "Forge"."Organization"
                SET
                    "owner" = @owner
                WHERE "id" = @id;

                """;

                var sqlBuilder = new StringBuilder(valueTypeAndSingleReferenceProperties);

                using var memoryStream = new MemoryStream();
                await this.serializer.SerializeAsync(organization, memoryStream, new JsonWriterOptions(), token);
                var valueTypesJson = Encoding.UTF8.GetString(memoryStream.ToArray());

                this.logger.LogTrace("Organization ValueType JSON: {valueTypesJson}", valueTypesJson);

                // Thing NpgsqlParameter
                command.Parameters.Add(new NpgsqlParameter("@id", NpgsqlDbType.Uuid) { Value = organization.Id });
                command.Parameters.Add(new NpgsqlParameter("@data", NpgsqlDbType.Jsonb) { Value = valueTypesJson });
                command.Parameters.Add(new NpgsqlParameter("@primaryAddress", NpgsqlDbType.Uuid) { Value = organization.PrimaryAddress });
                command.Parameters.Add(new NpgsqlParameter("@owner", NpgsqlDbType.Uuid) { Value = organization.Owner });

                // Organization Multi Reference Properties

                sqlBuilder.AppendLine(
                """
                WITH "wanted_Organization_administrator__Account" AS (
                    SELECT @id AS "sourceOrganization", unnest(@administrator::uuid[]) AS "targetAccount"
                )
                MERGE INTO "Forge"."Organization_administrator__Account" "current_Organization_administrator__Account"
                    USING "wanted_Organization_administrator__Account"
                    ON "current_Organization_administrator__Account"."sourceOrganization" = "wanted_Organization_administrator__Account"."sourceOrganization" AND "current_Organization_administrator__Account"."targetAccount" = "wanted_Organization_administrator__Account"."targetAccount"
                WHEN NOT MATCHED THEN
                    INSERT ("sourceOrganization", "targetAccount")
                        VALUES ("wanted_Organization_administrator__Account"."sourceOrganization", "wanted_Organization_administrator__Account"."targetAccount");

                DELETE FROM "Forge"."Organization_administrator__Account"
                    WHERE  "sourceOrganization" = @id
                      AND  "targetAccount" NOT IN (SELECT unnest(@administrator::uuid[]));
                """);

                command.Parameters.Add(new NpgsqlParameter("@administrator", (NpgsqlDbType)((int)NpgsqlDbType.Array | (int)NpgsqlDbType.Uuid)) { Value = (organization.Administrator ?? []).ToArray() });


                sqlBuilder.AppendLine(
                """
                WITH "wanted_Organization_member__Account" AS (
                    SELECT @id AS "sourceOrganization", unnest(@member::uuid[]) AS "targetAccount"
                )
                MERGE INTO "Forge"."Organization_member__Account" "current_Organization_member__Account"
                    USING "wanted_Organization_member__Account"
                    ON "current_Organization_member__Account"."sourceOrganization" = "wanted_Organization_member__Account"."sourceOrganization" AND "current_Organization_member__Account"."targetAccount" = "wanted_Organization_member__Account"."targetAccount"
                WHEN NOT MATCHED THEN
                    INSERT ("sourceOrganization", "targetAccount")
                        VALUES ("wanted_Organization_member__Account"."sourceOrganization", "wanted_Organization_member__Account"."targetAccount");

                DELETE FROM "Forge"."Organization_member__Account"
                    WHERE  "sourceOrganization" = @id
                      AND  "targetAccount" NOT IN (SELECT unnest(@member::uuid[]));
                """);

                command.Parameters.Add(new NpgsqlParameter("@member", (NpgsqlDbType)((int)NpgsqlDbType.Array | (int)NpgsqlDbType.Uuid)) { Value = (organization.Member ?? []).ToArray() });

                var sql = sqlBuilder.ToString();

                this.logger.LogTrace("Update Organization SQL: {sql}", sql);

                command.CommandText = sql;
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("Organization - Execute Update SQL");
                await command.ExecuteNonQueryAsync(token);
                this.logger.LogDebug("Organization - Update SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                this.logger.LogInformation("Organization updated: {Dto}", organization);

                return Result.Ok();
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "The Organization could not be updated in the database: {Dto}", organization);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Asynchronously deletes the provided <see cref="IOrganization"/> instances from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="dtos">The collection of <see cref="IOrganization"/> that are to be deleted from the database.</param>
        /// <returns>Returns a successful <see cref="Result"/> when deleted successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> DeleteAsync(NpgsqlTransaction transaction, CancellationToken token, IEnumerable<IOrganization> dtos)
        {
            this.logger.LogDebug("Starting to Delete the Organization instances {dtos}", dtos);

            var ids = dtos.Select(x => x.Id).ToArray();

            try
            {
                await using var command = new NpgsqlCommand();

                const string sql =
                """
                DELETE FROM "Forge"."Organization" WHERE id = ANY (@id) RETURNING id;
                """;

                this.logger.LogTrace("Delete Organization SQL: {sql}", sql);

                command.CommandText = sql;
                command.Parameters.Add(new NpgsqlParameter("id", (NpgsqlDbType)((int)NpgsqlDbType.Array | (int)NpgsqlDbType.Uuid)) { Value = ids });
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("Organization - Execute Delete SQL");

                List<Guid> deletedIds = [];

                await using (var reader = await command.ExecuteReaderAsync(token))
                {
                    while (await reader.ReadAsync(token))
                    {
                        deletedIds.Add(reader.GetGuid(0));
                    }
                }

                this.logger.LogDebug("Organization - Delete SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                var equal = new HashSet<Guid>(ids).SetEquals(deletedIds);

                if (!equal)
                {
                    this.logger.LogWarning("A different set of Organization instances was deleted than requested {id}:{deleted}", ids, deletedIds);
                }

                return Result.Ok();
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "Delete of Organization {id} failed with an error", ids);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Maps the contents of the <see cref="NpgsqlDataReader"/> to an <see cref="IOrganization"/>.
        /// </summary>
        /// <param name="reader">An instance of <see cref="NpgsqlDataReader"/> that contains the data that is to be read.</param>
        /// <returns>An instance of <see cref="IOrganization"/>.</returns>
        private static IOrganization MapToDto(NpgsqlDataReader reader)
        {
            var dto = new Organization
            {
                Id = (Guid)reader["id"],
                Address = [.. (Guid[])reader["address"]],
                Administrator = [.. (Guid[])reader["administrator"]],
                BillingEmail = reader["billingEmail"] is DBNull ? null : (string)reader["billingEmail"],
                CreatedAt = DateTime.Parse((string)reader["createdAt"], CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
                DefaultPackageVisibility = VisibilityKindProvider.Parse((string)reader["defaultPackageVisibility"]),
                Email = (string)reader["email"],
                LogoBlobReference = reader["logoBlobReference"] is DBNull ? null : (string)reader["logoBlobReference"],
                Member = [.. (Guid[])reader["member"]],
                ModifiedAt = DateTime.Parse((string)reader["modifiedAt"], CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
                Name = (string)reader["name"],
                Origin = (string)reader["origin"],
                OwnedPackage = [.. (Guid[])reader["ownedPackage"]],
                Owner = (Guid)reader["owner"],
                PrimaryAddress = (Guid)reader["primaryAddress"],
                ProfileLink = [.. (Guid[])reader["profileLink"]],
                ShortName = (string)reader["shortName"],
                Status = ScopeStatusKindProvider.Parse((string)reader["status"]),
                Website = reader["website"] is DBNull ? null : (string)reader["website"]
            };

            return dto;
        }
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
