// ------------------------------------------------------------------------------------------------
// <copyright file="PackageVersionDao.cs" company="Starion Group S.A.">
//
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Orm.AutoGeneratedDao
{
    using System.CodeDom.Compiler;
    using System.Collections.Immutable;
    using System.Diagnostics;
    using System.Globalization;
    using System.Text;
    using System.Text.Json;

    using FluentResults;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Orm.Filters;
    using Mycelium.Forge.Serializer.Json;

    using Npgsql;

    using NpgsqlTypes;

    /// <summary>
    /// The <see cref="PackageVersionDao"/> class is a Data Access Object which acts
    /// as an ORM layer to the SQL database.
    /// </summary>
    [GeneratedCode("Mycelium.Forge.Generator", "1.0.0")]
    public partial class PackageVersionDao : IPackageVersionDao
    {
        /// <summary>
        /// The (injected) <see cref="ILogger"/> used for logging.
        /// </summary>
        private readonly ILogger<PackageVersionDao> logger;

        /// <summary>
        /// The (injected) <see cref="ISerializer"/> used for JSON serialization.
        /// </summary>
        private readonly ISerializer serializer;

        /// <summary>
        /// Initializes a new instance of the <see cref="PackageVersionDao"/> class.
        /// </summary>
        /// <param name="logger">The (injected) <see cref="ILogger"/> to perform logging.</param>
        /// <param name="serializer">The (injected) <see cref="ISerializer"/> used for JSON serialization.</param>
        public PackageVersionDao(ILogger<PackageVersionDao> logger, ISerializer serializer)
        {
            this.logger = logger;
            this.serializer = serializer;

            this.logger.LogDebug("PackageVersionDao Initialized");
        }

        /// <summary>
        /// Asynchronously creates (persists) an instance of <see cref="IPackageVersion"/> in the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Create operation.</param>
        /// <param name="packageVersion">The <see cref="IPackageVersion"/> that is to be persisted.</param>
        /// <returns>Returns a successful <see cref="Result"/> when persisted successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> CreateAsync(NpgsqlTransaction transaction, CancellationToken token, IPackageVersion packageVersion)
        {
            this.logger.LogDebug("Starting to Create the PackageVersion {Dto}", packageVersion);

            try
            {
                await using var command = new NpgsqlCommand();

                // ValueType and Single Reference Properties SQL
                const string valueTypeAndSingleReferenceProperties =
                """
                -- Thing
                INSERT INTO "Forge"."Thing" ("id", "classKind", "data")
                VALUES (@id, @classKind, @data);

                -- PackageVersion
                INSERT INTO "Forge"."PackageVersion" ("id", "owner")
                VALUES (@id, @owner);

                """;

                var sqlBuilder = new StringBuilder(valueTypeAndSingleReferenceProperties);

                using var memoryStream = new MemoryStream();
                await this.serializer.SerializeAsync(packageVersion, memoryStream, new JsonWriterOptions(), token);
                var valueTypesJson = Encoding.UTF8.GetString(memoryStream.ToArray());

                this.logger.LogTrace("PackageVersion ValueType JSON: {valueTypesJson}", valueTypesJson);

                // Thing NpgsqlParameter
                command.Parameters.Add(new NpgsqlParameter("@id", NpgsqlDbType.Uuid) { Value = packageVersion.Id });
                command.Parameters.Add(new NpgsqlParameter("@classKind", NpgsqlDbType.Text) { Value = "PackageVersion" });
                command.Parameters.Add(new NpgsqlParameter("@data", NpgsqlDbType.Jsonb) { Value = valueTypesJson });
                command.Parameters.Add(new NpgsqlParameter("@owner", NpgsqlDbType.Uuid) { Value = packageVersion.Owner });

                var sql = sqlBuilder.ToString();

                this.logger.LogTrace("Create PackageVersion SQL: {sql}", sql);

                command.CommandText = sql;
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("PackageVersion - Execute Create SQL");
                await command.ExecuteNonQueryAsync(token);
                this.logger.LogDebug("PackageVersion - Create SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                this.logger.LogInformation("PackageVersion created: {Dto}", packageVersion);

                return Result.Ok();
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "The PackageVersion could not be created in the database: {Dto}", packageVersion);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Asynchronously reads <see cref="IPackageVersion"/> instances from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Read operation.</param>
        /// <param name="include">An array of unique identifiers of <see cref="IPackageVersion"/> instances that are to be read.</param>
        /// <param name="exclude">An array of unique identifiers of <see cref="IPackageVersion"/> instances that are to be excluded from the read results.</param>
        /// <param name="filter">An optional <see cref="ISqlFilter"/> to apply to the read query.</param>
        /// <returns>An <see cref="ImmutableList{T}"/> of <see cref="IPackageVersion"/>.</returns>
        public async Task<Result<ImmutableList<IPackageVersion>>> ReadAsync(NpgsqlTransaction transaction, CancellationToken token, Guid[] include = null, Guid[] exclude = null, ISqlFilter filter = null)
        {
            this.logger.LogDebug("Starting to Read the PackageVersion instances: include {@Include} - exclude {@Exclude}", include, exclude);

            include ??= [];
            exclude ??= [];

            var overlap = include.Intersect(exclude).ToArray();

            if (overlap.Length > 0)
            {
                this.logger.LogWarning("Overlapping PackageVersion identifiers found between include and exclude: {@Overlap}", overlap);

                return Result.Fail("PackageVersion include and exclude arrays contain overlapping identifiers.");
            }

            if (include.Length == 0)
            {
                include = (await this.ReadIdentifiersAsync(transaction, token, filter)).ToArray();
            }

            include = include.Except(exclude).ToArray();

            if (include.Length == 0)
            {
                return Result.Ok(ImmutableList<IPackageVersion>.Empty);
            }

            this.logger.LogDebug("Reading the following PackageVersion instances from the database {@Identifiers}", include);

            try
            {
                var sqlBuilder = new StringBuilder(
                    """
                    -- READ Thing
                    SELECT
                       "Thing"."id" AS "id",
                       "Thing"."classKind" AS "classKind",
                       ("Thing"."data"->>'createdAt') AS "createdAt",
                       ("Thing"."data"->>'downloadCount')::integer AS "downloadCount",
                       ("Thing"."data"->>'listed')::boolean AS "listed",
                       ("Thing"."data"->>'modifiedAt') AS "modifiedAt",
                       ("Thing"."data"->>'publicationDate') AS "publicationDate",
                       ("Thing"."data"->>'version') AS "version",
                       "PackageVersion_MetaData"."metaData"::uuid AS "metaData",
                       "PackageVersion"."owner" AS "owner"
                    FROM "Forge"."Thing" AS "Thing"

                    -- READ PackageVersion
                    INNER JOIN "Forge"."PackageVersion" AS "PackageVersion"
                            ON "PackageVersion"."id" = "Thing"."id"

                    -- READ PackageVersion.metaData
                    LEFT JOIN LATERAL(
                        SELECT
                            "PackageMetaData"."id"::uuid AS "metaData"
                        FROM "Forge"."PackageMetaData" AS "PackageMetaData"
                        WHERE "PackageMetaData"."owner" = "PackageVersion"."id"
                    ) AS "PackageVersion_MetaData" ON true

                    WHERE "PackageVersion"."id" = ANY(@include)
                    """);

                if (filter != null && !string.IsNullOrWhiteSpace(filter.ToSqlPredicate()))
                {
                    sqlBuilder.AppendLine();
                    sqlBuilder.Append($"                      AND ({filter.ToSqlPredicate()})");
                }

                sqlBuilder.Append(';');
                var sql = sqlBuilder.ToString();

                this.logger.LogTrace("Read PackageVersion SQL: {sql}", sql);

                await using var command = new NpgsqlCommand(sql, transaction.Connection, transaction);

                command.Parameters.Add(new NpgsqlParameter("include", (NpgsqlDbType)((int)NpgsqlDbType.Array | (int)NpgsqlDbType.Uuid)) { Value = include });
                filter?.ApplyParameters(command);

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("PackageVersion - Execute Read SQL");
                await using var reader = await command.ExecuteReaderAsync(token);
                this.logger.LogDebug("PackageVersion - Read SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                sw.Restart();
                this.logger.LogDebug("PackageVersion - Execute MapToDto");
                var i = 0;
                List<IPackageVersion> databaseResult = [];

                while (await reader.ReadAsync(token))
                {
                    var dto = MapToDto(reader);
                    databaseResult.Add(dto);
                    i++;
                }

                this.logger.LogDebug("A total of {i} PackageVersion instance(s) mapped to DTO in {sw} [ms]", i, sw.ElapsedMilliseconds);

                if (include.Length > 0 && databaseResult.Count == 0)
                {
                    return Result.Fail("PackageVersion data not found in the database.");
                }

                this.logger.LogInformation("{i} PackageVersion instances Read from the database", i);

                return Result.Ok(databaseResult.ToImmutableList());
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "The PackageVersion instance(s) could not be read from the database: include {@Include} - exclude {@Exclude}", include, exclude);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Reads the unique identifiers of all <see cref="IPackageVersion"/> objects from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Read operation.</param>
        /// <param name="filter">An optional <see cref="ISqlFilter"/> to apply to the read query.</param>
        /// <returns>The list of identifiers of the <see cref="IPackageVersion"/> objects that exist in the database.</returns>
        public async Task<List<Guid>> ReadIdentifiersAsync(NpgsqlTransaction transaction, CancellationToken token, ISqlFilter filter = null)
        {
            this.logger.LogDebug("Reading the PackageVersion Identifiers from the database");

            try
            {
                string sql;

                if (filter != null && !string.IsNullOrWhiteSpace(filter.ToSqlPredicate()))
                {
                    sql =
                        $"""
                        SELECT "PackageVersion"."id"
                        FROM "Forge"."PackageVersion" AS "PackageVersion"
                        INNER JOIN "Forge"."Thing" AS "Thing"
                                ON "Thing"."id" = "PackageVersion"."id"
                        WHERE ({filter.ToSqlPredicate()});
                        """;
                }
                else
                {
                    sql =
                        """
                        SELECT id FROM "Forge"."PackageVersion";
                        """;
                }

                await using var command = new NpgsqlCommand(sql, transaction.Connection, transaction);
                filter?.ApplyParameters(command);

                await using var reader = await command.ExecuteReaderAsync(token);

                List<Guid> result = [];

                while (await reader.ReadAsync(token))
                {
                    result.Add(reader.GetGuid(0));
                }

                return result;
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "Could not read the PackageVersion identifiers from the database");
                throw;
            }
        }

        /// <summary>
        /// Asynchronously updates (persists) an instance of <see cref="IPackageVersion"/> in the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Update operation.</param>
        /// <param name="packageVersion">The <see cref="IPackageVersion"/> that is to be updated.</param>
        /// <returns>Returns a successful <see cref="Result"/> when updated successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> UpdateAsync(NpgsqlTransaction transaction, CancellationToken token, IPackageVersion packageVersion)
        {
            this.logger.LogDebug("Starting to Update the PackageVersion {Dto}", packageVersion);

            try
            {
                await using var command = new NpgsqlCommand();

                // ValueType and Single Reference Properties SQL
                const string valueTypeAndSingleReferenceProperties =
                """
                -- Thing
                UPDATE "Forge"."Thing" SET "data" = @data WHERE "id" = @id;

                -- PackageVersion
                UPDATE "Forge"."PackageVersion"
                SET
                    "owner" = @owner
                WHERE "id" = @id;

                """;

                var sqlBuilder = new StringBuilder(valueTypeAndSingleReferenceProperties);

                using var memoryStream = new MemoryStream();
                await this.serializer.SerializeAsync(packageVersion, memoryStream, new JsonWriterOptions(), token);
                var valueTypesJson = Encoding.UTF8.GetString(memoryStream.ToArray());

                this.logger.LogTrace("PackageVersion ValueType JSON: {valueTypesJson}", valueTypesJson);

                // Thing NpgsqlParameter
                command.Parameters.Add(new NpgsqlParameter("@id", NpgsqlDbType.Uuid) { Value = packageVersion.Id });
                command.Parameters.Add(new NpgsqlParameter("@data", NpgsqlDbType.Jsonb) { Value = valueTypesJson });
                command.Parameters.Add(new NpgsqlParameter("@owner", NpgsqlDbType.Uuid) { Value = packageVersion.Owner });

                var sql = sqlBuilder.ToString();

                this.logger.LogTrace("Update PackageVersion SQL: {sql}", sql);

                command.CommandText = sql;
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("PackageVersion - Execute Update SQL");
                await command.ExecuteNonQueryAsync(token);
                this.logger.LogDebug("PackageVersion - Update SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                this.logger.LogInformation("PackageVersion updated: {Dto}", packageVersion);

                return Result.Ok();
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "The PackageVersion could not be updated in the database: {Dto}", packageVersion);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Asynchronously deletes the provided <see cref="IPackageVersion"/> instances from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="dtos">The collection of <see cref="IPackageVersion"/> that are to be deleted from the database.</param>
        /// <returns>Returns a successful <see cref="Result"/> when deleted successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> DeleteAsync(NpgsqlTransaction transaction, CancellationToken token, IEnumerable<IPackageVersion> dtos)
        {
            this.logger.LogDebug("Starting to Delete the PackageVersion instances {dtos}", dtos);

            var ids = dtos.Select(x => x.Id).ToArray();

            try
            {
                await using var command = new NpgsqlCommand();

                const string sql =
                """
                DELETE FROM "Forge"."PackageVersion" WHERE id = ANY (@id) RETURNING id;
                """;

                this.logger.LogTrace("Delete PackageVersion SQL: {sql}", sql);

                command.CommandText = sql;
                command.Parameters.Add(new NpgsqlParameter("id", (NpgsqlDbType)((int)NpgsqlDbType.Array | (int)NpgsqlDbType.Uuid)) { Value = ids });
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("PackageVersion - Execute Delete SQL");

                List<Guid> deletedIds = [];

                await using (var reader = await command.ExecuteReaderAsync(token))
                {
                    while (await reader.ReadAsync(token))
                    {
                        deletedIds.Add(reader.GetGuid(0));
                    }
                }

                this.logger.LogDebug("PackageVersion - Delete SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                var equal = new HashSet<Guid>(ids).SetEquals(deletedIds);

                if (!equal)
                {
                    this.logger.LogWarning("A different set of PackageVersion instances was deleted than requested {id}:{deleted}", ids, deletedIds);
                }

                return Result.Ok();
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "Delete of PackageVersion {id} failed with an error", ids);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Maps the contents of the <see cref="NpgsqlDataReader"/> to an <see cref="IPackageVersion"/>.
        /// </summary>
        /// <param name="reader">An instance of <see cref="NpgsqlDataReader"/> that contains the data that is to be read.</param>
        /// <returns>An instance of <see cref="IPackageVersion"/>.</returns>
        private static IPackageVersion MapToDto(NpgsqlDataReader reader)
        {
            var dto = new PackageVersion
            {
                Id = (Guid)reader["id"],
                CreatedAt = DateTime.Parse((string)reader["createdAt"], CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
                DownloadCount = (int)reader["downloadCount"],
                Listed = (bool)reader["listed"],
                MetaData = (Guid)reader["metaData"],
                ModifiedAt = DateTime.Parse((string)reader["modifiedAt"], CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
                Owner = (Guid)reader["owner"],
                PublicationDate = DateTime.Parse((string)reader["publicationDate"], CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
                Version = (string)reader["version"]
            };

            return dto;
        }
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
