// ------------------------------------------------------------------------------------------------
// <copyright file="PackageInvitationDao.cs" company="Starion Group S.A.">
//
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Orm.AutoGeneratedDao
{
    using System.CodeDom.Compiler;
    using System.Collections.Immutable;
    using System.Diagnostics;
    using System.Globalization;
    using System.Text;
    using System.Text.Json;

    using FluentResults;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Common.AutoGenDtoComparer;
    using Mycelium.Forge.Orm.Helpers;
    using Mycelium.Forge.Serializer.Json;

    using Npgsql;

    using NpgsqlTypes;

    /// <summary>
    /// The <see cref="PackageInvitationDao"/> class is a Data Access Object which acts
    /// as an ORM layer to the SQL database.
    /// </summary>
    [GeneratedCode("Mycelium.Forge.Generator", "1.0.0")]
    public partial class PackageInvitationDao : IPackageInvitationDao
    {
        /// <summary>
        /// The (injected) <see cref="ILogger"/> used for logging.
        /// </summary>
        private readonly ILogger<PackageInvitationDao> logger;

        /// <summary>
        /// The (injected) <see cref="ISerializer"/> used for JSON serialization.
        /// </summary>
        private readonly ISerializer serializer;

        /// <summary>
        /// The (injected) <see cref="PackageInvitationComparer"/> used to compare older and newer object versions.
        /// </summary>
        private readonly PackageInvitationComparer comparer;

        /// <summary>
        /// Initializes a new instance of the <see cref="PackageInvitationDao"/> class.
        /// </summary>
        /// <param name="logger">The (injected) <see cref="ILogger"/> to perform logging.</param>
        /// <param name="serializer">The (injected) <see cref="ISerializer"/> used for JSON serialization.</param>
        /// <param name="comparer">The (injected) <see cref="PackageInvitationComparer"/> used to compare older and newer object versions.</param>
        public PackageInvitationDao(ILogger<PackageInvitationDao> logger, ISerializer serializer, PackageInvitationComparer comparer)
        {
            this.logger = logger;
            this.serializer = serializer;
            this.comparer = comparer;

            this.logger.LogDebug("PackageInvitationDao Initialized");
        }

        /// <summary>
        /// Asynchronously creates (persists) an instance of <see cref="IPackageInvitation"/> in the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Create operation.</param>
        /// <param name="packageInvitation">The <see cref="IPackageInvitation"/> that is to be persisted.</param>
        /// <returns>Returns a successful <see cref="Result"/> when persisted successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> CreateAsync(NpgsqlTransaction transaction, CancellationToken token, IPackageInvitation packageInvitation)
        {
            this.logger.LogDebug("Starting to Create the PackageInvitation {Dto}", packageInvitation);

            try
            {
                await using var command = new NpgsqlCommand();

                // ValueType and Single Reference Properties SQL
                const string valueTypeAndSingleReferenceProperties =
                """
                -- Thing
                INSERT INTO "Forge"."Thing" ("id", "classKind", "data")
                VALUES (@id, @classKind, @data);

                -- Invitation
                INSERT INTO "Forge"."Invitation" ("id")
                VALUES (@id);

                -- PackageInvitation
                INSERT INTO "Forge"."PackageInvitation" ("id", "owner", "package", "target")
                VALUES (@id, @owner, @package, @target);

                """;

                var sqlBuilder = new StringBuilder(valueTypeAndSingleReferenceProperties);

                using var memoryStream = new MemoryStream();
                await this.serializer.SerializeAsync(packageInvitation, memoryStream, new JsonWriterOptions(), token);
                var valueTypesJson = Encoding.UTF8.GetString(memoryStream.ToArray());

                this.logger.LogTrace("PackageInvitation ValueType JSON: {valueTypesJson}", valueTypesJson);

                // Thing NpgsqlParameter
                command.Parameters.Add(new NpgsqlParameter("@id", NpgsqlDbType.Uuid) { Value = packageInvitation.Id });
                command.Parameters.Add(new NpgsqlParameter("@classKind", NpgsqlDbType.Text) { Value = "PackageInvitation" });
                command.Parameters.Add(new NpgsqlParameter("@data", NpgsqlDbType.Jsonb) { Value = valueTypesJson });
                command.Parameters.Add(new NpgsqlParameter("@owner", NpgsqlDbType.Uuid) { Value = packageInvitation.Owner });
                command.Parameters.Add(new NpgsqlParameter("@package", NpgsqlDbType.Uuid) { Value = packageInvitation.Package });
                command.Parameters.Add(new NpgsqlParameter("@target", NpgsqlDbType.Uuid) { Value = packageInvitation.Target });

                var sql = sqlBuilder.ToString();

                this.logger.LogTrace("Create PackageInvitation SQL: {sql}", sql);

                command.CommandText = sql;
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("PackageInvitation - Execute Create SQL");
                await command.ExecuteNonQueryAsync(token);
                this.logger.LogDebug("PackageInvitation - Create SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                this.logger.LogInformation("PackageInvitation created: {Dto}", packageInvitation);

                return Result.Ok();
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "The PackageInvitation could not be created in the database: {Dto}", packageInvitation);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Asynchronously reads <see cref="IPackageInvitation"/> instances from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Read operation.</param>
        /// <param name="include">An array of unique identifiers of <see cref="IPackageInvitation"/> instances that are to be read.</param>
        /// <param name="exclude">An array of unique identifiers of <see cref="IPackageInvitation"/> instances that are to be excluded from the read results.</param>
        /// <returns>An <see cref="ImmutableList{T}"/> of <see cref="IPackageInvitation"/>.</returns>
        public async Task<Result<ImmutableList<IPackageInvitation>>> ReadAsync(NpgsqlTransaction transaction, CancellationToken token, Guid[] include = null, Guid[] exclude = null)
        {
            this.logger.LogDebug("Starting to Read the PackageInvitation instances: include {@Include} - exclude {@Exclude}", include, exclude);

            include ??= [];
            exclude ??= [];

            var overlap = include.Intersect(exclude).ToArray();

            if (overlap.Length > 0)
            {
                this.logger.LogWarning("Overlapping PackageInvitation identifiers found between include and exclude: {@Overlap}", overlap);

                return Result.Fail("PackageInvitation include and exclude arrays contain overlapping identifiers.");
            }

            if (include.Length == 0)
            {
                include = (await this.ReadIdentifiersAsync(transaction, token)).ToArray();
            }

            include = include.Except(exclude).ToArray();

            if (include.Length == 0)
            {
                return Result.Ok(ImmutableList<IPackageInvitation>.Empty);
            }

            this.logger.LogDebug("Reading the following PackageInvitation instances from the database {@Identifiers}", include);

            try
            {
                const string sql =
                """
                    -- READ Thing
                    SELECT
                       "Thing"."id" AS "id",
                       "Thing"."classKind" AS "classKind",
                       ("Thing"."data"->>'createdAt') AS "createdAt",
                       ("Thing"."data"->>'experisAt') AS "experisAt",
                       ("Thing"."data"->>'modifiedAt') AS "modifiedAt",
                       ("Thing"."data"->>'packageInvitationKind') AS "packageInvitationKind",
                       ("Thing"."data"->>'status') AS "status",
                       "PackageInvitation"."owner" AS "owner",
                       "PackageInvitation"."package" AS "package",
                       "PackageInvitation"."target" AS "target"
                    FROM "Forge"."Thing" AS "Thing"

                    -- READ Invitation
                    INNER JOIN "Forge"."Invitation" AS "Invitation"
                            ON "Invitation"."id" = "Thing"."id"

                    -- READ PackageInvitation
                    INNER JOIN "Forge"."PackageInvitation" AS "PackageInvitation"
                            ON "PackageInvitation"."id" = "Thing"."id"

                    WHERE "PackageInvitation"."id" = ANY(@include);

                """;

                this.logger.LogTrace("Read PackageInvitation SQL: {sql}", sql);

                await using var command = new NpgsqlCommand(sql, transaction.Connection, transaction);

                command.Parameters.Add(new NpgsqlParameter("include", (NpgsqlDbType)((int)NpgsqlDbType.Array | (int)NpgsqlDbType.Uuid)) { Value = include });

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("PackageInvitation - Execute Read SQL");
                await using var reader = await command.ExecuteReaderAsync(token);
                this.logger.LogDebug("PackageInvitation - Read SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                sw.Restart();
                this.logger.LogDebug("PackageInvitation - Execute MapToDto");
                var i = 0;
                List<IPackageInvitation> databaseResult = [];

                while (await reader.ReadAsync(token))
                {
                    var dto = MapToDto(reader);
                    databaseResult.Add(dto);
                    i++;
                }

                this.logger.LogDebug("A total of {i} PackageInvitation instance(s) mapped to DTO in {sw} [ms]", i, sw.ElapsedMilliseconds);

                if (include.Length > 0 && databaseResult.Count == 0)
                {
                    return Result.Fail("PackageInvitation data not found in the database.");
                }

                this.logger.LogInformation("{i} PackageInvitation instances Read from the database", i);

                return Result.Ok(databaseResult.ToImmutableList());
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "The PackageInvitation instance(s) could not be read from the database: include {@Include} - exclude {@Exclude}", include, exclude);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Reads the unique identifiers of all <see cref="IPackageInvitation"/> objects from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Read operation.</param>
        /// <returns>The list of identifiers of the <see cref="IPackageInvitation"/> objects that exist in the database.</returns>
        public async Task<List<Guid>> ReadIdentifiersAsync(NpgsqlTransaction transaction, CancellationToken token)
        {
            this.logger.LogDebug("Reading the PackageInvitation Identifiers from the database");

            try
            {
                const string sql =
                    """
                    SELECT id FROM "Forge"."PackageInvitation";
                    """;

                await using var command = new NpgsqlCommand(sql, transaction.Connection, transaction);

                await using var reader = await command.ExecuteReaderAsync(token);

                List<Guid> result = [];

                while (await reader.ReadAsync(token))
                {
                    result.Add(reader.GetGuid(0));
                }

                return result;
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "Could not read the PackageInvitation identifiers from the database");
                throw;
            }
        }

        /// <summary>
        /// Asynchronously updates (persists) an instance of <see cref="IPackageInvitation"/> in the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Update operation.</param>
        /// <param name="packageInvitation">The <see cref="IPackageInvitation"/> that is to be updated.</param>
        /// <returns>Returns a successful <see cref="Result"/> when updated successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> UpdateAsync(NpgsqlTransaction transaction, CancellationToken token, IPackageInvitation packageInvitation)
        {
            this.logger.LogDebug("Starting to Update the PackageInvitation {Dto}", packageInvitation);

            try
            {
                var originalThingResult = await this.ReadAsync(transaction, token, [packageInvitation.Id]);

                if (originalThingResult.IsFailed)
                {
                    this.logger.LogError("Original PackageInvitation {Id} was not found.", packageInvitation.Id);

                    return Result.Fail(originalThingResult.Errors);
                }

                // Log changes between the original and the updated PackageInvitation
                var originalThing = originalThingResult.ValueOrDefault?.FirstOrDefault();
                DaoHelper.LogChanges(this.logger, this.comparer, originalThing, packageInvitation);

                await using var command = new NpgsqlCommand();

                // ValueType and Single Reference Properties SQL
                const string valueTypeAndSingleReferenceProperties =
                """
                -- Thing
                UPDATE "Forge"."Thing" SET "data" = @data WHERE "id" = @id;

                -- PackageInvitation
                UPDATE "Forge"."PackageInvitation"
                SET
                    "owner" = @owner,
                    "package" = @package,
                    "target" = @target
                WHERE "id" = @id;

                """;

                var sqlBuilder = new StringBuilder(valueTypeAndSingleReferenceProperties);

                using var memoryStream = new MemoryStream();
                await this.serializer.SerializeAsync(packageInvitation, memoryStream, new JsonWriterOptions(), token);
                var valueTypesJson = Encoding.UTF8.GetString(memoryStream.ToArray());

                this.logger.LogTrace("PackageInvitation ValueType JSON: {valueTypesJson}", valueTypesJson);

                // Thing NpgsqlParameter
                command.Parameters.Add(new NpgsqlParameter("@id", NpgsqlDbType.Uuid) { Value = packageInvitation.Id });
                command.Parameters.Add(new NpgsqlParameter("@data", NpgsqlDbType.Jsonb) { Value = valueTypesJson });
                command.Parameters.Add(new NpgsqlParameter("@owner", NpgsqlDbType.Uuid) { Value = packageInvitation.Owner });
                command.Parameters.Add(new NpgsqlParameter("@package", NpgsqlDbType.Uuid) { Value = packageInvitation.Package });
                command.Parameters.Add(new NpgsqlParameter("@target", NpgsqlDbType.Uuid) { Value = packageInvitation.Target });

                var sql = sqlBuilder.ToString();

                this.logger.LogTrace("Update PackageInvitation SQL: {sql}", sql);

                command.CommandText = sql;
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("PackageInvitation - Execute Update SQL");
                await command.ExecuteNonQueryAsync(token);
                this.logger.LogDebug("PackageInvitation - Update SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                this.logger.LogInformation("PackageInvitation updated: {Dto}", packageInvitation);

                return Result.Ok();
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "The PackageInvitation could not be updated in the database: {Dto}", packageInvitation);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Asynchronously deletes the provided <see cref="IPackageInvitation"/> instances from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="dtos">The collection of <see cref="IPackageInvitation"/> that are to be deleted from the database.</param>
        /// <returns>Returns a successful <see cref="Result"/> when deleted successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> DeleteAsync(NpgsqlTransaction transaction, CancellationToken token, IEnumerable<IPackageInvitation> dtos)
        {
            this.logger.LogDebug("Starting to Delete the PackageInvitation instances {dtos}", dtos);

            var ids = dtos.Select(x => x.Id).ToArray();

            try
            {
                await using var command = new NpgsqlCommand();

                const string sql =
                """
                DELETE FROM "Forge"."PackageInvitation" WHERE id = ANY (@id) RETURNING id;
                """;

                this.logger.LogTrace("Delete PackageInvitation SQL: {sql}", sql);

                command.CommandText = sql;
                command.Parameters.Add(new NpgsqlParameter("id", (NpgsqlDbType)((int)NpgsqlDbType.Array | (int)NpgsqlDbType.Uuid)) { Value = ids });
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("PackageInvitation - Execute Delete SQL");

                List<Guid> deletedIds = [];

                await using (var reader = await command.ExecuteReaderAsync(token))
                {
                    while (await reader.ReadAsync(token))
                    {
                        deletedIds.Add(reader.GetGuid(0));
                    }
                }

                this.logger.LogDebug("PackageInvitation - Delete SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                var equal = new HashSet<Guid>(ids).SetEquals(deletedIds);

                if (!equal)
                {
                    this.logger.LogWarning("A different set of PackageInvitation instances was deleted than requested {id}:{deleted}", ids, deletedIds);
                }

                return Result.Ok();
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "Delete of PackageInvitation {id} failed with an error", ids);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Maps the contents of the <see cref="NpgsqlDataReader"/> to an <see cref="IPackageInvitation"/>.
        /// </summary>
        /// <param name="reader">An instance of <see cref="NpgsqlDataReader"/> that contains the data that is to be read.</param>
        /// <returns>An instance of <see cref="IPackageInvitation"/>.</returns>
        private static IPackageInvitation MapToDto(NpgsqlDataReader reader)
        {
            var dto = new PackageInvitation
            {
                Id = (Guid)reader["id"],
                CreatedAt = DateTime.Parse((string)reader["createdAt"], CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
                ExperisAt = DateTime.Parse((string)reader["experisAt"], CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
                ModifiedAt = DateTime.Parse((string)reader["modifiedAt"], CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
                Owner = (Guid)reader["owner"],
                Package = (Guid)reader["package"],
                PackageInvitationKind = PackageInvitationKindProvider.Parse((string)reader["packageInvitationKind"]),
                Status = InvitationStatusKindProvider.Parse((string)reader["status"]),
                Target = (Guid)reader["target"]
            };

            return dto;
        }
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
