// ------------------------------------------------------------------------------------------------
// <copyright file="PackageMetaDataDao.cs" company="Starion Group S.A.">
//
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Orm.AutoGeneratedDao
{
    using System.CodeDom.Compiler;
    using System.Collections.Immutable;
    using System.Diagnostics;
    using System.Text;
    using System.Text.Json;

    using FluentResults;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Common.AutoGenDtoComparer;
    using Mycelium.Forge.Orm.Helpers;
    using Mycelium.Forge.Serializer.Json;

    using Npgsql;

    using NpgsqlTypes;

    /// <summary>
    /// The <see cref="PackageMetaDataDao"/> class is a Data Access Object which acts
    /// as an ORM layer to the SQL database.
    /// </summary>
    [GeneratedCode("Mycelium.Forge.Generator", "1.0.0")]
    public partial class PackageMetaDataDao : IPackageMetaDataDao
    {
        /// <summary>
        /// The (injected) <see cref="ILogger"/> used for logging.
        /// </summary>
        private readonly ILogger<PackageMetaDataDao> logger;

        /// <summary>
        /// The (injected) <see cref="ISerializer"/> used for JSON serialization.
        /// </summary>
        private readonly ISerializer serializer;

        /// <summary>
        /// The (injected) <see cref="PackageMetaDataComparer"/> used to compare older and newer object versions.
        /// </summary>
        private readonly PackageMetaDataComparer comparer;

        /// <summary>
        /// Initializes a new instance of the <see cref="PackageMetaDataDao"/> class.
        /// </summary>
        /// <param name="logger">The (injected) <see cref="ILogger"/> to perform logging.</param>
        /// <param name="serializer">The (injected) <see cref="ISerializer"/> used for JSON serialization.</param>
        /// <param name="comparer">The (injected) <see cref="PackageMetaDataComparer"/> used to compare older and newer object versions.</param>
        public PackageMetaDataDao(ILogger<PackageMetaDataDao> logger, ISerializer serializer, PackageMetaDataComparer comparer)
        {
            this.logger = logger;
            this.serializer = serializer;
            this.comparer = comparer;

            this.logger.LogDebug("PackageMetaDataDao Initialized");
        }

        /// <summary>
        /// Asynchronously creates (persists) an instance of <see cref="IPackageMetaData"/> in the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Create operation.</param>
        /// <param name="packageMetaData">The <see cref="IPackageMetaData"/> that is to be persisted.</param>
        /// <returns>Returns a successful <see cref="Result"/> when persisted successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> CreateAsync(NpgsqlTransaction transaction, CancellationToken token, IPackageMetaData packageMetaData)
        {
            this.logger.LogDebug("Starting to Create the PackageMetaData {Dto}", packageMetaData);

            try
            {
                await using var command = new NpgsqlCommand();

                // ValueType and Single Reference Properties SQL
                const string valueTypeAndSingleReferenceProperties =
                """
                -- Thing
                INSERT INTO "Forge"."Thing" ("id", "classKind", "data")
                VALUES (@id, @classKind, @data);

                -- PackageMetaData
                INSERT INTO "Forge"."PackageMetaData" ("id", "owner")
                VALUES (@id, @owner);

                """;

                var sqlBuilder = new StringBuilder(valueTypeAndSingleReferenceProperties);

                using var memoryStream = new MemoryStream();
                await this.serializer.SerializeAsync(packageMetaData, memoryStream, new JsonWriterOptions(), token);
                var valueTypesJson = Encoding.UTF8.GetString(memoryStream.ToArray());

                this.logger.LogTrace("PackageMetaData ValueType JSON: {valueTypesJson}", valueTypesJson);

                // Thing NpgsqlParameter
                command.Parameters.Add(new NpgsqlParameter("@id", NpgsqlDbType.Uuid) { Value = packageMetaData.Id });
                command.Parameters.Add(new NpgsqlParameter("@classKind", NpgsqlDbType.Text) { Value = "PackageMetaData" });
                command.Parameters.Add(new NpgsqlParameter("@data", NpgsqlDbType.Jsonb) { Value = valueTypesJson });
                command.Parameters.Add(new NpgsqlParameter("@owner", NpgsqlDbType.Uuid) { Value = packageMetaData.Owner });

                var sql = sqlBuilder.ToString();

                this.logger.LogTrace("Create PackageMetaData SQL: {sql}", sql);

                command.CommandText = sql;
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("PackageMetaData - Execute Create SQL");
                await command.ExecuteNonQueryAsync(token);
                this.logger.LogDebug("PackageMetaData - Create SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                this.logger.LogInformation("PackageMetaData created: {Dto}", packageMetaData);

                return Result.Ok();
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "The PackageMetaData could not be created in the database: {Dto}", packageMetaData);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Asynchronously reads <see cref="IPackageMetaData"/> instances from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Read operation.</param>
        /// <param name="include">An array of unique identifiers of <see cref="IPackageMetaData"/> instances that are to be read.</param>
        /// <param name="exclude">An array of unique identifiers of <see cref="IPackageMetaData"/> instances that are to be excluded from the read results.</param>
        /// <returns>An <see cref="ImmutableList{T}"/> of <see cref="IPackageMetaData"/>.</returns>
        public async Task<Result<ImmutableList<IPackageMetaData>>> ReadAsync(NpgsqlTransaction transaction, CancellationToken token, Guid[] include = null, Guid[] exclude = null)
        {
            this.logger.LogDebug("Starting to Read the PackageMetaData instances: include {@Include} - exclude {@Exclude}", include, exclude);

            include ??= [];
            exclude ??= [];

            var overlap = include.Intersect(exclude).ToArray();

            if (overlap.Length > 0)
            {
                this.logger.LogWarning("Overlapping PackageMetaData identifiers found between include and exclude: {@Overlap}", overlap);

                return Result.Fail("PackageMetaData include and exclude arrays contain overlapping identifiers.");
            }

            if (include.Length == 0)
            {
                include = (await this.ReadIdentifiersAsync(transaction, token)).ToArray();
            }

            include = include.Except(exclude).ToArray();

            if (include.Length == 0)
            {
                return Result.Ok(ImmutableList<IPackageMetaData>.Empty);
            }

            this.logger.LogDebug("Reading the following PackageMetaData instances from the database {@Identifiers}", include);

            try
            {
                const string sql =
                """
                    -- READ Thing
                    SELECT
                       "Thing"."id" AS "id",
                       "Thing"."classKind" AS "classKind",
                       ("Thing"."data"->>'createdAt') AS "createdAt",
                       ("Thing"."data"->>'modifiedAt') AS "modifiedAt",
                       "PackageMetaData"."owner" AS "owner"
                    FROM "Forge"."Thing" AS "Thing"

                    -- READ PackageMetaData
                    INNER JOIN "Forge"."PackageMetaData" AS "PackageMetaData"
                            ON "PackageMetaData"."id" = "Thing"."id"

                    WHERE "PackageMetaData"."id" = ANY(@include);

                """;

                this.logger.LogTrace("Read PackageMetaData SQL: {sql}", sql);

                await using var command = new NpgsqlCommand(sql, transaction.Connection, transaction);

                command.Parameters.Add(new NpgsqlParameter("include", (NpgsqlDbType)((int)NpgsqlDbType.Array | (int)NpgsqlDbType.Uuid)) { Value = include });

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("PackageMetaData - Execute Read SQL");
                await using var reader = await command.ExecuteReaderAsync(token);
                this.logger.LogDebug("PackageMetaData - Read SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                sw.Restart();
                this.logger.LogDebug("PackageMetaData - Execute MapToDto");
                var i = 0;
                List<IPackageMetaData> databaseResult = [];

                while (await reader.ReadAsync(token))
                {
                    var dto = MapToDto(reader);
                    databaseResult.Add(dto);
                    i++;
                }

                this.logger.LogDebug("A total of {i} PackageMetaData instance(s) mapped to DTO in {sw} [ms]", i, sw.ElapsedMilliseconds);

                if (include.Length > 0 && databaseResult.Count == 0)
                {
                    return Result.Fail("PackageMetaData data not found in the database.");
                }

                this.logger.LogInformation("{i} PackageMetaData instances Read from the database", i);

                return Result.Ok(databaseResult.ToImmutableList());
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "The PackageMetaData instance(s) could not be read from the database: include {@Include} - exclude {@Exclude}", include, exclude);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Reads the unique identifiers of all <see cref="IPackageMetaData"/> objects from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Read operation.</param>
        /// <returns>The list of identifiers of the <see cref="IPackageMetaData"/> objects that exist in the database.</returns>
        public async Task<List<Guid>> ReadIdentifiersAsync(NpgsqlTransaction transaction, CancellationToken token)
        {
            this.logger.LogDebug("Reading the PackageMetaData Identifiers from the database");

            try
            {
                const string sql =
                    """
                    SELECT id FROM "Forge"."PackageMetaData";
                    """;

                await using var command = new NpgsqlCommand(sql, transaction.Connection, transaction);

                await using var reader = await command.ExecuteReaderAsync(token);

                List<Guid> result = [];

                while (await reader.ReadAsync(token))
                {
                    result.Add(reader.GetGuid(0));
                }

                return result;
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "Could not read the PackageMetaData identifiers from the database");
                throw;
            }
        }

        /// <summary>
        /// Asynchronously updates (persists) an instance of <see cref="IPackageMetaData"/> in the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the Update operation.</param>
        /// <param name="packageMetaData">The <see cref="IPackageMetaData"/> that is to be updated.</param>
        /// <returns>Returns a successful <see cref="Result"/> when updated successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> UpdateAsync(NpgsqlTransaction transaction, CancellationToken token, IPackageMetaData packageMetaData)
        {
            this.logger.LogDebug("Starting to Update the PackageMetaData {Dto}", packageMetaData);

            try
            {
                var originalThingResult = await this.ReadAsync(transaction, token, [packageMetaData.Id]);

                if (originalThingResult.IsFailed)
                {
                    this.logger.LogError("Original PackageMetaData {Id} was not found.", packageMetaData.Id);

                    return Result.Fail(originalThingResult.Errors);
                }

                // Log changes between the original and the updated PackageMetaData
                var originalThing = originalThingResult.ValueOrDefault?.FirstOrDefault();
                DaoHelper.LogChanges(this.logger, this.comparer, originalThing, packageMetaData);

                await using var command = new NpgsqlCommand();

                // ValueType and Single Reference Properties SQL
                const string valueTypeAndSingleReferenceProperties =
                """
                -- Thing
                UPDATE "Forge"."Thing" SET "data" = @data WHERE "id" = @id;

                -- PackageMetaData
                UPDATE "Forge"."PackageMetaData"
                SET
                    "owner" = @owner
                WHERE "id" = @id;

                """;

                var sqlBuilder = new StringBuilder(valueTypeAndSingleReferenceProperties);

                using var memoryStream = new MemoryStream();
                await this.serializer.SerializeAsync(packageMetaData, memoryStream, new JsonWriterOptions(), token);
                var valueTypesJson = Encoding.UTF8.GetString(memoryStream.ToArray());

                this.logger.LogTrace("PackageMetaData ValueType JSON: {valueTypesJson}", valueTypesJson);

                // Thing NpgsqlParameter
                command.Parameters.Add(new NpgsqlParameter("@id", NpgsqlDbType.Uuid) { Value = packageMetaData.Id });
                command.Parameters.Add(new NpgsqlParameter("@data", NpgsqlDbType.Jsonb) { Value = valueTypesJson });
                command.Parameters.Add(new NpgsqlParameter("@owner", NpgsqlDbType.Uuid) { Value = packageMetaData.Owner });

                var sql = sqlBuilder.ToString();

                this.logger.LogTrace("Update PackageMetaData SQL: {sql}", sql);

                command.CommandText = sql;
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("PackageMetaData - Execute Update SQL");
                await command.ExecuteNonQueryAsync(token);
                this.logger.LogDebug("PackageMetaData - Update SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                this.logger.LogInformation("PackageMetaData updated: {Dto}", packageMetaData);

                return Result.Ok();
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "The PackageMetaData could not be updated in the database: {Dto}", packageMetaData);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Asynchronously deletes the provided <see cref="IPackageMetaData"/> instances from the database.
        /// </summary>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="dtos">The collection of <see cref="IPackageMetaData"/> that are to be deleted from the database.</param>
        /// <returns>Returns a successful <see cref="Result"/> when deleted successfully, or a failed <see cref="Result"/> if not successful.</returns>
        public async Task<Result> DeleteAsync(NpgsqlTransaction transaction, CancellationToken token, IEnumerable<IPackageMetaData> dtos)
        {
            this.logger.LogDebug("Starting to Delete the PackageMetaData instances {dtos}", dtos);

            var ids = dtos.Select(x => x.Id).ToArray();

            try
            {
                await using var command = new NpgsqlCommand();

                const string sql =
                """
                DELETE FROM "Forge"."PackageMetaData" WHERE id = ANY (@id) RETURNING id;
                """;

                this.logger.LogTrace("Delete PackageMetaData SQL: {sql}", sql);

                command.CommandText = sql;
                command.Parameters.Add(new NpgsqlParameter("id", (NpgsqlDbType)((int)NpgsqlDbType.Array | (int)NpgsqlDbType.Uuid)) { Value = ids });
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                var sw = Stopwatch.StartNew();
                this.logger.LogDebug("PackageMetaData - Execute Delete SQL");

                List<Guid> deletedIds = [];

                await using (var reader = await command.ExecuteReaderAsync(token))
                {
                    while (await reader.ReadAsync(token))
                    {
                        deletedIds.Add(reader.GetGuid(0));
                    }
                }

                this.logger.LogDebug("PackageMetaData - Delete SQL executed in {sw} [ms]", sw.ElapsedMilliseconds);

                var equal = new HashSet<Guid>(ids).SetEquals(deletedIds);

                if (!equal)
                {
                    this.logger.LogWarning("A different set of PackageMetaData instances was deleted than requested {id}:{deleted}", ids, deletedIds);
                }

                return Result.Ok();
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "Delete of PackageMetaData {id} failed with an error", ids);

                return Result.Fail(ex.Message);
            }
        }

        /// <summary>
        /// Maps the contents of the <see cref="NpgsqlDataReader"/> to an <see cref="IPackageMetaData"/>.
        /// </summary>
        /// <param name="reader">An instance of <see cref="NpgsqlDataReader"/> that contains the data that is to be read.</param>
        /// <returns>An instance of <see cref="IPackageMetaData"/>.</returns>
        private static IPackageMetaData MapToDto(NpgsqlDataReader reader)
        {
            var dto = new PackageMetaData
            {
                Id = (Guid)reader["id"],
                CreatedAt = DateTime.Parse((string)reader["createdAt"]),
                ModifiedAt = DateTime.Parse((string)reader["modifiedAt"]),
                Owner = (Guid)reader["owner"]
            };

            return dto;
        }
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
