// ------------------------------------------------------------------------------------------------
// <copyright file="UmlCoreSqlSchemaGeneratorTestFixture.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Generator.Tests
{
    using System;
    using System.IO;
    using System.Threading.Tasks;

    using Mycelium.Forge.Generator.Generators;
    using Mycelium.Forge.Generator.Tests.Extensions;

    /// <summary>
    /// Suite of tests for the <see cref="UmlCoreSqlSchemaGenerator" /> class.
    /// </summary>
    [TestFixture]
    public class UmlCoreSqlSchemaGeneratorTestFixture
    {
        private UmlCoreSqlSchemaGenerator generator;
        private DirectoryInfo outputDirectory;

        /// <summary>
        /// Sets up the test fixture before each test execution.
        /// </summary>
        [SetUp]
        public void SetUp()
        {
            this.generator = new UmlCoreSqlSchemaGenerator();
            this.outputDirectory = new DirectoryInfo(Path.Combine(TestContext.CurrentContext.WorkDirectory, "TestSqlSchemaOutput"));
            this.outputDirectory.Create();
        }

        /// <summary>
        /// Cleans up any resources after each test execution.
        /// </summary>
        [TearDown]
        public void TearDown()
        {
            if (this.outputDirectory.Exists)
            {
                this.outputDirectory.Delete(true);
            }
        }

        /// <summary>
        /// Verifies that
        /// <see cref="UmlCoreSqlSchemaGenerator.GenerateAsync(uml4net.xmi.Readers.XmiReaderResult, DirectoryInfo)" />
        /// correctly writes the SQL schema to disk and throws when arguments are invalid.
        /// </summary>
        /// <returns>An awaitable <see cref="Task" />.</returns>
        [Test]
        public async Task VerifyGenerateAsync()
        {
            var expected = await File.ReadAllTextAsync(
                Path.Combine(TestContext.CurrentContext.TestDirectory, "Expected", "AutoGeneratedSqlSchema", "schema.sql"));

            await this.generator.GenerateAsync(GeneratorSetupFixture.XmiReaderResult, this.outputDirectory);

            var schemaFilePath = Path.Combine(this.outputDirectory.FullName, "schema.sql");

            using (Assert.EnterMultipleScope())
            {
                Assert.That(File.Exists(schemaFilePath), Is.True);

                var generatedContent = await File.ReadAllTextAsync(schemaFilePath);
                Assert.That(generatedContent.NormalizeLineEndings(), Is.EqualTo(expected.NormalizeLineEndings()));

                Assert.That(
                    async () => await this.generator.GenerateAsync(null!, this.outputDirectory),
                    Throws.TypeOf<ArgumentNullException>());

                Assert.That(
                    async () => await this.generator.GenerateAsync(GeneratorSetupFixture.XmiReaderResult, null!),
                    Throws.TypeOf<ArgumentNullException>());
            }
        }

        /// <summary>
        /// Verifies that <see cref="UmlCoreSqlSchemaGenerator.GenerateSqlSchemaAsync(uml4net.xmi.Readers.XmiReaderResult)" />
        /// correctly generates the SQL schema and throws when arguments are invalid.
        /// </summary>
        /// <returns>An awaitable <see cref="Task" />.</returns>
        [Test]
        public async Task VerifyGenerateSqlSchemaAsync()
        {
            var expected = await File.ReadAllTextAsync(
                Path.Combine(TestContext.CurrentContext.TestDirectory, "Expected", "AutoGeneratedSqlSchema", "schema.sql"));

            var actual = await this.generator.GenerateSqlSchemaAsync(GeneratorSetupFixture.XmiReaderResult);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(actual.NormalizeLineEndings(), Is.EqualTo(expected.NormalizeLineEndings()));

                Assert.That(
                    async () => await this.generator.GenerateSqlSchemaAsync(null!),
                    Throws.TypeOf<ArgumentNullException>());
            }
        }
    }
}
