// ------------------------------------------------------------------------------------------------
// <copyright file="UserServiceTestFixture.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Tests.Services
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Immutable;
    using System.Security.Claims;
    using System.Threading;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Http;

    using Moq;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Dal.AutoGeneratedServices;
    using Mycelium.Forge.Data;
    using Mycelium.Forge.Services;

    /// <summary>
    /// Test fixture for <see cref="UserService" />.
    /// </summary>
    [TestFixture]
    public class UserServiceTestFixture
    {
        private Mock<IAccountService> accountServiceMock;
        private Mock<IHttpContextAccessor> httpContextAccessorMock;
        private UserService userService;

        /// <summary>
        /// Sets up mock dependencies and creates the user service before each test.
        /// </summary>
        [SetUp]
        public void SetUp()
        {
            this.accountServiceMock = new Mock<IAccountService>();
            this.httpContextAccessorMock = new Mock<IHttpContextAccessor>();

            this.accountServiceMock
                .Setup(service => service.ReadAsync(
                    It.IsAny<IUserContext>(),
                    It.IsAny<CancellationToken>(),
                    It.Is<Guid[]>(ids => ids.Length == 1 && ids[0] == SeedData.RegisAccount.Id)))
                .ReturnsAsync(ImmutableList.Create<IAccount>(SeedData.RegisAccount));

            this.accountServiceMock
                .Setup(service => service.ReadAsync(
                    It.IsAny<IUserContext>(),
                    It.IsAny<CancellationToken>(),
                    It.Is<Guid[]>(ids => ids.Length == 1 && ids[0] == SeedData.StefanAccount.Id)))
                .ReturnsAsync(ImmutableList.Create<IAccount>(SeedData.StefanAccount));

            this.userService = new UserService(this.accountServiceMock.Object, this.httpContextAccessorMock.Object);
        }

        /// <summary>
        /// Verifies that <see cref="UserService.GetCurrentUser" /> retrieves user identity from state and HTTP context.
        /// </summary>
        /// <returns>A <see cref="Task" /> representing the asynchronous operation.</returns>
        [Test]
        public async Task VerifyGetCurrentUser()
        {
            var initialUser = await this.userService.GetCurrentUser();
            Assert.That(initialUser, Is.Null);

            await this.userService.SetCurrentUser(SeedData.RegisAccount.Id);
            var user = await this.userService.GetCurrentUser();
            var userForceLoaded = await this.userService.GetCurrentUser(true);

            var httpContextAccessor = new Mock<IHttpContextAccessor>();

            var claims = new List<Claim>
            {
                new(ClaimTypes.NameIdentifier, SeedData.StefanAccount.Id.ToString()),
                new(ClaimTypes.Role, nameof(RoleKind.Account))
            };

            var identity = new ClaimsIdentity(claims, "Cookie");
            var context = new DefaultHttpContext { User = new ClaimsPrincipal(identity) };
            httpContextAccessor.Setup(x => x.HttpContext).Returns(context);

            var httpUserService = new UserService(this.accountServiceMock.Object, httpContextAccessor.Object);
            var httpUser = await httpUserService.GetCurrentUser();

            using (Assert.EnterMultipleScope())
            {
                Assert.That(user, Is.Not.Null);
                Assert.That(user.Id, Is.EqualTo(SeedData.RegisAccount.Id));
                Assert.That(user.Name, Is.EqualTo(SeedData.RegisAccount.Name));
                Assert.That(user.ShortName, Is.EqualTo(SeedData.RegisAccount.ShortName));
                Assert.That(userForceLoaded, Is.SameAs(user));
                Assert.That(httpUser, Is.Not.Null);
                Assert.That(httpUser.Id, Is.EqualTo(SeedData.StefanAccount.Id));
            }
        }

        /// <summary>
        /// Verifies that <see cref="UserService.GetUserContext" /> returns anonymous or populated user context.
        /// </summary>
        /// <returns>A <see cref="Task" /> representing the asynchronous operation.</returns>
        [Test]
        public async Task VerifyGetUserContext()
        {
            var anonContext = await this.userService.GetUserContext();

            using (Assert.EnterMultipleScope())
            {
                Assert.That(anonContext.AccountId, Is.Null);
                Assert.That(anonContext.Username, Is.EqualTo("anonymous"));
                Assert.That(anonContext.IsAuthenticated, Is.False);
            }

            await this.userService.SetCurrentUser(SeedData.RegisAccount.Id);
            var userContext = await this.userService.GetUserContext();
            var userContextForceLoaded = await this.userService.GetUserContext(true);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(userContext, Is.Not.Null);
                Assert.That(userContext.AccountId, Is.EqualTo(SeedData.RegisAccount.Id));
                Assert.That(userContext.Username, Is.EqualTo(SeedData.RegisAccount.ShortName));
                Assert.That(userContext.IsAuthenticated, Is.True);
                Assert.That(userContextForceLoaded.AccountId, Is.EqualTo(SeedData.RegisAccount.Id));
            }
        }

        /// <summary>
        /// Verifies the <see cref="UserService.IsAuthenticated" /> property before and after setting current user.
        /// </summary>
        /// <returns>A <see cref="Task" /> representing the asynchronous operation.</returns>
        [Test]
        public async Task VerifyIsAuthenticated()
        {
            Assert.That(this.userService.IsAuthenticated, Is.False);

            await this.userService.SetCurrentUser(SeedData.RegisAccount.Id);
            Assert.That(this.userService.IsAuthenticated, Is.True);

            await this.userService.SetCurrentUser(null);
            Assert.That(this.userService.IsAuthenticated, Is.False);
        }

        /// <summary>
        /// Verifies that <see cref="UserService.SetCurrentUser" /> configures user identity and roles.
        /// </summary>
        /// <returns>A <see cref="Task" /> representing the asynchronous operation.</returns>
        [Test]
        public async Task VerifySetCurrentUser()
        {
            await this.userService.SetCurrentUser(SeedData.StefanAccount.Id);
            var stefanContext = await this.userService.GetUserContext();

            using (Assert.EnterMultipleScope())
            {
                Assert.That(this.userService.IsAuthenticated, Is.True);
                Assert.That(stefanContext.CurrentRoles, Contains.Item(RoleKind.Account));
            }

            await this.userService.SetCurrentUser(null);
            var anonymousContext = await this.userService.GetUserContext();

            using (Assert.EnterMultipleScope())
            {
                Assert.That(this.userService.IsAuthenticated, Is.False);
                Assert.That(anonymousContext.CurrentRoles, Contains.Item(RoleKind.Anonymous));
            }
        }
    }
}
