// ------------------------------------------------------------------------------------------------
// <copyright file="APIKeyReadFilter.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Orm.AutoGeneratedFilters
{
    using System.CodeDom.Compiler;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Orm.Filters;

    using NpgsqlTypes;

    /// <summary>
    /// Factory for creating SQL read visibility filters for <see cref="IAPIKey" />.
    /// </summary>
    [GeneratedCode("Mycelium.Forge.Generator", "1.0.0")]
    public static class APIKeyReadFilter
    {
        /// <summary>
        /// Creates an <see cref="ISqlFilter" /> for <see cref="IAPIKey" /> instances based on the specified user context.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles for authorization evaluation.</param>
        /// <returns>An <see cref="ISqlFilter" /> containing the SQL visibility predicate and parameter bindings.</returns>
        public static ISqlFilter FromUserContext(IUserContext userContext)
        {
            return new SqlFilter()
                .Where(
                    """
                    @canRevokeAnyApiKey = true
                    OR (@callerAccountId IS NOT NULL AND "APIKey"."owner" = @callerAccountId)
                    """)
                .AddParameter("@callerAccountId", NpgsqlDbType.Uuid, userContext.AccountId)
                .AddParameter("@canRevokeAnyApiKey", NpgsqlDbType.Boolean, PermissionGuard.HasPermission(userContext, PermissionKind.RevokeAnyApiKey));
        }
    }
}
