// ------------------------------------------------------------------------------------------------
// <copyright file="OrganizationSettingsViewModelTestFixture.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Tests.ViewModels.OrganizationSettings
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Immutable;
    using System.Threading;
    using System.Threading.Tasks;

    using ErrorOr;

    using Microsoft.Extensions.Logging;

    using Moq;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Dal.AutoGeneratedServices;
    using Mycelium.Forge.Dal.AutoGenPermissionService;
    using Mycelium.Forge.Dal.DatabaseSource;
    using Mycelium.Forge.Services;
    using Mycelium.Forge.ViewModels.OrganizationSettings;

    [TestFixture]
    public class OrganizationSettingsViewModelTestFixture
    {
        private Mock<IDatabaseSource> databaseSourceMock;
        private Mock<IOrganizationService> organizationServiceMock;
        private Mock<IAccountService> accountServiceMock;
        private Mock<IOrganizationInvitationService> organizationInvitationServiceMock;
        private Mock<IOrganizationPermissionService> organizationPermissionServiceMock;
        private Mock<INotificationService> notificationServiceMock;
        private Mock<IUserService> userServiceMock;
        private Mock<ILogger<OrganizationSettingsViewModel>> loggerMock;
        private OrganizationSettingsViewModel viewModel;
        private UserContext adminUserContext;
        private UserContext memberUserContext;
        private Organization org;
        private Account adminAccount;
        private Account memberAccount;
        private OrganizationInvitation matchingInvitation;
        private OrganizationInvitation acceptedInvitation;
        private OrganizationInvitation otherOrgInvitation;

        [SetUp]
        public void SetUp()
        {
            this.databaseSourceMock = new Mock<IDatabaseSource>();
            this.organizationServiceMock = new Mock<IOrganizationService>();
            this.accountServiceMock = new Mock<IAccountService>();
            this.organizationInvitationServiceMock = new Mock<IOrganizationInvitationService>();
            this.organizationPermissionServiceMock = new Mock<IOrganizationPermissionService>();
            this.notificationServiceMock = new Mock<INotificationService>();
            this.userServiceMock = new Mock<IUserService>();
            this.loggerMock = new Mock<ILogger<OrganizationSettingsViewModel>>();

            var adminId = Guid.NewGuid();
            var memberId = Guid.NewGuid();
            var orgId = Guid.NewGuid();

            this.adminUserContext = new UserContext { AccountId = adminId };
            this.memberUserContext = new UserContext { AccountId = memberId };

            this.org = new Organization
            {
                Id = orgId,
                Name = "Starion Group",
                ShortName = "starion",
                Administrator = [adminId],
                Member = [memberId]
            };

            this.adminAccount = new Account { Id = adminId, Name = "Admin User" };
            this.memberAccount = new Account { Id = memberId, Name = "Member User" };

            this.matchingInvitation = new OrganizationInvitation
            {
                Id = Guid.NewGuid(),
                Organization = orgId,
                Status = InvitationStatusKind.PENDING,
                Target = Guid.NewGuid(),
                ExperiesAt = DateTime.UtcNow
            };

            this.acceptedInvitation = new OrganizationInvitation
            {
                Id = Guid.NewGuid(),
                Organization = orgId,
                Status = InvitationStatusKind.ACCEPTED,
                Target = Guid.NewGuid()
            };

            this.otherOrgInvitation = new OrganizationInvitation
            {
                Id = Guid.NewGuid(),
                Organization = Guid.NewGuid(),
                Status = InvitationStatusKind.PENDING,
                Target = Guid.NewGuid()
            };

            this.userServiceMock.Setup(x => x.GetUserContext(false)).ReturnsAsync(this.adminUserContext);
            this.organizationServiceMock.Setup(x => x.ReadByShortNameAsync(this.adminUserContext, "starion", It.IsAny<CancellationToken>())).ReturnsAsync(this.org);
            this.accountServiceMock.Setup(x => x.ReadAsync(this.adminUserContext, It.IsAny<CancellationToken>(), It.IsAny<Guid[]>())).ReturnsAsync(ImmutableList.Create<IAccount>(this.adminAccount, this.memberAccount));
            this.organizationInvitationServiceMock.Setup(x => x.ReadAsync(this.adminUserContext, It.IsAny<CancellationToken>())).ReturnsAsync(ImmutableList.Create<IOrganizationInvitation>(this.matchingInvitation, this.acceptedInvitation, this.otherOrgInvitation));

            this.viewModel = new OrganizationSettingsViewModel(this.databaseSourceMock.Object, this.organizationServiceMock.Object, this.accountServiceMock.Object, this.organizationInvitationServiceMock.Object, this.organizationPermissionServiceMock.Object, this.notificationServiceMock.Object, this.userServiceMock.Object, this.loggerMock.Object);
        }

        [Test]
        public async Task VerifyChangeMemberRole()
        {
            this.viewModel.Organization = this.org;

            // Scenario 1: Promote to Administrator (success)
            this.organizationServiceMock.Setup(x => x.UpdateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IOrganization>>(), It.IsAny<CancellationToken>())).ReturnsAsync(Result.Updated);

            await this.viewModel.ChangeMemberRole(this.memberAccount, OrganizationInvitationKind.ADMINISTRATOR);

            Assert.That(this.viewModel.Organization.Administrator, Does.Contain(this.memberAccount.Id));

            // Scenario 2: Demote to Member (failure logs error)
            this.organizationServiceMock.Setup(x => x.UpdateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IOrganization>>(), It.IsAny<CancellationToken>())).ReturnsAsync(Error.Failure("Update failed"));

            await this.viewModel.ChangeMemberRole(this.memberAccount, OrganizationInvitationKind.MEMBER);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(this.viewModel.Organization.Administrator, Does.Not.Contain(this.memberAccount.Id));
                Assert.That(this.viewModel.Organization.Member, Does.Contain(this.memberAccount.Id));
                this.loggerMock.Verify(x => x.Log(LogLevel.Error, It.IsAny<EventId>(), It.Is<It.IsAnyType>((v, t) => true), It.IsAny<Exception?>(), It.IsAny<Func<It.IsAnyType, Exception?, string>>()), Times.Once);
            }
        }

        [Test]
        public async Task VerifyInitializeViewModel()
        {
            // Scenario 1: Organization not found
            this.organizationServiceMock.Setup(x => x.ReadByShortNameAsync(this.adminUserContext, "unknown", It.IsAny<CancellationToken>())).ReturnsAsync(Error.NotFound());

            await this.viewModel.InitializeViewModel("unknown");

            using (Assert.EnterMultipleScope())
            {
                Assert.That(this.viewModel.Organization, Is.Null);
                this.loggerMock.Verify(x => x.Log(LogLevel.Warning, It.IsAny<EventId>(), It.Is<It.IsAnyType>((v, t) => true), It.IsAny<Exception?>(), It.IsAny<Func<It.IsAnyType, Exception?, string>>()), Times.Once);
            }

            // Scenario 2: Happy path where user is Administrator
            await this.viewModel.InitializeViewModel("starion");

            using (Assert.EnterMultipleScope())
            {
                Assert.That(this.viewModel.Organization, Is.EqualTo(this.org));
                Assert.That(this.viewModel.CurrentUserRole, Is.EqualTo(OrganizationInvitationKind.ADMINISTRATOR));
                Assert.That(this.viewModel.Members, Has.Count.EqualTo(2));
                Assert.That(this.viewModel.PendingInvitations, Has.Count.EqualTo(1));
                Assert.That(this.viewModel.RoleOptions, Has.Count.EqualTo(2));
            }

            // Scenario 3: User is Member, not Administrator
            this.userServiceMock.Setup(x => x.GetUserContext(false)).ReturnsAsync(this.memberUserContext);
            this.organizationServiceMock.Setup(x => x.ReadByShortNameAsync(this.memberUserContext, "starion", It.IsAny<CancellationToken>())).ReturnsAsync(this.org);
            this.accountServiceMock.Setup(x => x.ReadAsync(this.memberUserContext, It.IsAny<CancellationToken>(), It.IsAny<Guid[]>())).ReturnsAsync(ImmutableList.Create<IAccount>(this.adminAccount, this.memberAccount));
            this.organizationInvitationServiceMock.Setup(x => x.ReadAsync(this.memberUserContext, It.IsAny<CancellationToken>())).ReturnsAsync(ImmutableList.Create<IOrganizationInvitation>(this.matchingInvitation));

            await this.viewModel.InitializeViewModel("starion");

            Assert.That(this.viewModel.CurrentUserRole, Is.EqualTo(OrganizationInvitationKind.MEMBER));
        }

        [Test]
        public async Task VerifyRemoveMember()
        {
            this.viewModel.Organization = this.org;
            this.viewModel.Members = [this.memberAccount];

            // Scenario 1: Failure
            this.organizationServiceMock.Setup(x => x.UpdateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IOrganization>>(), It.IsAny<CancellationToken>())).ReturnsAsync(Error.Failure("Update failed"));

            await this.viewModel.RemoveMember(this.memberAccount);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(this.viewModel.Members, Has.Count.EqualTo(1));
                this.loggerMock.Verify(x => x.Log(LogLevel.Error, It.IsAny<EventId>(), It.Is<It.IsAnyType>((v, t) => true), It.IsAny<Exception?>(), It.IsAny<Func<It.IsAnyType, Exception?, string>>()), Times.Once);
            }

            // Scenario 2: Success
            this.organizationServiceMock.Setup(x => x.UpdateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IOrganization>>(), It.IsAny<CancellationToken>())).ReturnsAsync(Result.Updated);

            await this.viewModel.RemoveMember(this.memberAccount);

            Assert.That(this.viewModel.Members, Has.Count.EqualTo(0));
        }

        [Test]
        public async Task VerifyResendInvitation()
        {
            // Scenario 1: Success
            this.organizationInvitationServiceMock.Setup(x => x.UpdateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IOrganizationInvitation>>(), It.IsAny<CancellationToken>())).ReturnsAsync(Result.Updated);

            await this.viewModel.ResendInvitation(this.matchingInvitation);

            Assert.That(this.matchingInvitation.ExperiesAt, Is.GreaterThan(DateTime.UtcNow));

            // Scenario 2: Failure
            this.organizationInvitationServiceMock.Setup(x => x.UpdateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IOrganizationInvitation>>(), It.IsAny<CancellationToken>())).ReturnsAsync(Error.Failure("Failed"));

            await this.viewModel.ResendInvitation(this.matchingInvitation);

            this.loggerMock.Verify(x => x.Log(LogLevel.Error, It.IsAny<EventId>(), It.Is<It.IsAnyType>((v, t) => true), It.IsAny<Exception?>(), It.IsAny<Func<It.IsAnyType, Exception?, string>>()), Times.Once);
        }

        [Test]
        public async Task VerifyRevokeInvitation()
        {
            this.viewModel.PendingInvitations = [this.matchingInvitation];

            // Scenario 1: Failure
            this.organizationInvitationServiceMock.Setup(x => x.DeleteAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<Guid>>(), It.IsAny<CancellationToken>())).ReturnsAsync(Error.Failure("Failed"));

            await this.viewModel.RevokeInvitation(this.matchingInvitation);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(this.viewModel.PendingInvitations, Has.Count.EqualTo(1));
                this.loggerMock.Verify(x => x.Log(LogLevel.Error, It.IsAny<EventId>(), It.Is<It.IsAnyType>((v, t) => true), It.IsAny<Exception?>(), It.IsAny<Func<It.IsAnyType, Exception?, string>>()), Times.Once);
            }

            // Scenario 2: Success
            this.organizationInvitationServiceMock.Setup(x => x.DeleteAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<Guid>>(), It.IsAny<CancellationToken>())).ReturnsAsync(Result.Deleted);

            await this.viewModel.RevokeInvitation(this.matchingInvitation);

            Assert.That(this.viewModel.PendingInvitations, Has.Count.EqualTo(0));
        }

        [Test]
        public void VerifyTransferOrganization()
        {
            Assert.That(async () => await this.viewModel.TransferOrganization(), Throws.Nothing);
        }
    }
}
