// ------------------------------------------------------------------------------------------------
// <copyright file="OrganizationServiceIntegrationTestFixture.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Orm.Tests.Services
{
    using ErrorOr;

    using Microsoft.Extensions.Logging;

    using Moq;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Common.AutoGenDtoComparer;
    using Mycelium.Forge.Dal.AutoGenDtoValidator;
    using Mycelium.Forge.Dal.AutoGeneratedServices;
    using Mycelium.Forge.Dal.AutoGenPermissionService;
    using Mycelium.Forge.Dal.DatabaseSource;
    using Mycelium.Forge.Orm.AutoGeneratedDao;
    using Mycelium.Forge.Orm.Tests.Helper;

    using Npgsql;

    using NUnit.Framework;

    using ZiggyCreatures.Caching.Fusion;

    [TestFixture]
    [Category("Database")]
    public class OrganizationServiceIntegrationTestFixture : BaseIntegrationTestClassFixture
    {
        private OrganizationService service;
        private IUserContext adminUserContext;
        private IUserContext memberUserContext;
        private IUserContext anonymousUserContext;
        private Guid publicOrgId;
        private Guid privateOrgId;
        private Guid adminAccountId;
        private Guid memberAccountId;

        [Test]
        public async Task VerifyReadByShortNameAsync()
        {
            var anonPublicResult = await this.service.ReadByShortNameAsync(this.anonymousUserContext, "public-org", CancellationToken.None);
            var memberPublicResult = await this.service.ReadByShortNameAsync(this.memberUserContext, "public-org", CancellationToken.None);
            var adminPublicResult = await this.service.ReadByShortNameAsync(this.adminUserContext, "public-org", CancellationToken.None);

            var adminPrivateResult = await this.service.ReadByShortNameAsync(this.adminUserContext, "private-org", CancellationToken.None);
            var anonPrivateResult = await this.service.ReadByShortNameAsync(this.anonymousUserContext, "private-org", CancellationToken.None);
            var notFoundResult = await this.service.ReadByShortNameAsync(this.adminUserContext, "non-existent-org", CancellationToken.None);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(anonPublicResult.IsError, Is.False);
                Assert.That(anonPublicResult.Value.Id, Is.EqualTo(this.publicOrgId));
                Assert.That(anonPublicResult.Value.ShortName, Is.EqualTo("public-org"));

                Assert.That(memberPublicResult.IsError, Is.False);
                Assert.That(memberPublicResult.Value.Id, Is.EqualTo(this.publicOrgId));

                Assert.That(adminPublicResult.IsError, Is.False);
                Assert.That(adminPublicResult.Value.Id, Is.EqualTo(this.publicOrgId));

                Assert.That(adminPrivateResult.IsError, Is.False);
                Assert.That(adminPrivateResult.Value.Id, Is.EqualTo(this.privateOrgId));

                Assert.That(anonPrivateResult.IsError, Is.False);
                Assert.That(anonPrivateResult.Value.Id, Is.EqualTo(this.privateOrgId));

                Assert.That(notFoundResult.IsError, Is.True);
                Assert.That(notFoundResult.FirstError.Type, Is.EqualTo(ErrorType.NotFound));
            }
        }

        [Test]
        public async Task VerifyUpdateAsync()
        {
            await using var transaction = await this.Connection.BeginTransactionAsync();

            var readResult = await this.service.ReadAsync(this.adminUserContext, transaction, CancellationToken.None, [this.publicOrgId]);
            var organization = readResult.Value.Single();
            organization.Email = "updated-org@example.com";
            organization.BillingEmail = "updated-billing@example.com";
            organization.ModifiedAt = DateTime.UtcNow;

            var anonymousUpdateResult = await this.service.UpdateAsync(this.anonymousUserContext, transaction, [organization], CancellationToken.None);
            var nonAdminUpdateResult = await this.service.UpdateAsync(this.memberUserContext, transaction, [organization], CancellationToken.None);
            var adminUpdateResult = await this.service.UpdateAsync(this.adminUserContext, transaction, [organization], CancellationToken.None);

            var updatedReadResult = await this.service.ReadAsync(this.adminUserContext, transaction, CancellationToken.None, [this.publicOrgId]);

            await transaction.CommitAsync();

            using (Assert.EnterMultipleScope())
            {
                Assert.That(anonymousUpdateResult.IsError, Is.True);
                Assert.That(nonAdminUpdateResult.IsError, Is.True);
                Assert.That(adminUpdateResult.IsError, Is.False);
                Assert.That(updatedReadResult.IsError, Is.False);
                Assert.That(updatedReadResult.Value.Single().Email, Is.EqualTo("updated-org@example.com"));
                Assert.That(updatedReadResult.Value.Single().BillingEmail, Is.EqualTo("updated-billing@example.com"));
            }
        }

        protected override async Task PostSetup()
        {
            var fusionCache = new FusionCache(new FusionCacheOptions());

            var organizationDao = new OrganizationDao(this.TestLoggerFactory.CreateLogger<OrganizationDao>(), this.Serializer, fusionCache);

            var orgPermissionService = new OrganizationPermissionService();

            var databaseSourceMock = new Mock<IDatabaseSource>();

            databaseSourceMock
                .Setup(x => x.OpenNewConnectionAsync(It.IsAny<CancellationToken>()))
                .Returns(async () =>
                {
                    var connection = new NpgsqlConnection(this.ConnectionString);
                    await connection.OpenAsync();
                    return connection;
                });

            this.service = new OrganizationService(organizationDao, new OrganizationValidator(), orgPermissionService, new OrganizationComparer(), this.TestLoggerFactory.CreateLogger<OrganizationService>(), databaseSourceMock.Object);

            this.adminAccountId = Guid.NewGuid();
            this.memberAccountId = Guid.NewGuid();

            this.adminUserContext = new UserContext
            {
                AccountId = this.adminAccountId,
                Username = "adminUser",
                CurrentRoles = [RoleKind.Account, RoleKind.OrganizationAdministrator, RoleKind.OrganizationMember]
            };

            this.memberUserContext = new UserContext
            {
                AccountId = this.memberAccountId,
                Username = "memberUser",
                CurrentRoles = [RoleKind.Account, RoleKind.OrganizationMember]
            };

            this.anonymousUserContext = UserContext.CreateAnonymous();

            await this.SeedDatabaseAsync(organizationDao, this.adminAccountId);
        }

        private async Task SeedDatabaseAsync(OrganizationDao organizationDao, Guid adminAccount)
        {
            var fusionCache = new FusionCache(new FusionCacheOptions());

            var forgeDao = new ForgeDao(this.TestLoggerFactory.CreateLogger<ForgeDao>(), this.Serializer, fusionCache);
            var countryDao = new CountryDao(this.TestLoggerFactory.CreateLogger<CountryDao>(), this.Serializer, fusionCache);
            var addressDao = new AddressDao(this.TestLoggerFactory.CreateLogger<AddressDao>(), this.Serializer, fusionCache);
            var accountDao = new AccountDao(this.TestLoggerFactory.CreateLogger<AccountDao>(), this.Serializer, fusionCache);

            var forgeId = Guid.NewGuid();

            await this.Insert(transaction => forgeDao.CreateAsync(transaction, CancellationToken.None, new Forge
            {
                Id = forgeId,
                Name = "TestForge",
                ShortName = "test-forge",
                Description = "Integration test forge"
            }));

            var countryId = Guid.NewGuid();

            await this.Insert(transaction => countryDao.CreateAsync(transaction, CancellationToken.None, new Country
            {
                Id = countryId,
                Owner = forgeId,
                Alpha2Code = "PT",
                Alpha3Code = "PRT",
                Name = "Portugal",
                NumericCode = "620"
            }));

            var addressId1 = Guid.NewGuid();
            var addressId2 = Guid.NewGuid();

            await this.Insert(async transaction =>
            {
                await using var setConstraints = new NpgsqlCommand("SET CONSTRAINTS ALL DEFERRED;", transaction.Connection, transaction);
                await setConstraints.ExecuteNonQueryAsync();

                var r1 = await addressDao.CreateAsync(transaction, CancellationToken.None, new Address
                {
                    Id = addressId1,
                    Owner = this.memberAccountId,
                    Country = countryId,
                    AddressLine1 = "1 Member Street",
                    Locality = "Lisbon",
                    PostalCode = "1000-001",
                    Region = "LX"
                });

                if (r1.IsError)
                {
                    return r1;
                }

                var r2 = await addressDao.CreateAsync(transaction, CancellationToken.None, new Address
                {
                    Id = addressId2,
                    Owner = adminAccount,
                    Country = countryId,
                    AddressLine1 = "2 Admin Street",
                    Locality = "Porto",
                    PostalCode = "4000-001",
                    Region = "PT"
                });

                if (r2.IsError)
                {
                    return r2;
                }

                var r3 = await accountDao.CreateAsync(transaction, CancellationToken.None, new Account
                {
                    Id = this.memberAccountId,
                    Owner = forgeId,
                    PrimaryAddress = addressId1,
                    Name = "MemberUser",
                    ShortName = "member-user",
                    Email = "member@example.com",
                    BillingEmail = "member-billing@example.com",
                    DefaultPackageVisibility = VisibilityKind.PUBLIC,
                    Status = ScopeStatusKind.ACTIVE,
                    Origin = "https://example.com"
                });

                if (r3.IsError)
                {
                    return r3;
                }

                return await accountDao.CreateAsync(transaction, CancellationToken.None, new Account
                {
                    Id = adminAccount,
                    Owner = forgeId,
                    PrimaryAddress = addressId2,
                    Name = "AdminUser",
                    ShortName = "admin-user",
                    Email = "admin@example.com",
                    BillingEmail = "admin-billing@example.com",
                    DefaultPackageVisibility = VisibilityKind.PUBLIC,
                    Status = ScopeStatusKind.ACTIVE,
                    Origin = "https://example.com"
                });
            });

            this.publicOrgId = Guid.NewGuid();
            this.privateOrgId = Guid.NewGuid();
            var now = DateTime.UtcNow;

            await this.Insert(transaction => organizationDao.CreateAsync(transaction, CancellationToken.None, new Organization
            {
                Id = this.publicOrgId,
                Owner = forgeId,
                PrimaryAddress = addressId2,
                Name = "PublicOrg",
                ShortName = "public-org",
                Email = "public@example.com",
                BillingEmail = "public-billing@example.com",
                DefaultPackageVisibility = VisibilityKind.PUBLIC,
                Status = ScopeStatusKind.ACTIVE,
                Origin = "https://example.com",
                Administrator = [adminAccount],
                Member = [adminAccount],
                CreatedAt = now,
                ModifiedAt = now
            }));

            await this.Insert(transaction => organizationDao.CreateAsync(transaction, CancellationToken.None, new Organization
            {
                Id = this.privateOrgId,
                Owner = forgeId,
                PrimaryAddress = addressId1,
                Name = "PrivateOrg",
                ShortName = "private-org",
                Email = "private@example.com",
                BillingEmail = "private-billing@example.com",
                DefaultPackageVisibility = VisibilityKind.PRIVATE,
                Status = ScopeStatusKind.ACTIVE,
                Origin = "https://example.com",
                Administrator = [adminAccount],
                Member = [adminAccount, this.memberAccountId],
                CreatedAt = now,
                ModifiedAt = now
            }));
        }
    }
}
