// ------------------------------------------------------------------------------------------------
// <copyright file="PackageVersionService.cs" company="Starion Group S.A.">
//
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Dal.AutoGeneratedServices
{
    using System.CodeDom.Compiler;
    using System.Collections.Immutable;

    using FluentResults;

    using Microsoft.Extensions.Logging;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Common.AutoGenDtoComparer;
    using Mycelium.Forge.Dal.AutoGenDtoValidator;
    using Mycelium.Forge.Dal.AutoGenPermissionService;
    using Mycelium.Forge.Dal.DatabaseSource;
    using Mycelium.Forge.Orm.AutoGeneratedDao;
    using Mycelium.Forge.Orm.AutoGeneratedFilters;

    using Npgsql;

    /// <summary>
    /// Service implementation for managing <see cref="IPackageVersion"/> instances, bringing validation, permissions, and data persistence together.
    /// </summary>
    [GeneratedCode("Mycelium.Forge.Generator", "1.0.0")]
    public partial class PackageVersionService : IPackageVersionService
    {
        /// <summary>
        /// The (injected) <see cref="IPackageVersionDao"/> data access object.
        /// </summary>
        private readonly IPackageVersionDao dao;

        /// <summary>
        /// The (injected) <see cref="PackageVersionValidator"/> DTO validator.
        /// </summary>
        private readonly PackageVersionValidator dtoValidator;

        /// <summary>
        /// The (injected) <see cref="IPackageVersionPermissionService"/> permission service.
        /// </summary>
        private readonly IPackageVersionPermissionService permissionService;

        /// <summary>
        /// The (injected) <see cref="PackageVersionComparer"/> DTO comparer.
        /// </summary>
        private readonly PackageVersionComparer dtoComparer;

        /// <summary>
        /// The (injected) <see cref="ILogger{T}"/> logger.
        /// </summary>
        private readonly ILogger<PackageVersionService> logger;

        /// <summary>
        /// The (injected) <see cref="IDatabaseSource"/> database connection provider.
        /// </summary>
        private readonly IDatabaseSource databaseSource;

        /// <summary>
        /// Initializes a new instance of the <see cref="PackageVersionService"/> class.
        /// </summary>
        /// <param name="dao">The (injected) <see cref="IPackageVersionDao"/> data access object.</param>
        /// <param name="dtoValidator">The (injected) <see cref="PackageVersionValidator"/> DTO validator.</param>
        /// <param name="permissionService">The (injected) <see cref="IPackageVersionPermissionService"/> permission service.</param>
        /// <param name="dtoComparer">The (injected) <see cref="PackageVersionComparer"/> DTO comparer.</param>
        /// <param name="logger">The (injected) <see cref="ILogger{T}"/> logger.</param>
        /// <param name="databaseSource">The (injected) <see cref="IDatabaseSource"/> database connection provider.</param>
        public PackageVersionService(
            IPackageVersionDao dao,
            PackageVersionValidator dtoValidator,
            IPackageVersionPermissionService permissionService,
            PackageVersionComparer dtoComparer,
            ILogger<PackageVersionService> logger,
            IDatabaseSource databaseSource)
        {
            ArgumentNullException.ThrowIfNull(dao);
            ArgumentNullException.ThrowIfNull(dtoValidator);
            ArgumentNullException.ThrowIfNull(permissionService);
            ArgumentNullException.ThrowIfNull(dtoComparer);
            ArgumentNullException.ThrowIfNull(logger);
            ArgumentNullException.ThrowIfNull(databaseSource);

            this.dao = dao;
            this.dtoValidator = dtoValidator;
            this.permissionService = permissionService;
            this.dtoComparer = dtoComparer;
            this.logger = logger;
            this.databaseSource = databaseSource;
        }

        /// <summary>
        /// Asynchronously creates (persists) instances of <see cref="IPackageVersion"/> within an existing transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="dtos">The collection of <see cref="IPackageVersion"/> instances to create.</param>
        /// <returns>A <see cref="Result"/> indicating success or failure.</returns>
        public async Task<Result> CreateAsync(IUserContext userContext, NpgsqlTransaction transaction, CancellationToken token, IEnumerable<IPackageVersion> dtos)
        {
            ArgumentNullException.ThrowIfNull(userContext);
            ArgumentNullException.ThrowIfNull(dtos);

            var dtoList = dtos.ToList();

            if (dtoList.Count == 0)
            {
                return Result.Ok();
            }

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting CreateAsync for {Count} PackageVersion instances within transaction", dtoList.Count);
            }

            var validationResult = await this.AreValid(dtoList);

            if (validationResult.IsFailed)
            {
                return validationResult;
            }

            foreach (var dto in dtoList)
            {
                var permissionResult = await this.permissionService.IsAllowedToCreate(userContext, dto);

                if (permissionResult.IsFailed)
                {
                    return permissionResult;
                }
            }

            foreach (var dto in dtoList)
            {
                var createResult = await this.dao.CreateAsync(transaction, token, dto);

                if (createResult.IsFailed)
                {
                    return createResult;
                }
            }

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Finished CreateAsync successfully for {Count} PackageVersion instances", dtoList.Count);
            }

            return Result.Ok();
        }

        /// <summary>
        /// Asynchronously creates (persists) instances of <see cref="IPackageVersion"/> managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="dtos">The collection of <see cref="IPackageVersion"/> instances to create.</param>
        /// <returns>A <see cref="Result"/> indicating success or failure.</returns>
        public async Task<Result> CreateAsync(IUserContext userContext, CancellationToken token, IEnumerable<IPackageVersion> dtos)
        {
            ArgumentNullException.ThrowIfNull(userContext);
            ArgumentNullException.ThrowIfNull(dtos);

            try
            {
                await using var connection = await this.databaseSource.OpenNewConnectionAsync(token);
                await using var transaction = await connection.BeginTransactionAsync(token);

                var result = await this.CreateAsync(userContext, transaction, token, dtos);

                if (result.IsFailed)
                {
                    await transaction.RollbackAsync(token);
                    return result;
                }

                await transaction.CommitAsync(token);
                return Result.Ok();
            }
            catch (Exception exception)
            {
                this.logger.LogError(exception, "CreateAsync for PackageVersion failed with an error");
                return Result.Fail(exception.Message);
            }
        }

        /// <summary>
        /// Asynchronously reads instances of <see cref="IPackageVersion"/> within an existing transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="iids">An optional array of unique identifiers to read.</param>
        /// <returns>A <see cref="Result{TValue}"/> containing an <see cref="ImmutableList{T}"/> of permitted instances.</returns>
        public async Task<Result<ImmutableList<IPackageVersion>>> ReadAsync(IUserContext userContext, NpgsqlTransaction transaction, CancellationToken token, Guid[] iids = null)
        {
            ArgumentNullException.ThrowIfNull(userContext);

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting ReadAsync for PackageVersion within transaction");
            }

            var filter = PackageVersionReadFilter.FromUserContext(userContext);
            var readResult = await this.dao.ReadAsync(transaction, token, iids, filter: filter);

            if (readResult.IsFailed)
            {
                return readResult;
            }

            List<IPackageVersion> permittedItems = [];

            foreach (var item in readResult.Value)
            {
                var permissionResult = await this.permissionService.IsAllowedToRead(userContext, item);

                if (permissionResult.IsSuccess)
                {
                    permittedItems.Add(item);
                }
            }

            return Result.Ok(permittedItems.ToImmutableList());
        }

        /// <summary>
        /// Asynchronously reads instances of <see cref="IPackageVersion"/> managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="iids">An optional array of unique identifiers to read.</param>
        /// <returns>A <see cref="Result{TValue}"/> containing an <see cref="ImmutableList{T}"/> of permitted instances.</returns>
        public async Task<Result<ImmutableList<IPackageVersion>>> ReadAsync(IUserContext userContext, CancellationToken token, Guid[] iids = null)
        {
            ArgumentNullException.ThrowIfNull(userContext);

            try
            {
                await using var connection = await this.databaseSource.OpenNewConnectionAsync(token);
                await using var transaction = await connection.BeginTransactionAsync(token);

                var result = await this.ReadAsync(userContext, transaction, token, iids);

                if (result.IsFailed)
                {
                    await transaction.RollbackAsync(token);
                    return result;
                }

                await transaction.CommitAsync(token);
                return result;
            }
            catch (Exception exception)
            {
                this.logger.LogError(exception, "ReadAsync for PackageVersion failed with an error");
                return Result.Fail(exception.Message);
            }
        }

        /// <summary>
        /// Asynchronously updates instances of <see cref="IPackageVersion"/> within an existing transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="dtos">The collection of <see cref="IPackageVersion"/> instances to update.</param>
        /// <returns>A <see cref="Result"/> indicating success or failure.</returns>
        public async Task<Result> UpdateAsync(IUserContext userContext, NpgsqlTransaction transaction, CancellationToken token, IEnumerable<IPackageVersion> dtos)
        {
            ArgumentNullException.ThrowIfNull(userContext);
            ArgumentNullException.ThrowIfNull(dtos);

            var dtoList = dtos.ToList();

            if (dtoList.Count == 0)
            {
                return Result.Ok();
            }

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting UpdateAsync for {Count} PackageVersion instances within transaction", dtoList.Count);
            }

            var validationResult = await this.AreValid(dtoList);

            if (validationResult.IsFailed)
            {
                return validationResult;
            }

            foreach (var dto in dtoList)
            {
                var filter = PackageVersionReadFilter.FromUserContext(userContext);
                var existingResult = await this.dao.ReadAsync(transaction, token, [dto.Id], filter: filter);

                if (existingResult.IsFailed)
                {
                    return existingResult.ToResult();
                }

                if (existingResult.Value.Count == 0)
                {
                    return Result.Fail($"The {nameof(IPackageVersion)} with ID '{dto.Id}' was not found for update.");
                }

                var existing = existingResult.Value[0];

                var permissionResult = await this.permissionService.IsAllowedToUpdate(userContext, existing, dto);

                if (permissionResult.IsFailed)
                {
                    return permissionResult;
                }

                ServiceHelper.LogChanges(this.logger, this.dtoComparer, existing, dto);

                var updateResult = await this.dao.UpdateAsync(transaction, token, dto);

                if (updateResult.IsFailed)
                {
                    return updateResult;
                }
            }

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Finished UpdateAsync successfully for {Count} PackageVersion instances", dtoList.Count);
            }

            return Result.Ok();
        }

        /// <summary>
        /// Asynchronously updates instances of <see cref="IPackageVersion"/> managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="dtos">The collection of <see cref="IPackageVersion"/> instances to update.</param>
        /// <returns>A <see cref="Result"/> indicating success or failure.</returns>
        public async Task<Result> UpdateAsync(IUserContext userContext, CancellationToken token, IEnumerable<IPackageVersion> dtos)
        {
            ArgumentNullException.ThrowIfNull(userContext);
            ArgumentNullException.ThrowIfNull(dtos);

            try
            {
                await using var connection = await this.databaseSource.OpenNewConnectionAsync(token);
                await using var transaction = await connection.BeginTransactionAsync(token);

                var result = await this.UpdateAsync(userContext, transaction, token, dtos);

                if (result.IsFailed)
                {
                    await transaction.RollbackAsync(token);
                    return result;
                }

                await transaction.CommitAsync(token);
                return Result.Ok();
            }
            catch (Exception exception)
            {
                this.logger.LogError(exception, "UpdateAsync for PackageVersion failed with an error");
                return Result.Fail(exception.Message);
            }
        }

        /// <summary>
        /// Asynchronously deletes instances of <see cref="IPackageVersion"/> within an existing transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="dtos">The collection of <see cref="IPackageVersion"/> instances to delete.</param>
        /// <returns>A <see cref="Result"/> indicating success or failure.</returns>
        public async Task<Result> DeleteAsync(IUserContext userContext, NpgsqlTransaction transaction, CancellationToken token, IEnumerable<IPackageVersion> dtos)
        {
            ArgumentNullException.ThrowIfNull(userContext);
            ArgumentNullException.ThrowIfNull(dtos);

            var dtoList = dtos.ToList();

            if (dtoList.Count == 0)
            {
                return Result.Ok();
            }

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting DeleteAsync for {Count} PackageVersion instances within transaction", dtoList.Count);
            }

            foreach (var dto in dtoList)
            {
                var permissionResult = await this.permissionService.IsAllowedToDelete(userContext, dto);

                if (permissionResult.IsFailed)
                {
                    return permissionResult;
                }
            }

            var deleteResult = await this.dao.DeleteAsync(transaction, token, dtoList);

            if (deleteResult.IsFailed)
            {
                return deleteResult;
            }

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Finished DeleteAsync successfully for {Count} PackageVersion instances", dtoList.Count);
            }

            return Result.Ok();
        }

        /// <summary>
        /// Asynchronously deletes instances of <see cref="IPackageVersion"/> managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="dtos">The collection of <see cref="IPackageVersion"/> instances to delete.</param>
        /// <returns>A <see cref="Result"/> indicating success or failure.</returns>
        public async Task<Result> DeleteAsync(IUserContext userContext, CancellationToken token, IEnumerable<IPackageVersion> dtos)
        {
            ArgumentNullException.ThrowIfNull(userContext);
            ArgumentNullException.ThrowIfNull(dtos);

            try
            {
                await using var connection = await this.databaseSource.OpenNewConnectionAsync(token);
                await using var transaction = await connection.BeginTransactionAsync(token);

                var result = await this.DeleteAsync(userContext, transaction, token, dtos);

                if (result.IsFailed)
                {
                    await transaction.RollbackAsync(token);
                    return result;
                }

                await transaction.CommitAsync(token);
                return Result.Ok();
            }
            catch (Exception exception)
            {
                this.logger.LogError(exception, "DeleteAsync for PackageVersion failed with an error");
                return Result.Fail(exception.Message);
            }
        }

        /// <summary>
        /// Asynchronously validates a collection of <see cref="IPackageVersion"/> instances.
        /// </summary>
        /// <param name="dtos">The collection of <see cref="IPackageVersion"/> instances to validate.</param>
        /// <returns>A <see cref="Result"/> indicating whether all instances are valid.</returns>
        private async Task<Result> AreValid(IEnumerable<IPackageVersion> dtos)
        {
            foreach (var dto in dtos)
            {
                var validationResult = await this.dtoValidator.ValidateDto(dto);

                if (validationResult.IsFailed)
                {
                    return validationResult;
                }
            }

            return Result.Ok();
        }
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
