// ------------------------------------------------------------------------------------------------
// <copyright file="PackageTypeService.cs" company="Starion Group S.A.">
//
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Dal.AutoGeneratedServices
{
    using System.CodeDom.Compiler;
    using System.Collections.Immutable;

    using ErrorOr;

    using Microsoft.Extensions.Logging;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Common.AutoGenDtoComparer;
    using Mycelium.Forge.Dal.AutoGenDtoValidator;
    using Mycelium.Forge.Dal.AutoGenPermissionService;
    using Mycelium.Forge.Dal.DatabaseSource;
    using Mycelium.Forge.Orm.AutoGeneratedDao;
    using Mycelium.Forge.Orm.AutoGeneratedFilters;

    using Npgsql;

    /// <summary>
    /// Service implementation for managing <see cref="IPackageType"/> instances, bringing validation, permissions, and data persistence together.
    /// </summary>
    [GeneratedCode("Mycelium.Forge.Generator", "1.0.0")]
    public partial class PackageTypeService : IPackageTypeService
    {
        /// <summary>
        /// The (injected) <see cref="IPackageTypeDao"/> data access object.
        /// </summary>
        private readonly IPackageTypeDao dao;

        /// <summary>
        /// The (injected) <see cref="PackageTypeValidator"/> DTO validator.
        /// </summary>
        private readonly PackageTypeValidator dtoValidator;

        /// <summary>
        /// The (injected) <see cref="IPackageTypePermissionService"/> permission service.
        /// </summary>
        private readonly IPackageTypePermissionService permissionService;

        /// <summary>
        /// The (injected) <see cref="PackageTypeComparer"/> DTO comparer.
        /// </summary>
        private readonly PackageTypeComparer dtoComparer;

        /// <summary>
        /// The (injected) <see cref="ILogger{T}"/> logger.
        /// </summary>
        private readonly ILogger<PackageTypeService> logger;

        /// <summary>
        /// The (injected) <see cref="IDatabaseSource"/> database connection provider.
        /// </summary>
        private readonly IDatabaseSource databaseSource;

        /// <summary>
        /// Initializes a new instance of the <see cref="PackageTypeService"/> class.
        /// </summary>
        /// <param name="dao">The (injected) <see cref="IPackageTypeDao"/> data access object.</param>
        /// <param name="dtoValidator">The (injected) <see cref="PackageTypeValidator"/> DTO validator.</param>
        /// <param name="permissionService">The (injected) <see cref="IPackageTypePermissionService"/> permission service.</param>
        /// <param name="dtoComparer">The (injected) <see cref="PackageTypeComparer"/> DTO comparer.</param>
        /// <param name="logger">The (injected) <see cref="ILogger{T}"/> logger.</param>
        /// <param name="databaseSource">The (injected) <see cref="IDatabaseSource"/> database connection provider.</param>
        public PackageTypeService(
            IPackageTypeDao dao,
            PackageTypeValidator dtoValidator,
            IPackageTypePermissionService permissionService,
            PackageTypeComparer dtoComparer,
            ILogger<PackageTypeService> logger,
            IDatabaseSource databaseSource)
        {
            ArgumentNullException.ThrowIfNull(dao);
            ArgumentNullException.ThrowIfNull(dtoValidator);
            ArgumentNullException.ThrowIfNull(permissionService);
            ArgumentNullException.ThrowIfNull(dtoComparer);
            ArgumentNullException.ThrowIfNull(logger);
            ArgumentNullException.ThrowIfNull(databaseSource);

            this.dao = dao;
            this.dtoValidator = dtoValidator;
            this.permissionService = permissionService;
            this.dtoComparer = dtoComparer;
            this.logger = logger;
            this.databaseSource = databaseSource;
        }

        /// <summary>
        /// Asynchronously creates (persists) instances of <see cref="IPackageType"/> within an existing transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="dtos">The collection of <see cref="IPackageType"/> instances to create.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Created}"/> indicating success or failure.</returns>
        public async Task<ErrorOr<Created>> CreateAsync(IUserContext userContext, NpgsqlTransaction transaction, IEnumerable<IPackageType> dtos, CancellationToken token)
        {
            ArgumentNullException.ThrowIfNull(userContext);
            ArgumentNullException.ThrowIfNull(dtos);

            var dtoList = dtos.ToList();

            if (dtoList.Count == 0)
            {
                return Result.Created;
            }

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting CreateAsync for {Count} PackageType instances within transaction", dtoList.Count);
            }

            var validationResult = await this.AreValid(dtoList);

            if (validationResult.IsError)
            {
                return validationResult.Errors;
            }

            foreach (var dto in dtoList)
            {
                var permissionResult = await this.permissionService.IsAllowedToCreate(userContext, dto);

                if (permissionResult.IsError)
                {
                    return permissionResult.Errors;
                }
            }

            foreach (var dto in dtoList)
            {
                var createResult = await this.dao.CreateAsync(transaction, token, dto);

                if (createResult.IsError)
                {
                    return createResult.Errors;
                }
            }

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Finished CreateAsync successfully for {Count} PackageType instances", dtoList.Count);
            }

            return Result.Created;
        }

        /// <summary>
        /// Asynchronously creates (persists) instances of <see cref="IPackageType"/> managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="dtos">The collection of <see cref="IPackageType"/> instances to create.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Created}"/> indicating success or failure.</returns>
        public async Task<ErrorOr<Created>> CreateAsync(IUserContext userContext, IEnumerable<IPackageType> dtos, CancellationToken token)
        {
            ArgumentNullException.ThrowIfNull(userContext);
            ArgumentNullException.ThrowIfNull(dtos);

            try
            {
                await using var connection = await this.databaseSource.OpenNewConnectionAsync(token);
                await using var transaction = await connection.BeginTransactionAsync(token);

                var result = await this.CreateAsync(userContext, transaction, dtos, token);

                if (result.IsError)
                {
                    await transaction.RollbackAsync(token);
                    return result.Errors;
                }

                await transaction.CommitAsync(token);
                return Result.Created;
            }
            catch (Exception exception)
            {
                this.logger.LogError(exception, "CreateAsync for PackageType failed with an error");
                return Error.Failure(description: exception.Message);
            }
        }

        /// <summary>
        /// Asynchronously reads instances of <see cref="IPackageType"/> within an existing transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="iids">An optional array of unique identifiers to read.</param>
        /// <returns>A <see cref="ErrorOr{TValue}"/> containing an <see cref="ImmutableList{T}"/> of permitted instances.</returns>
        public async Task<ErrorOr<ImmutableList<IPackageType>>> ReadAsync(IUserContext userContext, NpgsqlTransaction transaction, CancellationToken token, Guid[] iids = null)
        {
            ArgumentNullException.ThrowIfNull(userContext);

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting ReadAsync for PackageType within transaction");
            }

            var filter = PackageTypeReadFilter.FromUserContext(userContext);
            var readResult = await this.dao.ReadAsync(transaction, token, iids, filter: filter);

            if (readResult.IsError)
            {
                return readResult.Errors;
            }

            List<IPackageType> permittedItems = [];

            foreach (var item in readResult.Value)
            {
                var permissionResult = await this.permissionService.IsAllowedToRead(userContext, item);

                if (!permissionResult.IsError)
                {
                    permittedItems.Add(item);
                }
            }

            return permittedItems.ToImmutableList();
        }

        /// <summary>
        /// Asynchronously reads instances of <see cref="IPackageType"/> managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <param name="iids">An optional array of unique identifiers to read.</param>
        /// <returns>A <see cref="ErrorOr{TValue}"/> containing an <see cref="ImmutableList{T}"/> of permitted instances.</returns>
        public async Task<ErrorOr<ImmutableList<IPackageType>>> ReadAsync(IUserContext userContext, CancellationToken token, Guid[] iids = null)
        {
            ArgumentNullException.ThrowIfNull(userContext);

            try
            {
                await using var connection = await this.databaseSource.OpenNewConnectionAsync(token);
                await using var transaction = await connection.BeginTransactionAsync(token);

                var result = await this.ReadAsync(userContext, transaction, token, iids);

                if (result.IsError)
                {
                    await transaction.RollbackAsync(token);
                    return result.Errors;
                }

                await transaction.CommitAsync(token);
                return result;
            }
            catch (Exception exception)
            {
                this.logger.LogError(exception, "ReadAsync for PackageType failed with an error");
                return Error.Failure(description: exception.Message);
            }
        }

        /// <summary>
        /// Asynchronously updates instances of <see cref="IPackageType"/> within an existing transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="dtos">The collection of <see cref="IPackageType"/> instances to update.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Updated}"/> indicating success or failure.</returns>
        public async Task<ErrorOr<Updated>> UpdateAsync(IUserContext userContext, NpgsqlTransaction transaction, IEnumerable<IPackageType> dtos, CancellationToken token)
        {
            ArgumentNullException.ThrowIfNull(userContext);
            ArgumentNullException.ThrowIfNull(dtos);

            var dtoList = dtos.ToList();

            if (dtoList.Count == 0)
            {
                return Result.Updated;
            }

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting UpdateAsync for {Count} PackageType instances within transaction", dtoList.Count);
            }

            var validationResult = await this.AreValid(dtoList);

            if (validationResult.IsError)
            {
                return validationResult.Errors;
            }

            var filter = PackageTypeReadFilter.FromUserContext(userContext);
            var existingDtosResult = await this.dao.ReadAsync(transaction, token, [.. dtoList.Select(x => x.Id)], filter: filter);

            if (existingDtosResult.IsError)
            {
                return existingDtosResult.Errors;
            }

            var existingDtos = existingDtosResult.Value;

            foreach (var dto in dtoList)
            {
                var existing = existingDtos.Find(x => x.Id == dto.Id);

                if (existing == null)
                {
                    return Error.NotFound(description: $"The {nameof(IPackageType)} with ID '{dto.Id}' was not found for update.");
                }

                var permissionResult = await this.permissionService.IsAllowedToUpdate(userContext, existing, dto);

                if (permissionResult.IsError)
                {
                    return permissionResult.Errors;
                }

                ServiceHelper.LogChanges(this.logger, this.dtoComparer, existing, dto);

                var updateResult = await this.dao.UpdateAsync(transaction, token, dto);

                if (updateResult.IsError)
                {
                    return updateResult.Errors;
                }
            }

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Finished UpdateAsync successfully for {Count} PackageType instances", dtoList.Count);
            }

            return Result.Updated;
        }

        /// <summary>
        /// Asynchronously updates instances of <see cref="IPackageType"/> managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="dtos">The collection of <see cref="IPackageType"/> instances to update.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Updated}"/> indicating success or failure.</returns>
        public async Task<ErrorOr<Updated>> UpdateAsync(IUserContext userContext, IEnumerable<IPackageType> dtos, CancellationToken token)
        {
            ArgumentNullException.ThrowIfNull(userContext);
            ArgumentNullException.ThrowIfNull(dtos);

            try
            {
                await using var connection = await this.databaseSource.OpenNewConnectionAsync(token);
                await using var transaction = await connection.BeginTransactionAsync(token);

                var result = await this.UpdateAsync(userContext, transaction, dtos, token);

                if (result.IsError)
                {
                    await transaction.RollbackAsync(token);
                    return result.Errors;
                }

                await transaction.CommitAsync(token);
                return Result.Updated;
            }
            catch (Exception exception)
            {
                this.logger.LogError(exception, "UpdateAsync for PackageType failed with an error");
                return Error.Failure(description: exception.Message);
            }
        }

        /// <summary>
        /// Asynchronously deletes instances of <see cref="IPackageType"/> within an existing transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="transaction">The current <see cref="NpgsqlTransaction" /> to the database.</param>
        /// <param name="iids">The collection of unique identifiers of instances to delete.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Deleted}"/> indicating success or failure.</returns>
        public async Task<ErrorOr<Deleted>> DeleteAsync(IUserContext userContext, NpgsqlTransaction transaction, IEnumerable<Guid> iids, CancellationToken token)
        {
            ArgumentNullException.ThrowIfNull(userContext);
            ArgumentNullException.ThrowIfNull(iids);

            var idList = iids.ToList();

            if (idList.Count == 0)
            {
                return Result.Deleted;
            }

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Starting DeleteAsync for {Count} PackageType instances within transaction", idList.Count);
            }

            var filter = PackageTypeReadFilter.FromUserContext(userContext);
            var existingDtosResult = await this.dao.ReadAsync(transaction, token, [.. idList.ToArray()], filter: filter);

            if (existingDtosResult.IsError)
            {
                return existingDtosResult.Errors;
            }

            var existingDtos = existingDtosResult.Value;

            List<IPackageType> entitiesToDelete = [];

            foreach (var iid in idList)
            {
                var existing = existingDtos.Find(x => x.Id == iid);

                if (existing == null)
                {
                    return Error.NotFound(description: $"The {nameof(IPackageType)} with ID '{iid}' was not found for delete.");
                }

                var permissionResult = await this.permissionService.IsAllowedToDelete(userContext, existing);

                if (permissionResult.IsError)
                {
                    return permissionResult.Errors;
                }

                entitiesToDelete.Add(existing);
            }

            var deleteResult = await this.dao.DeleteAsync(transaction, token, entitiesToDelete);

            if (deleteResult.IsError)
            {
                return deleteResult.Errors;
            }

            if (this.logger.IsEnabled(LogLevel.Debug))
            {
                this.logger.LogDebug("Finished DeleteAsync successfully for {Count} PackageType instances", idList.Count);
            }

            return Result.Deleted;
        }

        /// <summary>
        /// Asynchronously deletes instances of <see cref="IPackageType"/> managing its own connection and transaction.
        /// </summary>
        /// <param name="userContext">The contextual user information and assigned roles.</param>
        /// <param name="iids">The collection of unique identifiers of instances to delete.</param>
        /// <param name="token">The <see cref="CancellationToken"/> used to cancel the operation.</param>
        /// <returns>A <see cref="ErrorOr{Deleted}"/> indicating success or failure.</returns>
        public async Task<ErrorOr<Deleted>> DeleteAsync(IUserContext userContext, IEnumerable<Guid> iids, CancellationToken token)
        {
            ArgumentNullException.ThrowIfNull(userContext);
            ArgumentNullException.ThrowIfNull(iids);

            try
            {
                await using var connection = await this.databaseSource.OpenNewConnectionAsync(token);
                await using var transaction = await connection.BeginTransactionAsync(token);

                var result = await this.DeleteAsync(userContext, transaction, iids, token);

                if (result.IsError)
                {
                    await transaction.RollbackAsync(token);
                    return result.Errors;
                }

                await transaction.CommitAsync(token);
                return Result.Deleted;
            }
            catch (Exception exception)
            {
                this.logger.LogError(exception, "DeleteAsync for PackageType failed with an error");
                return Error.Failure(description: exception.Message);
            }
        }

        /// <summary>
        /// Asynchronously validates a collection of <see cref="IPackageType"/> instances.
        /// </summary>
        /// <param name="dtos">The collection of <see cref="IPackageType"/> instances to validate.</param>
        /// <returns>A <see cref="ErrorOr{Success}"/> indicating whether all instances are valid.</returns>
        private async Task<ErrorOr<Success>> AreValid(IEnumerable<IPackageType> dtos)
        {
            foreach (var dto in dtos)
            {
                var validationResult = await this.dtoValidator.ValidateDto(dto);

                if (validationResult.IsError)
                {
                    return validationResult.Errors;
                }
            }

            return Result.Success;
        }
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
