// ------------------------------------------------------------------------------------------------
// <copyright file="ScopeServiceTestFixture.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Dal.Tests.Services
{
    using System.Collections.Immutable;
    using System.Runtime.CompilerServices;

    using ErrorOr;

    using Microsoft.Extensions.Logging;

    using Moq;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Dal.AutoGeneratedServices;
    using Mycelium.Forge.Dal.DatabaseSource;
    using Mycelium.Forge.Dal.Services;

    using Npgsql;

    using NUnit.Framework;

    /// <summary>
    /// Test fixture for <see cref="ScopeService" />.
    /// </summary>
    [TestFixture]
    public class ScopeServiceTestFixture
    {
        private Mock<IOrganizationService> organizationServiceMock;
        private Mock<IAccountService> accountServiceMock;
        private Mock<IDatabaseSource> databaseSourceMock;
        private Mock<ILogger<ScopeService>> loggerMock;
        private ScopeService service;
        private IUserContext userContext;

        /// <summary>
        /// Sets up mock dependencies and test instances before each test execution.
        /// </summary>
        [SetUp]
        public void SetUp()
        {
            this.organizationServiceMock = new Mock<IOrganizationService>();
            this.accountServiceMock = new Mock<IAccountService>();
            this.databaseSourceMock = new Mock<IDatabaseSource>();
            this.loggerMock = new Mock<ILogger<ScopeService>>();
            this.loggerMock.Setup(x => x.IsEnabled(It.IsAny<LogLevel>())).Returns(true);

            this.service = new ScopeService(
                this.organizationServiceMock.Object,
                this.accountServiceMock.Object,
                this.databaseSourceMock.Object,
                this.loggerMock.Object);

            this.userContext = new UserContext
            {
                AccountId = Guid.NewGuid(),
                Username = "testUser",
                CurrentRoles = [RoleKind.Account]
            };
        }

        /// <summary>
        /// Verifies the <see cref="ScopeService" /> constructor and its parameter null checks.
        /// </summary>
        [Test]
        public void VerifyConstructor()
        {
            using (Assert.EnterMultipleScope())
            {
                Assert.That(() => new ScopeService(null, this.accountServiceMock.Object, this.databaseSourceMock.Object, this.loggerMock.Object), Throws.ArgumentNullException);
                Assert.That(() => new ScopeService(this.organizationServiceMock.Object, null, this.databaseSourceMock.Object, this.loggerMock.Object), Throws.ArgumentNullException);
                Assert.That(() => new ScopeService(this.organizationServiceMock.Object, this.accountServiceMock.Object, null, this.loggerMock.Object), Throws.ArgumentNullException);
                Assert.That(() => new ScopeService(this.organizationServiceMock.Object, this.accountServiceMock.Object, this.databaseSourceMock.Object, null), Throws.ArgumentNullException);

                var instance = new ScopeService(
                    this.organizationServiceMock.Object,
                    this.accountServiceMock.Object,
                    this.databaseSourceMock.Object,
                    this.loggerMock.Object);

                Assert.That(instance, Is.Not.Null);
            }
        }

        /// <summary>
        /// Verifies all scenarios for reading scopes asynchronously.
        /// </summary>
        /// <returns>An awaitable <see cref="Task" />.</returns>
        [Test]
        public async Task VerifyReadAsync()
        {
            var dummyTransaction = (NpgsqlTransaction)RuntimeHelpers.GetUninitializedObject(typeof(NpgsqlTransaction));
            var org = new Organization { Id = Guid.NewGuid(), Name = "Org", ShortName = "org" };
            var account = new Account { Id = Guid.NewGuid(), Name = "Acc", ShortName = "acc" };
            var queryIds = new[] { org.Id, account.Id };

            // Null checks
            using (Assert.EnterMultipleScope())
            {
                Assert.ThrowsAsync<ArgumentNullException>(async () => await this.service.ReadAsync(null, dummyTransaction, CancellationToken.None));
                Assert.ThrowsAsync<ArgumentNullException>(async () => await this.service.ReadAsync(this.userContext, null, CancellationToken.None));
                Assert.ThrowsAsync<ArgumentNullException>(async () => await this.service.ReadAsync(null, CancellationToken.None));
            }

            // Case: Both services return errors
            this.organizationServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), It.IsAny<Guid[]>()))
                .ReturnsAsync(Error.Failure(description: "Org failure"));

            this.accountServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), It.IsAny<Guid[]>()))
                .ReturnsAsync(Error.Failure(description: "Account failure"));

            var bothFailResult = await this.service.ReadAsync(this.userContext, dummyTransaction, CancellationToken.None);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(bothFailResult.IsError, Is.True);
                Assert.That(bothFailResult.Errors[0].Description, Is.EqualTo("Org failure"));
            }

            // Case: Org succeeds, Account fails -> returns error
            this.organizationServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), It.IsAny<Guid[]>()))
                .ReturnsAsync(ImmutableList.Create<IOrganization>(org));

            this.accountServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), It.IsAny<Guid[]>()))
                .ReturnsAsync(Error.Failure(description: "Account failure"));

            var accountFailResult = await this.service.ReadAsync(this.userContext, dummyTransaction, CancellationToken.None);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(accountFailResult.IsError, Is.True);
                Assert.That(accountFailResult.Errors[0].Description, Is.EqualTo("Account failure"));
            }

            // Case: Org fails, Account succeeds -> returns error
            this.organizationServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), It.IsAny<Guid[]>()))
                .ReturnsAsync(Error.Failure(description: "Org failure"));

            this.accountServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), It.IsAny<Guid[]>()))
                .ReturnsAsync(ImmutableList.Create<IAccount>(account));

            var orgFailResult = await this.service.ReadAsync(this.userContext, dummyTransaction, CancellationToken.None);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(orgFailResult.IsError, Is.True);
                Assert.That(orgFailResult.Errors[0].Description, Is.EqualTo("Org failure"));
            }

            // Case: Org returns NotFound, Account succeeds -> ignores NotFound and returns account
            this.organizationServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), It.IsAny<Guid[]>()))
                .ReturnsAsync(Error.NotFound(description: "Org not found"));

            this.accountServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), It.IsAny<Guid[]>()))
                .ReturnsAsync(ImmutableList.Create<IAccount>(account));

            var orgNotFoundResult = await this.service.ReadAsync(this.userContext, dummyTransaction, CancellationToken.None);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(orgNotFoundResult.IsError, Is.False);
                Assert.That(orgNotFoundResult.Value, Has.Count.EqualTo(1));
                Assert.That(orgNotFoundResult.Value[0].Id, Is.EqualTo(account.Id));
            }

            // Case: Requested IIDs not found in either service -> returns NotFound error
            this.organizationServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), queryIds))
                .ReturnsAsync(ImmutableList<IOrganization>.Empty);

            this.accountServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), queryIds))
                .ReturnsAsync(ImmutableList<IAccount>.Empty);

            var notFoundResult = await this.service.ReadAsync(this.userContext, dummyTransaction, CancellationToken.None, queryIds);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(notFoundResult.IsError, Is.True);
                Assert.That(notFoundResult.Errors[0].Type, Is.EqualTo(ErrorType.NotFound));
            }

            // Case: Short-circuiting when all query IDs are found in Org service -> Account service is not called
            var singleOrgQueryIds = new[] { org.Id };

            this.organizationServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), singleOrgQueryIds))
                .ReturnsAsync(ImmutableList.Create<IOrganization>(org));

            this.accountServiceMock.Invocations.Clear();

            var shortCircuitResult = await this.service.ReadAsync(this.userContext, dummyTransaction, CancellationToken.None, singleOrgQueryIds);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(shortCircuitResult.IsError, Is.False);
                Assert.That(shortCircuitResult.Value, Has.Count.EqualTo(1));
                this.accountServiceMock.Verify(x => x.ReadAsync(It.IsAny<IUserContext>(), It.IsAny<NpgsqlTransaction>(), It.IsAny<CancellationToken>(), It.IsAny<Guid[]>()), Times.Never());
            }

            // Case: Both services succeed with specific IDs
            this.organizationServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), queryIds))
                .ReturnsAsync(ImmutableList.Create<IOrganization>(org));

            this.accountServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), It.Is<Guid[]>(ids => ids.Length == 1 && ids[0] == account.Id)))
                .ReturnsAsync(ImmutableList.Create<IAccount>(account));

            var bothSuccessResult = await this.service.ReadAsync(this.userContext, dummyTransaction, CancellationToken.None, queryIds);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(bothSuccessResult.IsError, Is.False);
                Assert.That(bothSuccessResult.Value, Has.Count.EqualTo(2));
                Assert.That(bothSuccessResult.Value[0].Id, Is.EqualTo(org.Id));
                Assert.That(bothSuccessResult.Value[1].Id, Is.EqualTo(account.Id));
            }

            // Case: Both services succeed with empty array (queries all)
            this.organizationServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), null))
                .ReturnsAsync(ImmutableList.Create<IOrganization>(org));

            this.accountServiceMock.Setup(x => x.ReadAsync(this.userContext, dummyTransaction, It.IsAny<CancellationToken>(), null))
                .ReturnsAsync(ImmutableList.Create<IAccount>(account));

            var emptyArrayResult = await this.service.ReadAsync(this.userContext, dummyTransaction, CancellationToken.None, []);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(emptyArrayResult.IsError, Is.False);
                Assert.That(emptyArrayResult.Value, Has.Count.EqualTo(2));
                Assert.That(emptyArrayResult.Value[0].Id, Is.EqualTo(org.Id));
                Assert.That(emptyArrayResult.Value[1].Id, Is.EqualTo(account.Id));
            }

            // Case: Standalone connection exception handled gracefully
            this.databaseSourceMock.Setup(x => x.OpenNewConnectionAsync(It.IsAny<CancellationToken>()))
                .ThrowsAsync(new InvalidOperationException("Connection failed"));

            var connectionFailResult = await this.service.ReadAsync(this.userContext, CancellationToken.None);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(connectionFailResult.IsError, Is.True);
                Assert.That(connectionFailResult.Errors[0].Description, Does.Contain("Connection failed"));
            }
        }
    }
}
