<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>Mycelium.Forge.Dal.Tests</AssemblyName>
        <RootNamespace>Mycelium.Forge.Dal.Tests</RootNamespace>
        <LangVersion>14.0</LangVersion>
        <Company>Starion Group S.A.</Company>
        <Authors>Sam Gerene</Authors>
        <Description>NUnit test suite for the Mycelium.Forge.Dal project</Description>
        <Copyright>Copyright © Starion Group S.A.</Copyright>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/mycelium-cmbse/mycelium-forge</RepositoryUrl>
        <RepositoryType>Git</RepositoryType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="NUnit" Version="4.3.2" />
        <PackageReference Include="NUnit.Analyzers" Version="4.6.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mycelium.Forge.Common\Mycelium.Forge.Common.csproj" />
        <ProjectReference Include="..\Mycelium.Forge.Dal\Mycelium.Forge.Dal.csproj" />
    </ItemGroup>

</Project>
