// ------------------------------------------------------------------------------------------------
// <copyright file="DatabaseSeederTestFixture.cs" company="Starion Group S.A.">
// 
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
// 
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace Mycelium.Forge.Tests.Data
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Threading;
    using System.Threading.Tasks;

    using ErrorOr;

    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.Logging;

    using Moq;

    using Mycelium.Forge.Common;
    using Mycelium.Forge.Dal.AutoGeneratedServices;
    using Mycelium.Forge.Dal.DatabaseSource;
    using Mycelium.Forge.Data;
    using Mycelium.Forge.Extensions;
    using Mycelium.Forge.Orm;

    using Npgsql;

    [TestFixture]
    public class DatabaseSeederTestFixture
    {
        private Mock<IForgeService> forgeServiceMock;
        private Mock<ICountryService> countryServiceMock;
        private Mock<IPackageTypeService> packageTypeServiceMock;
        private Mock<IAccountService> accountServiceMock;
        private Mock<IOrganizationService> organizationServiceMock;
        private Mock<IPackageService> packageServiceMock;
        private Mock<IPackageVersionService> packageVersionServiceMock;
        private Mock<IAPIKeyService> apiKeyServiceMock;
        private Mock<IDatabaseSource> databaseSourceMock;
        private Mock<ILogger<DatabaseSeeder>> loggerMock;
        private DatabaseConfig databaseConfig;
        private DatabaseSeeder databaseSeeder;

        [SetUp]
        public void SetUp()
        {
            this.forgeServiceMock = new Mock<IForgeService>();
            this.countryServiceMock = new Mock<ICountryService>();
            this.packageTypeServiceMock = new Mock<IPackageTypeService>();
            this.accountServiceMock = new Mock<IAccountService>();
            this.organizationServiceMock = new Mock<IOrganizationService>();
            this.packageServiceMock = new Mock<IPackageService>();
            this.packageVersionServiceMock = new Mock<IPackageVersionService>();
            this.apiKeyServiceMock = new Mock<IAPIKeyService>();
            this.databaseSourceMock = new Mock<IDatabaseSource>();
            this.loggerMock = new Mock<ILogger<DatabaseSeeder>>();

            var configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", true, false)
                .AddJsonFile("appsettings.Development.json", true, false)
                .AddEnvironmentVariables()
                .Build();

            this.databaseConfig = configuration.GetDatabaseConfig();

            this.databaseSourceMock
                .Setup(x => x.OpenNewConnectionAsync(It.IsAny<CancellationToken>()))
                .Returns(async (CancellationToken cancellationToken) =>
                {
                    var connection = new NpgsqlConnection(this.databaseConfig.BuildConnectionString());
                    await connection.OpenAsync(cancellationToken);
                    return connection;
                });

            this.forgeServiceMock
                .Setup(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IForge>>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(Result.Created);

            this.countryServiceMock
                .Setup(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<ICountry>>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(Result.Created);

            this.packageTypeServiceMock
                .Setup(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IPackageType>>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(Result.Created);

            this.accountServiceMock
                .Setup(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IAccount>>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(Result.Created);

            this.organizationServiceMock
                .Setup(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IOrganization>>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(Result.Created);

            this.packageServiceMock
                .Setup(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IPackage>>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(Result.Created);

            this.packageVersionServiceMock
                .Setup(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IPackageVersion>>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(Result.Created);

            this.apiKeyServiceMock
                .Setup(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IAPIKey>>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(Result.Created);

            this.databaseSeeder = new DatabaseSeeder(
                this.forgeServiceMock.Object,
                this.countryServiceMock.Object,
                this.packageTypeServiceMock.Object,
                this.accountServiceMock.Object,
                this.organizationServiceMock.Object,
                this.packageServiceMock.Object,
                this.packageVersionServiceMock.Object,
                this.apiKeyServiceMock.Object,
                this.databaseSourceMock.Object,
                this.databaseConfig,
                this.loggerMock.Object);
        }

        [Test]
        public async Task VerifySeedAsync()
        {
            var successResult = await this.databaseSeeder.SeedAsync(CancellationToken.None);

            using (Assert.EnterMultipleScope())
            {
                Assert.That(successResult, Is.True);
                this.forgeServiceMock.Verify(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IForge>>(), It.IsAny<CancellationToken>()), Times.Once);
                this.countryServiceMock.Verify(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<ICountry>>(), It.IsAny<CancellationToken>()), Times.Once);
                this.packageTypeServiceMock.Verify(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IPackageType>>(), It.IsAny<CancellationToken>()), Times.Once);
                this.accountServiceMock.Verify(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IAccount>>(), It.IsAny<CancellationToken>()), Times.Once);
                this.organizationServiceMock.Verify(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IOrganization>>(), It.IsAny<CancellationToken>()), Times.Once);
                this.packageServiceMock.Verify(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IPackage>>(), It.IsAny<CancellationToken>()), Times.Once);
                this.packageVersionServiceMock.Verify(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IPackageVersion>>(), It.IsAny<CancellationToken>()), Times.Once);
                this.apiKeyServiceMock.Verify(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IAPIKey>>(), It.IsAny<CancellationToken>()), Times.Once);
            }

            this.forgeServiceMock
                .Setup(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IForge>>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(Error.Failure(description: "Failed to create root Forge"));

            var forgeFailureResult = await this.databaseSeeder.SeedAsync(CancellationToken.None);
            Assert.That(forgeFailureResult, Is.False);

            this.forgeServiceMock
                .Setup(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IForge>>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(Result.Created);

            this.accountServiceMock
                .Setup(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IAccount>>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(Error.Failure(description: "Failed to create accounts"));

            var accountFailureResult = await this.databaseSeeder.SeedAsync(CancellationToken.None);
            Assert.That(accountFailureResult, Is.False);

            this.accountServiceMock
                .Setup(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IAccount>>(), It.IsAny<CancellationToken>()))
                .ReturnsAsync(Result.Created);

            this.packageServiceMock
                .Setup(x => x.CreateAsync(It.IsAny<IUserContext>(), It.IsAny<IEnumerable<IPackage>>(), It.IsAny<CancellationToken>()))
                .ThrowsAsync(new InvalidOperationException("Simulated unexpected exception during package seeding"));

            var exceptionResult = await this.databaseSeeder.SeedAsync(CancellationToken.None);
            Assert.That(exceptionResult, Is.False);

            this.databaseConfig.Host = "unreachable-host-for-testing";
            var resetFailureResult = await this.databaseSeeder.SeedAsync(CancellationToken.None);
            Assert.That(resetFailureResult, Is.False);
        }
    }
}
